### ISSUE TITLE
Cache Control for 404 response

### ISSUE THREAD

**Issue by oleghalin** [unjs/nitro#1001]
### Environment

Cloudflare Workers (i think all envs have same logic)

### Reproduction

Try to access localhost:3000/_nuxt/test.css and see Cache Control headers. 

### Describe the bug

I think nitro shouldnt cache 404's errors by default or atleast with different rules. For now we are facing issue when user visited page after deploy and 404 response was cached in browser.

**Comment by pi0** [comment]
Hi. Can you please share nuxt/nitro versions?

**Comment by oleghalin** [comment]
It's latest 2.2.3

**Comment by oleghalin** [comment]
@pi0 here is example, https://test-docus.vercel.app/_nuxt/test.css.


As you see cache-control exists here, while response status is 404
```
age: 3
cache-control: public, max-age=2592000, immutable
content-encoding: br
content-type: text/html;charset=utf-8
date: Wed, 01 Mar 2023 13:11:00 GMT
server: Vercel
```

**Comment by pi0** [comment]
Hi. I'm not sure if the deployment (cannot see source of open it anymore) were depending on cache headers generated by vercel edge or nitro so please feel free to open new issue with reproduction if facing similar issues.
