### ISSUE TITLE
Custom Ports

### ISSUE THREAD

**Issue by lautiamkok** [unjs/nitro#1028]
### Describe the feature

It will make more sense if we can set a custom port in Nitro. Currently, it is impossible to set that. For example, it would be great if we can set the custom port in the config file as follows:

```
// nitro.config.ts
import { defineNitroConfig } from 'nitropack'

export default defineNitroConfig({
  server: {
    port: 5000,
  } 
})
```

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by lautiamkok** [comment]
It seems that this only can be done in a .env file:

```
// .env
PORT=5000
```

Maybe that is just fine.

**Comment by fmoessle** [comment]
Doesn't work for me. Also `PORT=5000 yarn dev` doesn't change the port.
