### ISSUE TITLE
Prerender crawler breaks for links with spaces

### ISSUE THREAD

**Issue by juliesaia** [unjs/nitro#1029]
### Environment

Nitro: 2.2.3

### Reproduction

https://stackblitz.com/edit/nuxt-starter-1qwjem?file=pages/index.vue

### Describe the bug

Links with spaces in the `href` get cut off by the regex in `prerender.ts`. In the min repro, it should prerender `/link with space` but it prerenders `/link` instead.

### Logs

```
ℹ Initializing prerenderer                                                                                                       nitro 05:48:07
ℹ Prerendering 1 initial routes with crawler                                                                                     nitro 05:48:09
  ├─ / (103ms)                                                                                                                   nitro 05:48:09
  ├─ /link (8ms)
```

**Comment by pi0** [comment]
Thanks for issue and reproduction.

For reference, space is not allowed in HTML spec for values: 

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/5158436/223406636-982aed2b-c61d-4a70-9609-52d25e2a13b7.png">
