### ISSUE TITLE
Nuxt with netlify-edge preset getting 404 error with no error in logs

### ISSUE THREAD

**Issue by koronowicz** [unjs/nitro#1040]
### Environment

Nuxt 3.2.3, SSR, ```netlify-edge``` preset

### Reproduction

Clear installation of Nuxt deployed to Netlify with ```preset: 'netlify-edge'```

### Describe the bug

I have a problem with running Nuxt 3.2.3, SSR on Netlify with ```netlify-edge``` preset. When opening URL I got Netlify 404 error. In logs no errors and in Edge Functions part:

```
11:47:41 AM:   2. Edge Functions bundling                                    
11:47:41 AM: ────────────────────────────────────────────────────────────────
11:47:41 AM: ​
11:47:41 AM: ​
11:47:41 AM: (Edge Functions bundling completed in 494ms)
```

Paths to files are the same as in ```preset: 'netlify'```, and this preset is working.

**Comment by koronowicz** [comment]
Update: there is no problem with ``vercel-edge`` preset:

``


[info] [nitro] Building Nitro Server (preset: `vercel-edge`)
--
13:49:31.916 | [success] [nitro] Nitro server built
13:49:32.095 | └─ .vercel/output/functions/__nitro.func/index.mjs (3.64 MB) (992 kB gzip)
13:49:32.095 | Σ Total size: 3.64 MB (992 kB gzip)
13:49:32.266 | Build Completed in /vercel/output [1m]
13:49:32.448 | Deploying outputs...
13:49:41.092 | Generated build outputs:


``

**Comment by Hebilicious** [comment]
@koronowicz Could you please provide a reproduction 🙏 ?
