### ISSUE TITLE
Prerender assets on nitro side during crawl-based generation

### ISSUE THREAD

**Issue by d0rich** [unjs/nitro#1044]
### Describe the feature

Now, as I understood, Nitro can prerender routes as `HTML` and `JSON` files only. Other types of static files (`png`, `pdf`, etc) should be placed in `public` folder before generation.

It would be great to also generate files from routes like `/cover/[post_id].jpeg` which returns buffer with file info. It is useful for generation of images for blog posts. This algorithm works in runtime - browser successfully gets file generated from link, but files are not appearing in `.output/public` folder.

I also tried to generate PDF in this way and it does not work for prerender. This feature would be great for SSG. 

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by danielroe** [comment]
It should be possible to render other types of files this way. I use it to render binary files all the time, including images.

If you are encountering any issues, please do raise an issue with a minimal reproduction. 🙏

**Comment by d0rich** [comment]
My apologies. This functionality works fine. My problem caused by failed attempt of puppeteer to access route during prerender. 
Is application served on any address during prerender? I tried to get some info from requests, there is only header `host: localhost`.

**Comment by d0rich** [comment]
As I can see from source code during prerender H3App is not available by link, but we have access with provided `$fetch`.

I was able to implement workaround: instead of accessing the application by link from puppeteer I accessed HTML with `$fetch` and past it to the page in puppeteer. 

Problem was links to CSS files. They are not loaded with fetch. I parsed HTML, and loaded these CSS files one by one and past it to HTML under `<style>` tag. It is not elegant, but it worked and is enough for me.

```ts
import puppeteer from 'puppeteer'
import { parse } from 'node-html-parser'
import * as fs from 'fs'

export default defineEventHandler(async (event) => {
  // Get HTML page
  const html = await $fetch<string>('/resume')
  
  // Get required CSS styles
  const parsedHtml = parse(html)
  const head = parsedHtml.querySelector('head')
  if (!head) return
  const cssRels = head.querySelectorAll('link')
  for (let cssRel of cssRels) {
    const href = cssRel.getAttribute('href')
    if (!href?.endsWith('.css')) continue
    // CSS files are already compiled, so we can get it with filesystem
    const style = fs.readFileSync('./dist' + href, { encoding: 'utf-8' })
    // Add CSS to HTML under style tag
    head.appendChild(parse(`<style>${style}</style>`))
  }
  
  // Convert page to pdf with puppeteer
  const browser = await puppeteer.launch(({ headless: true }))
  const page = await browser.newPage()
  await page.setContent(parsedHtml.toString(), { waitUntil: 'domcontentloaded' })
  await page.emulateMediaType('print')
  // Some custom logic
  await page.evaluate(() => {
    let html = document.querySelector('html')
    if (html) {
      html.className = 'light'
    }
 })
  const pdf = await page.pdf({
    //path: 'result.pdf',
    printBackground: true,
    format: 'A4',
  })
  await browser.close()
  return pdf
})
```
