### ISSUE TITLE
Edge functions has crashed

### ISSUE THREAD

**Issue by Mnigos** [unjs/nitro#1084]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app`, `components`, `modules`, `css`, `build`, `runtimeConfig`, `proxy`, `graphql-client`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.2`, `nuxt-windicss@2.5.5`, `nuxt-proxy@0.3.4`, `nuxt-graphql-client@0.2.13`
- Build Modules:    `-`

### Reproduction

Cannot reproduce this issue without using external `NITRO_PRESET` provider like `vercel` of `netlify`

### Describe the bug

Edge functions crashes with `NITRO_PRESET` set to `vercel-edge` or `netlify-edge` I tried to deploy my app on both services.

### Logs

```sh
Netlify error:

Mar 24, 02:06:19 PM: error  TypeError: Pn.Debug.extend is not a function
    at file:///root/.netlify/edge-functions/server.js:1:160277Mar 24, 02:06:41 PM: error  TypeError: Pn.Debug.extend is not a function
    at file:///root/.netlify/edge-functions/server.js:1:160277
```

Vercel error:
```
[GET] / reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
TypeError: Sn.Debug.extend is not a function
    at (index.mjs:1:160264)
    at (__nitro:middleware.js:1:17)
```
```

**Comment by pi0** [comment]
Can you please open an issue in nuxt repository with reproduction? 🙏🏼 (from above info, i can only guess nuxt-proxy might cause some issues. we have `proxy` option in `routeRules` you can replace it with)
