### ISSUE TITLE
Built-in proxy support

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#113]
Adding as a feature to route rules.

**Comment by DamianGlowala** [comment]
@pi0, would you be able to give any ETA on this one? 🙏 Would be super useful to have it working in Nuxt 3.

**Comment by ironytr** [comment]
can't use nuxt3@latest because proxy issues, non module working rn. is nitro proxy ready yet?

**Comment by makkarpov** [comment]
devProxy doesn't seem to be supporting relative URL in fetch, is this by design?

I.e.

```javascript
// config:
export default defineNuxtConfig({
    nitro: {
        devProxy: {
            '/api/': {
                target: process.env.API_TARGET,
                changeOrigin: true
            }
        }
    }
})

// ======================
// later, on server side:
// ======================

const r = await (await fetch('/api/test')).json();
// => 500 Invalid URL
```

**Comment by frasza** [comment]
Any indication when it will be fully implemented?

**Comment by makkarpov** [comment]
@pi0

> Yes. You need to pass full URLs because dev proxy is outside of worker and needs to make an actual request.

But this breaks code unification between client and server. In browser, when I make a `/api/xxx` request, browser will resolve it to my domain automatically. So it's natural to assume same behavior in SSR context - relative requests should finally end up being proxied. Or resolved to absolute URLs via proxy config and executed normally.

**Comment by makkarpov** [comment]
It's also desirable (but far less annoying) to proxy WebSocket request for same reason. This time things are even more complicated: you have to invent ad-hoc logic _on client_. This means, you need to put all your backend paths into a `runtimeConfig`, check if it's dev or prod, use relative paths on prod (nginx is completely fine with websockets), match correct backend on dev, build an URL.

**Comment by pi0** [comment]
Web socket layer and runtime proxy support (with direct fetch ability) are on the way :)

**Comment by PavlosMac** [comment]
> Web socket layer and runtime proxy support (with direct fetch ability) are on the way :)

Available yet?

**Comment by Arturexe** [comment]
Will this be available soon? I can't send auth requests to my backend because of it. Before this is integrated, I can't use Nuxt 3.

**Comment by bogumilkorek** [comment]
Some ETA would me much appreciated. Our team is also waiting for this.

**Comment by paulvonber** [comment]
Any news on it?

**Comment by MiniDigger** [comment]
bumping this every day certainly will not make it faster, plus it annoys everyone who subscribed to this issue for actual updates, so please, just don't.

**Comment by michauds** [comment]
Commenting here in case this info is useful to anyone. For some reason, I couldn't get vite proxy to match any of the regex I was writing.

After investigation, it seems like all the routes tested by vite are prefixed with `__url`. This means that if I want to proxy `^/vegetables/.*`, I actually need to write the following route in the vite server proxy options: `^/__url/vegetables/.*`.

For context, the configured root route on my project is a catch-all, (`pages/[...slug].ts`).
