### ISSUE TITLE
Support cloudflare KV bindings for `cloudflare-pages` and `cloudflare-module` presets

### ISSUE THREAD

**Issue by stenet** [unjs/nitro#1132]
### Environment

Cloudflare Pages

### Reproduction

Not sure whether this is an error or not and whether this is the correct place ...

I've created a simple Nuxt-App with Storage [https://github.com/stenet/nuxt-storage-cf](https://github.com/stenet/nuxt-storage-cf).

While deploying the App in Cloudflare Pages at the end an error is thrown:
![image](https://user-images.githubusercontent.com/1838511/231521073-9816923c-3ae0-4a42-b45d-813415bdcfab.png)

[nuxt-storage-cf.ae48777b-dbd5-4a9d-832d-80a70ba6fdc9.log](https://github.com/unjs/unstorage/files/11213724/nuxt-storage-cf.ae48777b-dbd5-4a9d-832d-80a70ba6fdc9.log)

This is the KV namespace binding I've configured:
![image](https://user-images.githubusercontent.com/1838511/231521257-340f7ada-45d4-4953-b910-14e80e494385.png)

When I remove Nitro storage and use `ev.context.cloudflare.env.KV123` inside `test.get.ts` it works without errors.

### Describe the bug

See above.

**Comment by pi0** [comment]
Cloudflare module format (used by pages) does not support KV yet. Since we need to access env from global.

**Comment by Atinux** [comment]
Error is thrown by https://github.com/unjs/unstorage/blob/a336cafd559a34087db99303d9ce06532cd03fb8/src/drivers/cloudflare-kv-binding.ts#L46

We may have to rethink to create the storage only when a request come in, so far you can create the storage inside the router as a workaround

**Comment by pi0** [comment]
Support for CF bindings in module mode should be possible in the latest nitropack edge. You can early try using resolutions in `package.json`: (make sure to also renew lockfile)

```js
{
  "resolutions": {
    "nitropack": "npm:nitropack-edge@latest"
  }
}
```

**Comment by Hebilicious** [comment]
This got added in v2.4.0
