### ISSUE TITLE
Cannot serve images or fonts file on azure-function no matter files' size 

### ISSUE THREAD

**Issue by gyhyfj** [unjs/nitro#1134]
### Environment

azure-function 
node: '18.x'
runs-on: ubuntu-latest

### Reproduction

Hi, I met a problem after deploy my nuxt3 ssr app to azure-function successfully,

For example, I cannot get my website favicon, with:
`GET https://xxxx.azurewebsites.net/favicon.ico      net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)`  
It's `2.52kb`,  in `/public` dir, seems no mater how big it's size is.

What should I do?

### Describe the bug

As above
But images which is smaller than 4kb in `/assets` is ok because of transform to base64 already

### Logs
```
[2023-04-14T07:03:09.644Z] An unhandled host error has occurred.
[2023-04-14T07:03:09.645Z] Microsoft.AspNetCore.Server.Kestrel.Core: Response Content-Length mismatch: too many bytes written (3835 of 2587).
```
online:
```
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
``
_No response_

**Comment by danielroe** [comment]
I would recommend using the Azure SWA preset as it will not serve the assets directly from the serverless function. Is there a reason you want to use the function preset instead?

**Comment by gyhyfj** [comment]
Thank you , I just wonder if I can deploy ssr project(with no prerender, and with some server api in `/server`) instead of ssg project on Azure SWA?

**Comment by danielroe** [comment]
Yes, the Azure SWA app can be fully SSR.
