### ISSUE TITLE
Support Firebase functions v2 (2nd Gen) as a deploy target.

### ISSUE THREAD

**Issue by JamieCurnow** [unjs/nitro#1141]
### Describe the feature

Almost exactly the same as the current `firebase` preset, but make the generated cloud function a 2nd gen function and expose some config to set region, min/max instances etc.

The cloud functions v2 are in beta at the moment and the documentation is here:
https://firebase.google.com/docs/functions/beta

Though Google claim that they are in GA here:
https://cloud.google.com/blog/products/serverless/cloud-functions-2nd-generation-now-generally-available

Proposal is a new preset `firebaseV2` that will extend the current firebase preset, but just use a different import to take advantage of the new features of firebase functions v2.

There has been a few issues #1098 #666 that express a valid requirement for configuring cloud functions, so this feature also includes an easy way to inject options into the cloud function call through the nirto runtime config. This allows the developer to control all options of the firebase function such as region, min/max instances etc.

The options are detailed here:
https://firebase.google.com/docs/reference/functions/2nd-gen/node/firebase-functions.https.httpsoptions

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by JamieCurnow** [comment]
PR incoming...

**Comment by mcfarljw** [comment]
I think Cloud Functions v2 has been moved out of beta. I'm looking to take advantage of the improved concurrency.
