### ISSUE TITLE
Add tests for process.env support

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1150]
Cloudflare preset now supports global env. We shall add tests to verify `process.env.FOO_BAR` dynamic access works as expected across presets (and ignore the one's still have known issues)

**Comment by pi0** [comment]
Need to also add tests for Deno and Netlify Edge /cc @Atinux

**Comment by LarchLiu** [comment]
when i use `deno` preset to build nitro app and set env in deno deploy, it can't access those environment variables.
