### ISSUE TITLE
Hook for catching errors

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1152]
Related https://github.com/nuxt/nuxt/issues/20113

A hook like `error` or `nitro:error` within plugins could be particularly useful. 

Requirements:

- Hook should be non-blocking 
- Hook should allow accessing event context but prevent to modify / end response

**Comment by mao-shonen** [comment]
related unjs/h3#377

Capturing errors from external packages is a common use case,
In addition to onError, adding a onRawError handle other package errors is also useful.

**Comment by DrJume** [comment]
done? https://github.com/unjs/nitro/pull/1463
