### ISSUE TITLE
Cannot find module 'h3'

### ISSUE THREAD

**Issue by kleinpetr** [unjs/nitro#1166]
### Environment

OS: Linux Fedora 37
Node: v18.15.0
Nitro: 2.3.3
pnpm: 8.2.0

### Reproduction

1. `pnpm dlx giget@latest nitro test-app`
2. `pnpm dev`
3. open `nitro-imports.d.ts`

### Describe the bug

I am facing an issue with auto-imports. When I use `event` within `eventHandler((event)=>...)` is has `any` type. So when I go to the function definition it takes me to auto-imports and it seems that cannot resolve `h3` dep

![image](https://user-images.githubusercontent.com/17269309/232599738-715e1ef6-e072-418c-8876-8c0c8f25e223.png)

**Comment by danielroe** [comment]
I suspect you are not hoisting dependencies (which is fine) and so you may need to add `h3` to your dependencies.

**Comment by kleinpetr** [comment]
Ok, `shamefully-hoist=true` fixed it ;)

**Comment by kleinpetr** [comment]
btw I am getting the same for `node:http` when I want to figure out what I can call on `event.node.res` object 

![image](https://user-images.githubusercontent.com/17269309/232808591-66a4b960-80a2-4ea1-a1c1-52c56455b0e1.png)

**Comment by danielroe** [comment]
You will probably need to install `@types/node`.

**Comment by kleinpetr** [comment]
That's right :+1: I just think it would be nice that it works out of the box :)
