### ISSUE TITLE
How to in subfunction exit process?

### ISSUE THREAD

**Issue by tenfei4** [unjs/nitro#1179]
### Describe the feature

**example /api/test.ts**
```
import fun from '@/server/fun'
export default defineEventHandler(async e => {
    fun.result(e,true);
    console.log('i hope not execute this.')
    //return e.context.json;
});
```

**/server/fun.ts**
```
const result=(e,end){
    if(!end){
        e.context.json={/*json content*/};
    }else{
        e.node.res.writeHead(200,{ 'Content-Type': 'application/json','Charset':'utf8'});
        e.node.res.end(JSON.stringify(e.context.json));
    }
}
export default {result}
```

Is there a way to achieve it? In practical projects, there is often a requirement to directly end a statement in a subfunction instead of using a return in the main function to end and output the content.

I hope to exit process not use return. However, after the content is output and the subfunction is called, the subsequent code will still be executed. How can I make the subsequent code not execute.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by tenfei4** [comment]
Because various business judgments need to be processed in the **fun.result** function, it is more desirable to directly pass the e.context in the API interface and directly output the result after directly judging the business logic in the fun.result. and stops subsequent code execution.Instead of using midware to judge, just want to judge access rights in midware.

**Comment by mao-shonen** [comment]
You can extend H3Error,
And use the errorHandler to customize error responses if needed.

**Comment by tenfei4** [comment]
How do I make it happen? Could you please give me an example code? @mao-shonen

**Comment by mao-shonen** [comment]
https://stackblitz.com/edit/github-mqes69
This is a simple example.
*Due to an export error, I didn't confirm that the code was running correctly.

**Comment by tenfei4** [comment]
your example is client side,i want is run at server side.how to run at server/api/ @mao-shonen

**Comment by manniL** [comment]
This is more of an architectural problem than a Nitro issue per sé. You can always make sure to return the value you want early and use the helpers to set headers and so on. Simple example:

```ts
export default defineEventHandler(async (event) => {
  const result = myFn(event)
  if(result) {
    return result
  }
});
function myFn (event: H3Event) {
  if(/*someCondition*/ true) {
    setResponseHeader(event, 'content', 'application/json')
    return { example: 'response' }
  }
}
```

**Do not use `event.node.XYZ` directly.**
