### ISSUE TITLE
[DOC] IIS Support

### ISSUE THREAD

**Issue by derHodrig** [unjs/nitro#1187]
### Describe the feature

Please add 
https://github.com/nuxt/framework/commit/ede534847831f46c45089a122d19b083d2ae26c7

to your documentation. We had our app running with IIS10 + nuxt2 and had no problem at all. With Nuxt3 we struggled, but that documentation of the archived repo helped us alot!

Could you please add this to the Nitro Docs? I would also add a Issue to the main nuxt 3 repo, since many users asked in that repo for IIS documentation.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by MosheL** [comment]
Can be used also with other  framework like `mod_rewrite` or nginx.

**Comment by pi0** [comment]
Let's track via https://github.com/unjs/nitro/issues/1427
