### ISSUE TITLE
Cloudflare Pages Deployment failing, __dirname is not defined

### ISSUE THREAD

**Issue by AwesomeDude091** [unjs/nitro#1194]
### Environment

nuxt.config.ts
```
export default defineNuxtConfig({
    modules: ['@nuxtjs/tailwindcss', '@nuxt/image-edge', 'nuxt-unhead',
        'nuxt-simple-sitemap', 'nuxt-schema-org', 'nuxt-simple-robots']
});
```
Running Nuxt Version 3.4.2
.mvnrc
`16`

### Reproduction

Upload this project to Cloudflare Pages using the Zero Config option provided by linking the GitHub Repository with Cloudflare Pages. Cloudflare successfully compiles and finds the _worker.js . It uploads the assets and fails on publishing a function

### Describe the bug

Cloudflare Pages fails to deploy the application to the cloudflare network due to a reference error. It cannot find __dirname.

### Additional context

The same project compiles successfully locally with the `node_server` preset and the `cloudflare_pages` preset.
I DO NOT add any Cloudflare Function (at least that I am aware of). I purely compile the nuxt web application and want it to execute :)

### Logs

```sh
`Error: Failed to publish your Function. Got error: Uncaught ReferenceError: __dirname is not defined
  at functionsWorker-0.4740030691865005.js:6396:18`
```

**Comment by AwesomeDude091** [comment]
After further investiagtion it seems that the issues resolves itself, once the `@nuxt/image-edge` module is removed from the application

**Comment by Hebilicious** [comment]
Closing in favour of related issue in nuxt/image https://github.com/nuxt/image/issues/866
