### ISSUE TITLE
An option to read file-based secrets

### ISSUE THREAD

**Issue by mao-shonen** [unjs/nitro#1195]
### Describe the feature

I wish there was an option to read file-based secrets.
This can make it easier for developers to use `google cloud secret manager` or `AWS secrets manager` or similar functionality from other providers.

it maybe like.
```ts
// nitro.config.ts
export default defineNitroConfig({
  secretsVaultDir: '/secrets',
  runtimeConfig: {
    secretKey: 'a secret'
  }
})
```

in `/secrets/secret_key`
```
a covered secret
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by mao-shonen** [comment]
Yes, I know the storage can read it.
It seems like my title is inappropriate.
I intuitively thought this was a functionality similar to `.env`,
so I suggest having a more elegant way to use.

**Comment by pi0** [comment]
Can you please explain more? How do you see it to make it more elegant with new option?

**Comment by mao-shonen** [comment]
When I was preparing the explanation,
I remembered the meaning of this `UnJS` organization.
This feature is really not part of nitro, maybe I'll create a nuxt module instead to provide this feature.
