### ISSUE TITLE
[proxy] socket hang up

### ISSUE THREAD

**Issue by Luferov** [unjs/nitro#120]
### Environment

NodeJS: 17.19.0
@nuxt/nitro@npm:@nuxt/nitro-edge@3.0.0-27468803.23e7afb
@nuxt/nitro@3.0.0-27468803.23e7afb

### Reproduction

https://github.com/devind-team/eleden

But its not easy, because it need server.

### Describe the bug

This error is related to sockets, when on the client I establish a connection with the server via apollo-subscription.

In console I get:
![image](https://user-images.githubusercontent.com/26242554/163733540-e17cb38d-1128-417e-8b94-66c8ddc69dc9.png)
And the page hangs in an endless reload.

And client does not set cookie. Before, on nuxt 2.5 it worked good.
![image](https://user-images.githubusercontent.com/26242554/163733690-0c9d0e77-e079-479d-850f-5eda22ccef3e.png)

### Additional context

I use apollo subscription.

**Comment by Luferov** [comment]
It may linked with ssl in new open ssl provider, because I need set flag NODE_OPTIONS=--openssl-legacy-provider when started dev.

**Comment by pi0** [comment]
Hey @Luferov. It seems you are using an older version of Nuxt 3. `nuxt/nitro-edge` doesn't exist anymore! Would you please try `npx nuxi upgrade --force` to see if it still happens?

**Comment by Luferov** [comment]
Right now I'm using nuxt-bridge, maybe that's the problem, but I can't upgrade because at that very moment everything stops working. We are now putting in a lot of effort to move fully to nuxt3. Maybe when we upgrade to nuxt 3 everything will be fine.

**Comment by pi0** [comment]
Feel free to open another issue in Nuxt 3 or Bridge repo if you are still experiencing it but I guess this issue might be solved in latest nitro codebase. Also wish best for Nuxt 3 upgrade plan 🚀
