### ISSUE TITLE
Support route groups

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1205]
Context: https://github.com/nuxt/nuxt/issues/20641

I am thinking also how we could integrate groups somehow with route rules.

**Comment by oumarbarry** [comment]
any plan on this @pi0 ?

**Comment by oumarbarry** [comment]
@HigherOrderLogic, it would be amazing to have route groups for Nitro too, [like Nuxt](https://github.com/nuxt/nuxt/pull/28276) !

**Comment by pi0** [comment]
PR welcome, i think basic support would be so simple for nitro file scanner.
