### ISSUE TITLE
`cachedEventHandler` clears request body

### ISSUE THREAD

**Issue by johankrijt** [unjs/nitro#1238]
### Environment

Nitro: 2.4.0
Node: 18.16.0

### Reproduction

When caching an API handler using cachedEventHandler (https://nitro.unjs.io/guide/cache#usage) the body of the events' (POST) request is empty within the handler:

```
export default cachedEventHandler(async (event) => {
  let body = await readBody(event)
  console.log(body) // this one is always empty when doing a (POST) request
}, {
  maxAge: 60
});
```

### Describe the bug

Within the cachedEventHandler (https://github.com/unjs/nitro/blob/1b4bb37fed3d9bb3014cc85a4681a9daebf340e9/src/runtime/cache.ts#LL207C7-L207C80) the request is being proxied to clear the headers:

`const reqProxy = cloneWithProxy(incomingEvent.node.req, { headers: {} });`

This unfortunately has a side effect of also removing the body of the request which is later on attached to the event: https://github.com/unjs/nitro/blob/1b4bb37fed3d9bb3014cc85a4681a9daebf340e9/src/runtime/cache.ts#LL267C7-L267C7 and consequently prevents the handler from reading the body.

Calling the readBody function before cloning the request resolves this issue, because the buffered result is attached to the request which afterwards gets copied over to the proxy, but personally it would make more sense to either attach the buffer to the reqProxy, or probably even better, not cloning the request at all (and only overwriting headers where necessary), preventing other unwanted side effects as this one.

**Comment by pi0** [comment]
Hi. It is intentional behavior. Cached events do not have access to incoming request headers and body. This wake we make sure they are rendered isolated and request from one user is not cached for another user.

You can instead cache heavy logic using [cachedFunction](https://nitro.unjs.io/guide/cache#function) and use normal event handler which has access to body.

**Comment by johankrijt** [comment]
Hi pi0, 

I understand what you are saying, and where I understand it makes sense for normal post requests, this also removes any way of adding additional information to the request which would actually be useful for handling the request itself. For us for example we use dynamic hostnames, which we also need to access in the request itself. We first tried adding those in the header of the GET request (which got cleared) and then as an alternative moved the variable to a post request, similar to how for example https://nuxt.com/modules/api-party is handling extra parameters. Wouldn't it be an option to instead of removing all the headers, actually keep all the 'x-...' headers in the request?

**Comment by pi0** [comment]
Supporting `varies` options for headers like `host` is planned 👍🏼

**Comment by johankrijt** [comment]
Nice job! Thanks so much for your quick response as well! Really appreciated 👏
