### ISSUE TITLE
Add AWS via Flightcontrol Docs

### ISSUE THREAD

**Issue by ModupeD** [unjs/nitro#1249]
### Describe the feature

This change adds a new deployment provider to Nitro: deploying to AWS via Flightcontrol. Flightcontrol helps you deploy your Nitro projects (Both static & SSR) to your own AWS account with little to no configuration.

### Additional information

- [X] Would you be willing to help implement this feature?
Here is the pull request:
https://github.com/unjs/nitro/pull/1250

**Comment by Hebilicious** [comment]
Resolved with https://github.com/unjs/nitro/pull/970
