### ISSUE TITLE
RuntimeConfig property is unknown

### ISSUE THREAD

**Issue by maou-shonen** [unjs/nitro#1253]
### Describe the feature

refer unjs/h3#386
Perhaps the same behavior can be provided for `RuntimeConfig`?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
@maou-shonen Could you provide more information / a reproduction please ?

**Comment by McPizza0** [comment]
@Hebilicious 
I can replicate this

My runtimeConfig is as follows:
```
runtimeConfig: {
    key1: 'value1',
    key2: 'value2',
    key3: 'value3',
 }
```

When using `useRuntimeConfig()` none of the keys are present (only `app` & `nitro` are).
When using `useRuntimeConfig().key1` type is returned as any/unknown.
`useRuntimeConfig().randomWrongKeyName` does not throw any type errors.

**Comment by Hebilicious** [comment]
> @Hebilicious I can replicate this
> 
> My runtimeConfig is as follows:
> 
> ```
> runtimeConfig: {
>     key1: 'value1',
>     key2: 'value2',
>     key3: 'value3',
>  }
> ```
> 
> When using `useRuntimeConfig()` none of the keys are present (only `app` & `nitro` are). When using `useRuntimeConfig().key1` type is returned as any/unknown. `useRuntimeConfig().randomWrongKeyName` does not throw any type errors.

Could you please provide a reproduction ? 🙏🏽

**Comment by McPizza0** [comment]
https://codesandbox.io/p/sandbox/nitro-5jssbm?file=/routes/api/hello.ts:4,24

check type of key1
check keys under config

**Comment by pi0** [comment]
I think the idea is to automatically generate runtime config types from `nitro.config` as reference similar to Nuxt.

**Comment by McPizza0** [comment]
100% as @pi0 said

Coming from nuxt, I thought runtime config would behave the same.

**Comment by Hebilicious** [comment]
Understood, my bad I didn't realise this only worked in Nuxt.

**Comment by McPizza0** [comment]
Me too, I thought it would have been in Nitro
Now realize its a feature request instead of bug
