### ISSUE TITLE
The development environment is different from packaging, and yup is not packaged 。 .output\server\node_modules

### ISSUE THREAD

**Issue by 15844229646** [unjs/nitro#1254]
### Environment

Operating System: Windows_NT
Node Version: v18.12.1
Nuxt Version: 0.0.0
Nitro Version: -
Package Manager: unknown
Builder: webpack
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

https://gitee.com/WangJingXuan/new-team

### Describe the bug

[nuxt] [request error] [unhandled] [500] Cannot find package 'yup' imported from E:\blogtest\server\chunks\index.get.mjs
at new NodeError (node:internal/errors:393:5)
at packageResolve (node:internal/modules/esm/resolve:860:9)
at moduleResolve (node:internal/modules/esm/resolve:909:20)
at defaultResolve (node:internal/modules/esm/resolve:1124:11)
at nextResolve (node:internal/modules/esm/loader:163:28)
at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
at ModuleWrap. (node:internal/modules/esm/module_job:76:40)
at link (node:internal/modules/esm/module_job:75:36)

I am running fine in the development environment. However, when I package the application and run it, I encounter the following error:
```
import {Schema, model} from 'mongoose';
import yup from 'yup'
import { getNextId } from '../tools/mongooseUtils';

const {modelName,fieldName} = {
  modelName:'Banner',
  fieldName:'bannerId'
} 

const bannerSchema = new Schema({
[fieldName]: { type: Number, unique: true },
title: { type: String },
subtitle: { type: String, required: true },
image: { type: String, required: true },
enabled: { type: Number, required: true },
sort: { type: Number },
}, { timestamps: true });

bannerSchema.pre('save', async function (next) {
if (!this[fieldName]) {
  this[fieldName] = await getNextId(modelName, fieldName);
}
next();
});
```

export const Banner = model<any>(modelName, bannerSchema)

export const BannerYup = yup.object().shape({
  title: yup.string().required('Title is required'),
  subtitle: yup.string().required('Subtitle is required'),
  image: yup.string().required('Image is required'),
  enabled: yup.number().required('enabled is required'),
  sort: yup.number().required('sort is required'),
});

The endpoint directory is server/api/banner and the file is imported from server/models/Banner.

To reproduce the issue:

After packaging, run node .output/server/index.mjs (The issue occurs because the node_modules/yup is present locally in the project)
Move the packaged .output folder to a different directory
Run node .output/server/index.mjs from the new location, which triggers the error.

Question:
Why is the yup module not included in the node_modules directory when building?

Please ensure that the translation accurately conveys the information provided.

**Comment by 15844229646** [comment]
当我在 nuxt 路由中的api路由为：
/api/banner.ts 
此时打包 【yup】将被加入到 server\node_modules

当我在 nuxt 路由中的api路由为：
/api/banner/index.get.ts 
/api/banner/index.post.ts 
此时打包 【yup】将不会被加入到 server\node_modules

**Comment by 15844229646** [comment]
已解决  ：


多次 yarn install 不可行

升级 yarn
npm install yarn@latest -g

再次 
yarn install

打包后的【yup】正常

**Comment by Hebilicious** [comment]
@15844229646 Could you please provide a stackblitz/codesanbox/github reproduction ? I can't access your repository.

**Comment by manniL** [comment]
Hey! No reproduction was provided for a month. I'll close this issue here.
If it issue persists, feel free to raise a new issue **with a reproduction** and link this issue ☺️
