### ISSUE TITLE
Infer middleware event context in eventHandlers 

### ISSUE THREAD

**Issue by michealroberts** [unjs/nitro#1258]
### Describe the feature

I think it would make sense if the event context can be overridden or inferred somehow in route eventHandlers ... let's say I have the following middleware:

`middleware/db.ts`

```ts
export default defineEventHandler(async event => {
  const { db } = useRuntimeConfig()
  event.context.db = useDb(db)
})
```

This should then be correctly typed in route handlers (not as any)

```ts
export default defineEventHandler(async event => {
  const { db } = event.context // <-- db here is current typed as "any"
}
```

This would be a massive improvement for DX ...

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by maou-shonen** [comment]
You can extends types like this

```ts
declare module "h3" {
  interface H3EventContext {
    db: YourDBType
  }
}
```

It would be nice to have this in the docs

**Comment by michealroberts** [comment]
@maou-shonen Yeh that's fair, but it would be nice to have this inferred, or at worse, in the documentation like you say.
