### ISSUE TITLE
`vercel-edge` preset should not target node runtime in `jose` npm package

### ISSUE THREAD

**Issue by Arecsu** [unjs/nitro#1277]
### Environment

Nuxt 3.5.2
Nitro 2.4.1
Node v16.14.2 & v18.16.0

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zmpnuh?file=server%2Futils%2Futils.js

It should run `yarn install && NITRO_PRESET=vercel-edge yarn build` automatically. Otherwise, use those commands.

### Describe the bug

I'm using the library [jose](https://github.com/panva/jose) in the server functions of my Nuxt project because it has support for edge runtimes, described [here](https://github.com/panva/jose#supported-runtimes). It uses Web Crypto API instead of Node ones.

The package has both runtimes bundled: a `node` runtime which uses node functions, and a `browser` runtime which should work with everything else without depending on node.

When I build the project with the default Nitro preset, which targets Node, everything works fine. With `NITRO_PRESET=vercel-edge`, the following error appears:

```
ℹ Building Nitro Server (preset: vercel-edge)                                                                                                                 nitro 3:15:01 PM

[nitro 3:15:06 PM]  ERROR  RollupError: "createHash" is not exported by "node_modules/unenv/runtime/node/crypto/index.mjs", imported by "node_modules/jose/dist/node/esm/runtime/digest.js".


1: import { createHash } from 'crypto';
            ^
2: const digest = (algorithm, data) => createHash(algorithm).update(data).digest();
3: export default digest;


 ERROR  "createHash" is not exported by "node_modules/unenv/runtime/node/crypto/index.mjs", imported by "node_modules/jose/dist/node/esm/runtime/digest.js".        3:15:06 PM
 ```

It seems that it still targets the `node` runtime of the package and tries to use `unenv` to polyfill the `createHash` function, which doesn't have. In `next.js`, it seems to work out of the box when deploying to the Edge.

I don't know if this is an issue from `Nitro`, `unenv` or `jose`, or if I should configure something to target the proper edge runtimes from `jose` in the build process.

The following is part of the `package.json` from `jose`:

```json
"exports": {
  ".": {
    "types": "./dist/types/index.d.ts",
    "bun": "./dist/browser/index.js",
    "deno": "./dist/browser/index.js",
    "browser": "./dist/browser/index.js",
    "worker": "./dist/browser/index.js",
    "import": "./dist/node/esm/index.js",
    "require": "./dist/node/cjs/index.js"
  },
  "./package.json": "./package.json"
},
"main": "./dist/node/cjs/index.js",
"browser": "./dist/browser/index.js",
"types": "./dist/types/index.d.ts",
"files": [
  "dist/**/package.json",
  "dist/**/*.js",
  "dist/types/**/*.d.ts",
  "!dist/**/*.bundle.js",
  "!dist/**/*.umd.js",
  "!dist/**/*.min.js",
  "!dist/node/webcrypto/**/*",
  "!dist/types/runtime/*",
  "!dist/types/lib/*",
  "!dist/deno/**/*"
],
"deno": "./dist/browser/index.js"
```

Thank you so much!

**Comment by 5knnbdwm** [comment]
Hey @Arecsu did you find a solution? As i'm having the same problems

**Comment by Arecsu** [comment]
@5knnbdwm I have a possible workaround. Haven't tested this on Vercel, but at least it gets rid of the build errors using `vercel-edge` preset.

Seach for the `package.json` of `jose` that your package manager is using (it may differ if you're using `yarn`, or pnpm`) and locate the `import` value from `exports`:

```
"import": "./dist/node/esm/index.js",
"require": "./dist/node/cjs/index.js"
```

Change it to:

```
"import": "./dist/browser/index.js",
"require": "./dist/node/cjs/index.js"
```

If you can test it on Vercel, please report back!

**Comment by 5knnbdwm** [comment]
@Arecsu well if i try to build it with `vercel-edge` locally it fails (as it did before) but I get a different error.

```
ℹ Building Nitro Server (preset: vercel-edge)                                                                                                                                                                                      nitro 6:41:35 PM

 ERROR  RollupError: "createHmac" is not exported by "node_modules/unenv/runtime/node/crypto/index.mjs", imported by "node_modules/@panva/hkdf/dist/node/esm/runtime/fallback.js".                                                 nitro 6:41:41 PM


1: import { createHmac } from 'crypto';
            ^
2: export default (digest, ikm, salt, info, keylen) => {
3:     const hashlen = parseInt(digest.substr(3), 10) >> 3 || 20;


 ERROR  "createHmac" is not exported by "node_modules/unenv/runtime/node/crypto/index.mjs", imported by "node_modules/@panva/hkdf/dist/node/esm/runtime/fallback.js".                                                                    6:41:41 PM

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2124:30)
  at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:13463:16)
  at Module.traceVariable (node_modules/rollup/dist/es/shared/node-entry.js:13884:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:12429:39)
  at ReturnValueScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:6965:38)
  at ChildScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:6965:38)
  at Identifier.bind (node_modules/rollup/dist/es/shared/node-entry.js:8127:40)
  at CallExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:5738:23)
  at CallExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:9680:15)
  at MemberExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:5738:23)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Arecsu** [comment]
It seems you've solved the error from `jose`, but now it's the package `@panva` that has the problem. Look into it as we did we `jose` and see if you can apply the same workaround.

**Comment by 5knnbdwm** [comment]
@Arecsu okay so @panva/hkdf doesnt contain a dist/browser folder but dist/web. I used that instead.

and well it works.

**Comment by Arecsu** [comment]
I can think of two ways: 

- Install the vercel CLI and use the command `vercel build` and then `vercel deploy --prebuilt`. This will build locally and then deploy it to vercel as a `preview` build. I think you can add `--prod` to deploy it directly to production if everything goes right from `preview`.
- Fork the modified packages to your Github and fix the packages.json. Replace the packages of your project with those. See: https://stackoverflow.com/questions/43411864/how-to-install-package-from-github-repo-in-yarn

Maybe you can just go with the first one and then if everything goes right use the second method. I still think that there's something to be fixed within `Nitro` or `unenv` to detect and use the browser/web runtimes.

**Comment by 5knnbdwm** [comment]
Okay yeah thought of the second way, didnt know the first existed

**Comment by v-moravec** [comment]
Hi, you can solve this by adding this to `nuxt.config.ts`:

```
alias: {
  "jose": resolve(__dirname, "./node_modules/jose/dist/browser/index.js"),
  "@panva/hkdf": resolve(__dirname, "./node_modules/@panva/hkdf/dist/web/index.js")
}
```

**Comment by Arecsu** [comment]
Thank you so much @v-moravec, that workaround works!

**Comment by MurmeltierS** [comment]
A similar issue occurs when using the new @vercel/postgres library. 

```
alias: {
    jose: process.env.NODE_ENV === 'development' ? undefined : path.resolve(__dirname, './node_modules/jose/dist/browser/index.js'),
    '@vercel/postgres': process.env.NODE_ENV === 'development' ? undefined : path.resolve(__dirname, './node_modules/@vercel/postgres/dist/index.js')
  }
```

**Comment by Hebilicious** [comment]
> Hi, you can solve this by adding this to `nuxt.config.ts`:
> 
> ```
> import {createResolver} from '@nuxt/kit'
> 
> const { resolve } = createResolver(import.meta.url)
> 
> export default defineNuxtConfig({
>   alias: {
>     "jose": resolve(__dirname, "./node_modules/jose/dist/browser/index.js"),
>     "@panva/hkdf": resolve(__dirname, "./node_modules/@panva/hkdf/dist/web/index.js")
>   }
> )}
> ```

This looks like the exact same issue I tried to fix in my [module](https://github.com/Hebilicious/authjs-nuxt/blob/7fe8e5fb2911ea74e337f6f74d4d96a282d1f292/packages/authjs-nuxt/src/module.ts#L35)

Fwiw this doesn't happen just with vercel-edge, but other non node environments too.

I can get really ugly too, see https://github.com/nuxt/nuxt/issues/21619

**Comment by septatrix** [comment]
I am not sure if this is the right place or if I should open a new issue for this but using the crypto global from newer node versions does not work in the generated build version where "crypto is not defined" is thrown. Instead, I have to manually import the used methods from `node:crypto` which makes prevents it from being runtime agnostic :/

**Comment by Hebilicious** [comment]
> I am not sure if this is the right place or if I should open a new issue for this but using the crypto global from newer node versions does not work in the generated build version where "crypto is not defined" is thrown. Instead, I have to manually import the used methods from `node:crypto` which makes prevents it from being runtime agnostic :/

I'm using a workaround like this :

```ts
if (!globalThis.crypto) {
  // eslint-disable-next-line no-console
  console.log("Polyfilling crypto...")
  import("node:crypto").then((crypto) => {
    Object.defineProperty(globalThis, "crypto", {
      value: crypto.webcrypto || crypto,
      writable: false,
      configurable: true
    })
  })
}
```

In the meantime, we can track this here https://github.com/unjs/nitro/issues/1371

**Comment by JamieCurnow** [comment]
@Hebilicious Where do you add the code for that workaround above to add crypto to the globalThis?

**Comment by Hebilicious** [comment]
Somewhere in the server side code of a Nuxt application. You might need to tweak this an use a real import instead of static import. Lucia has something similar in their docs https://lucia-auth.com/start-here/getting-started?nuxt#polyfill-crypto-global for example
