### ISSUE TITLE
404 error on the root (/) route when using (ISR) on Vercel.

### ISSUE THREAD

**Issue by MikeBellika** [unjs/nitro#1287]
### Environment

Vercel

### Reproduction

This route returns a 404: https://isr-bug-mike-altingetdk.vercel.app/
This route returns the content: https://isr-bug-mike-altingetdk.vercel.app/hello

They are both rendered with `{ isr: 60 }`.

Repo at https://github.com/MikeBellika/isr-bug

### Describe the bug

When the index route is rendered using ISR, it always returns a 404. Doesn't seem to happen locally, only when deploying to vercel

### Additional context

Got this issue while trying to upgrade to nuxt 3.5 and it's preventing us from upgrading, since we can't cache the front page.

**Comment by Hebilicious** [comment]
fixed with https://github.com/unjs/nitro/pull/1290
