### ISSUE TITLE
Missing middleware docs

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/nitro#1296]
### Describe the feature

I think that the concept of middleware is missing in the documentation.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Barbapapazes** [comment]
I'm currently learning Nitro and I'll be happy to help writing missing docs (or at least report missing parts)!

**Comment by manniL** [comment]
Covered by now @ https://nitro.unjs.io/guide/routing#middleware
