### ISSUE TITLE
Enable Node by default with Cloudflare Pages preset

### ISSUE THREAD

**Issue by Smef** [unjs/nitro#1314]
### Describe the feature

When deploying on Cloudflare Pages the `cloudflare-pages` preset has `node: false` as a configuration option, which is incorrect. CFP v1 uses Node 12 by default, with Node 18 as the default in the new v2 beta. You can also specify any specific Node version you want for your deployment, which is what you'd need to do to deploy on CFP. (https://developers.cloudflare.com/pages/platform/language-support-and-tools/)

I think that the default for a CFP preset should be `node: true`.

PR: #1315 

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
We do use Node.js for building nitro apps. More context https://github.com/unjs/nitro/pull/1315#issuecomment-1596087858
