### ISSUE TITLE
Sending stream responses (experimental)

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1327]
Moving from (https://github.com/unjs/nitro/issues/19)

Coming with [h3@1.7.0](https://github.com/unjs/h3/releases/tag/v1.7.0) and new [`event.handled` flag](https://github.com/unjs/h3/pull/410) it is possible to take over h3 response mechanism and send streams. For Workers, we can check `res._body` property existence. Direct fetch in unenv ([src](https://github.com/unjs/unenv/blob/main/src/runtime/fetch/index.ts#L17)) passes the body as is. 

This way we can implement `sendStream` with the minimum possible changes. Once tested enough and working for common presets, I plan to add this as a built-in (nitro/h3) utility.

Example usage: https://github.com/unjs/nitro-deploys/blob/main/routes/stream.ts 

Working deployments:

- Cloudflare workers: https://nitro-deployment.pi0.workers.dev/stream
- Netlify functions: https://nitro-deployment-edge.netlify.app/stream
- Vercel edge: https://nitro-app-edge.vercel.app/stream

https://github.com/unjs/nitro/assets/5158436/274076e6-4bd0-4bd4-b64f-3b903ab2bde7

**Comment by Hebilicious** [comment]
This is approach is working great for me, see [here](https://github.com/Hebilicious/vercel-sdk-ai/blob/cloudflare-official/examples/nuxt-openai/server/api/chat.ts).

@pi0 Could we replace the sendStream in h3 with this new updated version instead of adding it to nitro ?

**Comment by jlucaso1** [comment]
I'm experiencing problems detecting when the request is closed to clean up processing.
```ts
  event.node.req.once("close", () => {
    cleanupFunction() // <-- this is never called
  })
```
@pi0 can you update the example of streams to handle this? I don't know if this is a bug.

**Comment by dosstx** [comment]
So how does one set this up for Nuxt ?

**Comment by Hebilicious** [comment]
> I'm experiencing problems detecting when the request is closed to clean up processing.
> 
> ```ts
>   event.node.req.once("close", () => {
>     cleanupFunction() // <-- this is never called
>   })
> ```
> 
> @pi0 can you update the example of streams to handle this? I don't know if this is a bug.

For node.js, you could pass a cleanup function to your sendStream handler, and run it as part of the close() callback of WritableStream. 

```ts
function sendStream(event: H3Event, stream: ReadableStream, cleanup: any) {
  // Mark to prevent h3 handling response
  event._handled = true;

  // Workers (unenv)
  (event.node.res as unknown as { _data: BodyInit })._data = stream;

  // Node.js
  if (event.node.res.socket) {
    stream.pipeTo(
      new WritableStream({
        write(chunk) {
          event.node.res.write(chunk);
        },
        close() {
         cleanup()
          event.node.res.end();
        },
      })
    );
  }
}
```

**Comment by jlucaso1** [comment]
@Hebilicious 
I attempted this approach; however, when I forcefully close the request, the `cleanup()` function does not get invoked as expected.

**Comment by Hebilicious** [comment]
@jlucaso1 Try [abort()](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream/abort)

**Comment by pi0** [comment]
Update: Web Stream Support directly landing in H3 (https://github.com/unjs/h3/pull/432). 

We still might need to tweak some presets for full compatibility and experiment worker support.

**Comment by dosstx** [comment]
Can we use this yet in Nuxt or not yet? Confused.

**Comment by pi0** [comment]
@dosstx h3 changes are still not released and being tested. But very soon you would be able to try it via nuxt or nitro edge channels.

**Comment by dosstx** [comment]
@pi0 OK thank you very much. Sorry to waste your time looking at these kinds of questions. Looking forward to the release!

**Comment by Hebilicious** [comment]
> @pi0 OK thank you very much. Sorry to waste your time looking at these kinds of questions. Looking forward to the release!

You can already use it with a few workarounds: https://github.com/vercel-labs/ai/pull/295
As pi said, soon you will be able to use it without the workarounds.

**Comment by Giancarlo-Ma** [comment]
how can i intercept the streaming content to save it to db on cf worker

**Comment by pi0** [comment]
streaming support should be more stable now. please report any issues if you encounter so we can improve 🙏🏼

**Comment by Ena-Heleneto** [comment]
I apologize for the off-topic question, but I genuinely love the font used on the website in your video. If it's not a commercial font, would you mind sharing its name with me? Thank you so much! @pi0
