### ISSUE TITLE
useFetch not triggered on index.vue when <NuxtPage /> is used

### ISSUE THREAD

**Issue by Subfortytwo** [unjs/nitro#1353]
### Environment

Nuxt 3.6.1 with Nitro 2.5.1 

### Reproduction

**app.vue:**

```
<template>
      <NuxtPage />
</template>
```

**layouts/default.vue:**

```
<template>
<slot />
</template>
```

**pages/index.vue and pages/test.vue:** 
```
<script setup lang="ts">
const {data: dog} = await useFetch('https://dog.ceo/api/breeds/image/random')
</script>
<template>
  Dog: {{ dog.message }}
</template>
```

Now you do
`yarn dev`

Press F5 on 127.0.0.1:3000/, the dog URL gets updated.

`yarn build && node .output/server/index.mjs `

Press F5 on 127.0.0.1:3000/, the dog URL **is not** updated.
Go on  127.0.0.1:3000/test, the dog URL is updated.

### Describe the bug

NuxtPage / is killing the useFetch on the server side. UseFetch is not triggered. See the reproduction for the minimal reproduction.

**Comment by danielroe** [comment]
`pages/index.vue` renders `/`, not `pages/default.vue` (which would render a route path of `/default`)

**Comment by Subfortytwo** [comment]
of course, little mistake, I corrected the description.

**Comment by Subfortytwo** [comment]
Different machine, cannot reproduce the error. I believe it comes from a 'plugin'. Let's close this bug for the moment. Thanks for your answer.
