### ISSUE TITLE
`nitro` npm package 🥳

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1362]
**Update:** `nitro` and `nitropack` will be mirrored. More info: https://github.com/unjs/nitro/pull/2497

---

Currently, we are using [nitropack](https://www.npmjs.com/package/nitropack) and [nitropack-edge](https://www.npmjs.com/package/nitropack-edge) npm packages for nitro releases. It was because `nitro` package was used. And package name is mismatched with the project name a little bit. We also publish docs in [nitropack.org](https://www.nitropack.org/) and have access to `@nitropack/` npm scope planned to be used for presets (https://github.com/unjs/nitro/issues/845)).

Thanks to @danielroe for following up about `nitro` npm package and @jgermade for donating it now we have a chance to use it  🥳 (credits to be added to readme!)

Quickly talking with @danielroe, There are two ideas for using this new package:

1. Release nitro v3 as `nitro@3.0.0` and have a compatibility `nitropack@3.0.0` with stubs and bundling CLI in same package of nitro with build deps
2. Use the new `nitro` package name for zero-dependency `nitro` CLI and keep using nitropack or better scoped npm packages for actual core/preset packages

And there are cons and pros with each.

- Using `nitro` as the new Library name, makes naming consistent and also easier for to people understand what is in `devDependencies` field and `node_modules`.
- Using `nitro` as the new standalone CLI, makes sure we can always advise `npx nitro` command without version conflicts similar to (upcoming) `npx nuxi`. This CLI will be for initializing a project but also upcoming user-defined subcommands (👀)

Opening this discussion to collect more feedback and ideas until nitro v3 release.

**Comment by Hebilicious** [comment]
Personally, I feel like renaming to nitro and [deprecating](https://docs.npmjs.com/cli/v9/commands/npm-deprecate) nitropack for v3 is perfect and makes the most sense, as we always refer to Nitro as Nitro (in the docs etc) and nitropack was chosen just because nitro was un-available. 

For the CLI, I like how [Astro](https://github.com/withastro/astro/blob/main/packages/astro/package.json) is doing it, where they use `astro` for both the cli and the dependency, and `create-astro` for the scaffolding tool.

This would enable : 

- `npm i nitro` install nitro as a dependency in package.json
- `npx nitro` use the nitro cli for nitro commands (ie: nitro dev`, `nitro build`...)
- `npm create nitro@latest` leverage `create-nitro` to scaffold a project

However, since this is a brand new thing, we could also use a brand new name such as `nitro-cli` or `nitri` ?

**Comment by Atinux** [comment]
`nitro-cli` makes more sense for your last question.

This is awesome news for `nitro` package!

**Comment by pi0** [comment]
I respect all opinions and feedback. 

Still leaner towards using `nitro` for dedicated cli, considering we need a zero dependency and short nuxi-like CLI for nitro and also a npm namespace for upcoming presets refactor which cannot be `@nitro` (it is actively used). CLI accessibility and usability is more important than programmatic usage and manual boilerplates.

**Comment by nksaraf** [comment]
I think having one package `nitro` with both the CLI and the core programmtic package is probably the easiest for people to use and understand. Its quite atypical to have a separate package just for the cli in other places in the ecosystem.

**Comment by pi0** [comment]
> is probably the easiest for people to use and understand

I also expect people to directly interact with `nitro` to initialize and run tasks for their projects 👍🏼 

Weather bundling both Nitro core (with ALL dependencies which cost [![install size](https://packagephobia.com/badge?p=nitropack)](https://packagephobia.com/result?p=nitropack) and hundreds of `node_module` files today) from single npm package is a technicality that reduces the DX of CLI usage every time we use it. And at least for modern Nuxt 3, we expose CLI as a standalone `nuxi` command ([nuxt/cli](https://github.com/nuxt/cli)) and we used a second name for CLI because nuxt was made years ago, following what was typical by the day. Which can be better thought for Nitro once we have this one-time chance.

I think regardless, I am still clearly not messaging that this is a final decision but that need to gather more ideas and progress to see how Nitro structure evolves (in regards of increasing modularity and splitting presets to `@nitropack/` npm namespace -- we can't have `@nitro/`!) and also future of nuxi CLI which is based on same foundation i have in my mind for Nitro CLI.

**Comment by pi0** [comment]
`nitro` and `nitropack` will be mirrored and we will use `nitro` as main package starting v3. More info: https://github.com/unjs/nitro/pull/2497
