### ISSUE TITLE
IIS Preset

### ISSUE THREAD

**Issue by Hebilicious** [unjs/nitro#1365]
Thanks for the PR. I think we can also introduce a preset for IIS generating `web.config` file.

_Originally posted by @pi0 in https://github.com/unjs/nitro/issues/1035#issuecomment-1458225094_

**Comment by Hebilicious** [comment]
@pi0 I created this one for adding a IIS preset so we can merge the docs in the meantime. What do you think ?

**Comment by pi0** [comment]
As a best practice it would be best to only _officially_ list deployment presets in nitro when they have a tested preset. This way we can make sure to support it in long term and avoid boilerplate.  (this comes from long history in pre nuxt 3 with outdated deploy docs.)

Adding a simple preset for IIS should be straight forward btw to generate required configs :)

**Comment by Hebilicious** [comment]
Duplicated #1035
