### ISSUE TITLE
Allow customizing firebase regions

### ISSUE THREAD

**Issue by Hebilicious** [unjs/nitro#1369]
```typescript
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  /* Other config options */
  nitro: {
    preset: "firebase",
    replace: {
      "functions.https.onRequest": "functions.region('europe-west2').https.onRequest",
    },
  },
});
```

This is little hacky, but better than nothing. 
After we had support for regions with firebase v2 we can add support for v1.

_Originally posted by @luc122c in https://github.com/unjs/nitro/issues/90#issuecomment-1430548908_

**Comment by pi0** [comment]
Let's track via #90
