### ISSUE TITLE
Document how to make custom nitro presets

### ISSUE THREAD

**Issue by Hebilicious** [unjs/nitro#1373]
### Describe the feature

Documenting how to create and use presets will un-block users who are un-aware that they can tweak their presets or create new ones locally, similarly to Nuxt Modules. 

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Let's put a pending on this until making https://github.com/unjs/nitro/issues/845 done. We could have more examples and structure how preset packages look like.

FYI i previously made a simple starter to try new presets: https://github.com/unjs?q=preset&type=all&language=&sort=

**Comment by Hebilicious** [comment]
> Let's put a pending on this until making #845 done. We could have more examples and structure how preset packages look like.
> 
> FYI i previously made a simple starter to try new presets you can check [unjs/nitro-preset-starter](https://github.com/unjs/nitro-preset-starter)

I understand your vision with #845 

It is currently possible to do something like this : 

https://github.com/jdevdevdev/nuxt-sst/blob/lambda-edge/nuxt-app/server/nitro/preset/entry.ts

While the documentation could make someone think that this is not possible.
Without going into too much details, we could mention that it's possible https://nitro.unjs.io/deploy/custom-presets, or maybe link to an example ?

**Comment by pi0** [comment]
Sure adding some more refs to that page would be nice idea meanwhile 👍🏼

**Comment by Hebilicious** [comment]
Just found out an example in the while of a "remote" preset https://github.com/auguwu/fastify-nitro
