### ISSUE TITLE
make `event.context.params` usable within server middleware

### ISSUE THREAD

**Issue by Xulgoos** [unjs/nitro#1374]
### Describe the feature

Currently any usage of `event.context.params`, `getRouterParams` or any equivalent within server middlewares (`~/server/middleware`) will return undefined.

We should be able to access `event.context.params` within server middlewares as it can open a lot of possible usage.
For example, directly loading users' permissions within middlewares and deciding whether they can use the API endpoint.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. This is not technically possible to access matched params in middleware because they run before the router handler.

You can use custom pattern matcher using `event.path` in middleware to apply logic to a group of matched routes.
