### ISSUE TITLE
nitro-routes not generated properly for filename separated by dots like handler.get.ts

### ISSUE THREAD

**Issue by trc-mathieu** [unjs/nitro#1378]
### Environment

nitropack 2.5.2
node 18.15.0

### Reproduction

No reproduction, bug is easy to reproduce.

### Describe the bug

I found the issue using a nuxt module after exposing an event handler from a file named `assets.get.ts`
```javascript
 addServerHandler({
    handler: resolve('./runtime/server/assets.get'),
    route: '/api/assets',
    method: 'get',
  })
```
The resulting `nitro-routes.d.ts` generated is
```javascript
// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
   ...
'/api/assets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../src/runtime/server/assets').default>>>>
    }
```
It's missing the `.get` from the import.

The fix is easy, I just renamed the file `assets-get.ts` but I wanted to keep the same naming convention in my nuxt module as in a Nuxt application using the `.get,.post,..` filename convention.

**Comment by Barbapapazes** [comment]
Yes, I can confirme that.

reproduction https://stackblitz.com/edit/github-o26m3b?file=routes%2Fnice.hello.ts

/nice is prerendered but /nice.hello is not, even if working well in dev mode.

**Comment by pi0** [comment]
@Barbapapazes I have moved your report to #1896 it is different.
