### ISSUE TITLE
Prerendering a page that uses navigateTo results in an error

### ISSUE THREAD

**Issue by tobiasdiez** [unjs/nitro#1402]
### Environment

- Operating System: Windows_NT
- Node Version:     v19.9.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2

### Reproduction

Do you have a starter template for reproductions?

### Describe the bug

If you use `navigateTo` on a (nuxt) page that is prerendered, the prerendering fails as the status code is 302 and not 200:

```
Prerendering 4 initial routes with crawler                        nitro 20:02:29
  ├─ ....
  ├─ /download (208ms) (Error: [302] )                               nitro 20:02:31
                                                                     nitro 20:02:31  
Errors prerendering:
  ├─ /download (302)
```

### Additional context

This error comes from the check
https://github.com/unjs/nitro/blob/6bc50b2f9416dc9af6ba327440deea2ec8e35a33/src/prerender.ts#L171-L176.

If one adds `res.status !== 302` it works well. I can open a PR with this fix, but I'm not sure if there are any negative consequences or if there is a better way to handle prerenders of redirects.

**Comment by davidsandoz** [comment]
I also get the same behaviour with Nitro 2.5.2 (Nuxt 3.6.2), that I didn't get with Nitro 2.5.1 (Nuxt 3.6.1), but because of `redirect` in the `routeRules` of `nuxt.config.ts`
```
  routeRules: {
    '/': {redirect: '/search'}
  },
```

I get this error:
```
...
Generated public .output/public
Initializing prerenderer
Prerendering 3 initial routes with crawler
   ├─ / (11ms) (Error: [307] )
   ├─ /200.html (48ms)
   ├─ /404.html (48ms)
 
Errors prerendering:
   ├─ / (307)
```

The _307 Temporary Redirect_ is interpreted as an error.

I suppose that all 3xx redirection status codes could be allowed.

**Comment by MarcusAngel** [comment]
Bumping this as currently any kind of redirect in a route completely blocks pre-rendering completely

**Comment by Hebilicious** [comment]
Related https://github.com/unjs/nitro/issues/1418

**Comment by pi0** [comment]
Let's followup via #1418
