### ISSUE TITLE
OOM termination when using `extends` nuxt feature

### ISSUE THREAD

**Issue by Aareksio** [unjs/nitro#1458]
### Environment

Nuxi 3.6.3
Nuxt 3.6.3 with Nitro 2.5.2
Node v20.4.0
pnpm 8.6.6
Windows 11 and Windows 11 WSL2 Debian

### Reproduction

https://github.com/Aareksio/nitro-issue-build-workspace

### Describe the bug

Nitro runs into OOM when working with pnpm layers. Seems to be related to pnpm workspaces - not sure, but this is how it's easy to replicate. Effectively results in [503 error on dev server URL](https://github.com/unjs/nitro/issues/1454), which ultimatelly ends with memory allocation failure during "nitro build" phase.

Layers extended from remote dependencies does not seem to share the issue.

### Additional context

Naturally I understand building the project requires resources and an example with extending 50 layers is reasonably expected to be problematic. The real issue is how even a single empty layer adds 2.5s on i9-13900 - seems more like a bug than intended behavior.

Reproduces on: Windows 11 and WSL 2 running Debian (WSL filesystem)
Does **not** reproduce on macos (intel and m1)

### Logs

Base project (expected behavior):
```sh
ℹ Vite client warmed up in 327ms
✔ Nitro built in 182 ms
```

Extending empty layer (minimal reproduction):
```sh
ℹ Vite client warmed up in 439ms
✔ Nitro built in 2562 ms
```

Extending empty layer x50 (minimal OOM reproduction):
```sh
ℹ Vite client warmed up in 4727ms                                                                     

<--- Last few GCs --->

[16210:0x5ae9ce0]    83427 ms: Mark-Compact 1978.6 (2083.8) -> 1963.2 (2084.0) MB, 661.54 / 0.00 ms  (average mu = 0.088, current mu = 0.028) task; scavenge might not succeed
[16210:0x5ae9ce0]    84061 ms: Mark-Compact 1979.2 (2084.3) -> 1964.6 (2084.8) MB, 618.62 / 0.00 ms  (average mu = 0.057, current mu = 0.025) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xc94240 node::Abort() [/usr/bin/node]
 2: 0xb6df9f  [/usr/bin/node]
 3: 0xeb4120 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/bin/node]
 4: 0xeb4407 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/bin/node]
 5: 0x10c5a75  [/usr/bin/node]
 6: 0x10c6004 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]
 7: 0x10dcef4 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*) [/usr/bin/node]
 8: 0x10dd70c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 9: 0x11364cc v8::internal::MinorGCJob::Task::RunInternal() [/usr/bin/node]
10: 0xd0b8b6  [/usr/bin/node]
11: 0xd0e46f node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/usr/bin/node]
12: 0x1874233  [/usr/bin/node]
13: 0x1888bfb  [/usr/bin/node]
14: 0x1874f57 uv_run [/usr/bin/node]
15: 0xbafba6 node::SpinEventLoopInternal(node::Environment*) [/usr/bin/node]
16: 0xce16b6 node::NodeMainInstance::Run() [/usr/bin/node]
17: 0xc4ce0f node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResultImpl const*) [/usr/bin/node]
18: 0xc50792 node::Start(int, char**) [/usr/bin/node]
19: 0x7fe21c935d0a __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
20: 0xbac62e _start [/usr/bin/node]
```

**Comment by pi0** [comment]
Would you please make a "Nitro" minimal reproduction to track from here? 🙏🏼

**Comment by Aareksio** [comment]
I am not quite sure (yet) how to reproduce with nitro only. Trying to debug it myself, I stumbled upon related discussion in nuxt/nuxt with someone having the exactly same issue with docus. This is definitely not related to the other 503 issue :)

https://github.com/nuxt/nuxt/discussions/20213

**Comment by Hebilicious** [comment]
Thanks for the investigation @Aareksio ❤️ 

@danielroe Should we transfer this back to Nuxt ?

**Comment by danielroe** [comment]
Yes, it sounds like it is a Nuxt issue 👍

I'll investigate further and close here.

**Comment by danielroe** [comment]
Confirmed. And should be fixed within Nuxt in https://github.com/nuxt/nuxt/pull/22214. Thank you @Aareksio for lovely investigation. ❤️
