### ISSUE TITLE
Use mongodb， can't  new MongoClient

### ISSUE THREAD

**Issue by CooLNuanfeng** [unjs/nitro#1479]
### Environment

node: v16.14.0
nitropack: lastest

### Reproduction

import { MongoClient } from 'mongodb'

export default cachedEventHandler(async (event)=>{
  const { page, pageSize = 10 } = getQuery(event)

  // Connection URL
  const mongoUrl = 'mongodb://localhost:27017';
  console.log('aaaa')
  const client = new MongoClient(mongoUrl);
  console.log('bbbb')
  await client.connect();
  const db = client.db('mydb');
  const collection = `db.collection('list');

  ......

### Describe the bug

[nitro] [request error] [unhandled] mongodb_connection_string_url_1.default is not a constructor

**Comment by Hebilicious** [comment]
Possibly duplicate #949 #1024
