### ISSUE TITLE
Vercel Serverless preset doesn't stream responses because `supportsResponseStreaming: true` is missing from vercel config

### ISSUE THREAD

**Issue by nksaraf** [unjs/nitro#1505]
### Environment

Node: v18.15.0
Nitropack: 2.5.2

### Reproduction

Deploy an app with streaming to "vercel" preset

### Describe the bug

The handler is responding with a NodeJS stream and works on NodeJS normal. Typically lambda has not supported streaming so Vercel's serverless offering didn't either, but recently they added support for it but its behind a flag called `supportsResponseStreaming` that needs to be applied to your serverless function's `vc_config.json`. 

I think we should make this the default so people don't get bit by it not realizing that they need to enable this. People could potentially be given an option to disable it.

**Comment by pi0** [comment]
Reproduction: https://github.com/unjs/nitro-deploys/blob/main/routes/stream.ts#L55 (with edge and h3 nightly)

https://nitro-app.vercel.app/
