### ISSUE TITLE
Open Next integration

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1566]
Just discovered [sst/open-next](https://github.com/sst/open-next/tree/main) project (https://open-next.js.org/) (thanks for sharing @chris-visser!).

I think somehow we could integrate Nitro with this adapter, opening a way to welcome Next.js into supported frameworks and deploy to any environment. 

How? Ideas welcome!

**Comment by ennioVisco** [comment]
> Just discovered [sst/open-next](https://github.com/sst/open-next/tree/main) project (https://open-next.js.org/) (thanks for sharing @chris-visser!).
> 
> I think somehow we could integrate Nitro with this adapter, opening a way to welcome Next.js into supported frameworks and deploy to any environment.
> 
> How? Ideas welcome!

I just learned about this project and I love their philosophy! 
I believe this is an incredibly nice idea 🤩
