### ISSUE TITLE
issue with `element-plus`, pnpm and traced externals

### ISSUE THREAD

**Issue by danielroe** [unjs/nitro#1573]
Pure nitro reproduction: https://stackblitz.com/edit/github-v64i43?file=routes/index.ts,package.json

See https://github.com/nuxt/nuxt/issues/14930 for full details

**Comment by pi0** [comment]
Thanks for making the reproduction. Please see https://github.com/unjs/nitro/pull/1553 for more context. 

It is possible to solve this issue with Nitro 2.6:

```ts
import { defineNitroConfig } from "nitropack/config";

export default defineNitroConfig({
  externals: {
    traceAlias: {
      "@sxzz/popperjs-es": "@popperjs/core",
    },
  },
});
```

This is not something we can simply fix to cover all cases but we might work on https://github.com/unjs/nitro/issues/1574 to try to automatically infer aliases (one possible issue is with conflicting aliases.)
