### ISSUE TITLE
Firebase Preset Options not working 

### ISSUE THREAD

**Issue by RahulDey12** [unjs/nitro#1575]
### Environment

Nuxt 3

### Reproduction

production

### Describe the bug

I am using nuxt3 with nitro and firebase but I want to have firebase gen 2 functions but I am getting type error I don't know If I am doing something wrong 

![image](https://github.com/unjs/nitro/assets/26340814/4e1650f5-edd1-43b0-9144-b7aad0d456a9)

**Comment by ManasMadrecha** [comment]
Same issue here with Nuxt3 app.

**Comment by Hebilicious** [comment]
You will need to use `nitropack-edge` as this hasn't been released yet.

**Comment by ynechaev** [comment]
>You will need to use nitropack-edge as this hasn't been released yet.

@Hebilicious can you elaborate please?

**Comment by RahulDey12** [comment]
@ynechaev it's not released. So you need to use edge version just like beta version.

**Comment by Hebilicious** [comment]
Actually this was introduced in https://github.com/unjs/nitro/releases/tag/v2.6.0 🎉
