### ISSUE TITLE
Test Failures and Errors in pnpm test

### ISSUE THREAD

**Issue by jeanpierrecarvalho** [unjs/nitro#1581]
### Environment

Nitro Package Version: `2.5.2`
Node Version: `v18.12.1`
Operating System: `Linux`

### Reproduction

- Fork and clone [unjs/nitro](https://github.com/unjs/nitro)
- Enable [corepack](https://github.com/nodejs/corepack) using `corepack enable` (use `npm i -g corepack` for Node.js < 16.10)
- Install dependencies using `pnpm install`
- Activate passive watcher using `pnpm stub`
- Run the `pnpm test` command

### Describe the bug

When installing a fresh repository and running the tests using the the following error occurs, leading to the failure of 3 tests:

```
FAIL  test/presets/nitro-dev.test.ts > nitro:preset:nitro-dev > headers > handles headers correctly
FAIL  test/presets/node.test.ts > nitro:preset:node > headers > handles headers correctly
FAIL  test/presets/vercel.test.ts > nitro:preset:vercel > headers > handles headers correctly
```

It seems that the tests related to handling headers correctly in various presets (nitro-dev, node, and vercel) are failing.

This issue prevents successful test execution, and the headers handling functionality seems to be the root cause of the failure.

Please investigate and address this bug as it impacts the reliability of the Nitro package. If you require any further information or assistance, feel free to reach out.

**Comment by jeanpierrecarvalho** [comment]
![image](https://github.com/unjs/nitro/assets/90358872/3aabead7-3b82-4e0e-a315-813fc03d4739)

**Comment by jeanpierrecarvalho** [comment]
Could this PR be the reason behind the issue? #1452

**Comment by jeanpierrecarvalho** [comment]
Running `pnpm test` using `v17.0.0` all the tests passed successfully.

Running `pnpm test` using `v18.0.0` the `headers["set-cookie"]` is undefined

Running `pnpm test` using `v18.12.1` the `headers["set-cookie"]` is `foo=bar, bar=baz, test=value; Path=/,…` and is expected `[ 'foo=bar, bar=baz', …(2) ]`

**Comment by pi0** [comment]
Hi dear @jeanpierrecarvalho thanks for raising this issue 👍🏼  If you upgrade to the latest `v18.16.1`, the tests successfully pass (18.12.0 seems to have issues that are solved in latest. i can reproduce only with 18.12 too).

BTW we are aware of cookie-splitting misbehavior between different Node.js versions (you can followup from https://github.com/unjs/nitro/issues/1462). It is not as critical as it seems and not a new issue (we added more tests in the suite to track only).

**Comment by jeanpierrecarvalho** [comment]
Thanks @pi0 for the speedy response! I'll take a look at #1462.
