### ISSUE TITLE
preset 'cloudflare-pages' has deprecated command

### ISSUE THREAD

**Issue by dreitzner** [unjs/nitro#1612]
### Environment

When runing a nuxt3 build with the cloudflare-pages preset I get a deprecated command suggestion.

Running the publish command:
```bash
npx wrangler pages publish dist/
▲ [WARNING] `wrangler pages publish` is deprecated and will be removed in the next major version.

  Please use `wrangler pages deploy` instead, which accepts exactly the same arguments.
```

### Reproduction

1. build your app with cloudflare-pages preset
2. run deply command
3. see the deprecated warning

### Describe the bug

Deprecated warning for deploy command suggestion.

**Comment by Hebilicious** [comment]
Thanks @dreitzner , this will be included in Nitro 2.6 https://github.com/unjs/nitro/pull/1393/files
