### ISSUE TITLE
Bun streams get segfault with small streams

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1626]
Reproduction:

- Clone nitro repo
- `pnpm nitro build test/fixture --preset bun`
- `bun --bun run test/fixture/.output/server/index.mjs`
- Open http://localhost:3000/stream

```
Listening on http://localhost:3000...
[1]    29539 segmentation fault  bun run test/fixture/.output/server/index.mjs
```

Interestingly [this small stream fails](https://github.com/unjs/nitro/blob/main/test/fixture/routes/stream.ts) but the [bigger stream](https://github.com/unjs/nitro-deploys/blob/main/routes/stream.ts) if copied, works fine!

**Comment by pan93412** [comment]
Seems fixed in upstream.
