### ISSUE TITLE
Merge pre-exisiting web.config iis_node

### ISSUE THREAD

**Issue by Hardaker587** [unjs/nitro#1628]
### Describe the feature

Thank you for bringing out the IIS presets! It's been long awaited but much appreciated - I do have one small issue that I would like to request a feature for:

- During build, there needs to be a way to import an existing web.config file - right now I don't see any of my environment variables that would otherwise normally be in there.

Proposed solution:
Either merge the files together or generate the appsettings xml tag based on the runtimeConfig

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="NODE_ENV" value="production" />
  </ appSettings>
</ configuration>
```

I'd be more than happy to give this a bash to resolve this for you

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Supporting override via `iis.config` (in nuxt/nitro config) would be nice!

Also we might automatically generate env section for defaults + runtime config wdyt?

**Comment by Hardaker587** [comment]
Sounds amazing! I am currently writing the changes necessary to be able to cater for these things

First thing I am busy with at this point is merging the two different web.configs if one exists - like in my case

**Comment by Hardaker587** [comment]
Added PR https://github.com/unjs/nitro/pull/1656
