### ISSUE TITLE
RollupError: "rm" is not exported by "node_modules/.pnpm/unenv@1.7.3/node_modules/unenv/runtime/node/fs/promises/index.mjs"

### ISSUE THREAD

**Issue by oritwoen** [unjs/nitro#1629]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.6.0
- Package Manager:  pnpm@8.6.12
- Builder:          vite
- User Config:      css, app, runtimeConfig, modules, i18n, unocss, experimental, devtools, nitro, routeRules, sitemap
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.3, @nuxtjs/strapi@1.9.3, @nuxtjs/fontaine@0.4.1, @nuxtjs/html-validator@1.5.2, @unocss/nuxt@0.55.2, @vueuse/nuxt@10.3.0, @formkit/nuxt@1.0.0-beta.12, nuxt-swiper@1.2.0, nuxt-simple-sitemap@3.2.5
- Build Modules:    -
------------------------------

### Reproduction

NITRO_PRESET=cloudflare-pages pnpm build

### Describe the bug

![Zrzut ekranu z 2023-08-24 15-16-12](https://github.com/unjs/nitro/assets/18102267/c4abbe66-f69f-4a64-bfc7-dc4ae9d1b4ce)

**Comment by oritwoen** [comment]
@harlan-zw this bug occurs after install https://nuxtseo.com/sitemap

**Comment by pi0** [comment]
It is strange because we do export cp ([source](https://github.com/unjs/unenv/blob/fa3629def7d41fac0de12b76325ea9f2d1e8d568/src/runtime/node/fs/promises/_promises.ts#L8)). 

Can you please make a runnable reproduction i can check? 🙏🏼

**Comment by oritwoen** [comment]
Here you go @pi0 https://codesandbox.io/p/sandbox/late-feather-dcsq8h

The error does not occur on the `node-server` preset. Appeared on the `cloudflare-pages` preset. Also no problem with dev. The problem occurs with `nuxi build`.

**Comment by harlan-zw** [comment]
> @harlan-zw this bug occurs after install https://nuxtseo.com/sitemap

Will see if I can use unstorage instead 👍

**Comment by pi0** [comment]
Thanks for making a reproduction @oritwoen. I have tracked down this issue to https://github.com/harlan-zw/nuxt-site-config/issues/3. Nuxt modules should never pull in build time dependencies such as `@nuxt/kit`. There would be many edge cases like this to happen.

**Comment by pi0** [comment]
Added missing named `node:fs/promises` exports in [unenv@1.7.4](https://github.com/unjs/unenv/releases/tag/v1.7.4). It fixes the builds by upgrading lockfile but consider that upstream issue still exists and is a serious issue nuxt is hiding...
