### ISSUE TITLE
Request to modify this place

### ISSUE THREAD

**Issue by vijayasddd** [unjs/nitro#1641]
https://github.com/unjs/nitro/blob/61144e5b83fda418ca2b07e41427c6f782117089/src/runtime/static.ts#L79

The following send function is asynchronous. At this time, the code will not wait for the completion of the send, but will continue to go, and then the current res will be terminated by other tasks. When the res is completed, the send function will be executed. At this time, the send function will send a response again. It will report an error Cannot set headers after they are sent to the client nuxt

**Comment by pi0** [comment]
#1639
