### ISSUE TITLE
Nitro DevProxy ignores target basePath

### ISSUE THREAD

**Issue by cs8898** [unjs/nitro#1643]
#### NitroPack

```
nitropack@latest:
  version "2.6.1"
```

#### Nitro Config

```ts
export default defineNitroConfig({
    devProxy: {
        "/api": {
           target: "http://localhost:3001/api"
        }
    }
});
```

#### Node

```
v18.12.1
```

#### Yarn

```
1.22.19
```

### Reproduction

Sample is provided in https://github.com/cs8898/nitro_devproxy_mre

#### Problem

Nitro devProxy drops basepath of proxied server (only accepts Protocol, Host and Port of URL)

##### Expected

```raw
http://nitro:3000/api/foo => http://server:3001/api/foo
```

##### Observed

```raw
http://nitro:3000/api/foo => http://server:3001/foo
```

**Comment by cs8898** [comment]
Possible Relevant File:
https://github.com/unjs/nitro/blob/main/src/dev/server.ts#L170C33-L170C33

**Comment by cs8898** [comment]
Actually httpxy is ignoring the BaseURL
Nitro just drops the Route Segment of the defined Router

https://github.com/cs8898/nitro_devproxy_mre/commit/f15a35fd636d37b490affd053a79c04c9e446eb0

**Comment by jonasolesen** [comment]
FWIW, I tried looking into this and also found the bug to be in httpxy. When setting the target path, it is using a `path` property on an URL object. This property does not exist, and changing it to `pathname` seems to have solved the issue: https://github.com/jonasolesen/httpxy/commit/0919f9d0be5b4749bb9d40c6f9557e0137712818

**Comment by cs8898** [comment]
that seems to help Thanks

https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname

**Comment by cs8898** [comment]
@jonasolesen Works also for me, i can confirm, that solved the Problem.

I will close that here, if you could create an PR that would be great

**Comment by jonasolesen** [comment]
@cs8898 That's great! I've submitted an issue and a [PR](https://github.com/unjs/httpxy/pull/6)- hoping the fix is as simple as it seemed 🙂
