### ISSUE TITLE
Vercel returns 404 pages when using links that end in a slash and the vercel-static preset

### ISSUE THREAD

**Issue by hecktarzuli** [unjs/nitro#1651]
### Environment

node 18.15.0
nitropack 2.6.1

### Reproduction

Create a nitro project using the `vercel-static` preset
Enable the nitro crawler
create a homepage
create an about page
add a link to the about page on the homepage with a link that ends in a slash

### Describe the bug

When you deploy a project using the `vercel-static` preset, if a page you're linking to has a url that ends in a slash, both the non-slash, and slash version of that page will be 404.

**Link with trailing slash link causes `/about/` and `/about` to 404**
https://github.com/hecktarzuli/nitro-vercel-bug
https://nitro-vercel-9kao2bwpo-hecktarzuli.vercel.app/about

**Link without trailing slash shows `/about/` and `/about` as 200 as expected**
https://github.com/hecktarzuli/nitro-vercel-bug/tree/about-link-with-no-ending-slash
https://nitro-vercel-bp1o9yo22-hecktarzuli.vercel.app/about

**Crawling Disabled**
If you turn off crawling and remove the link from the homepage (for good measure)
prerender.routes['/about'] lets both `/about/` and `/about` 200.
prerender.routes['/about/'] makes `/about/` and `/about` 404.

### Additional context

I noticed this a while after I upgraded my version of Nuxt to 3.5.0.  All of a sudden, my pages were getting removed from google.  It turns out, the 404 page in nuxt was returning 404, but was rendering the pages client-side so the site still looked fine but behind the scenes was returning an SPA.

Google noticed
![image](https://github.com/unjs/nitro/assets/2112282/21dc3562-cbee-4ed7-8582-d607462bcbde)

And removed pretty much all of my pages from it's index
![image](https://github.com/unjs/nitro/assets/2112282/557fa01b-69e1-4ee0-97e7-f216d6a10536)

Since I actually build my site with both Vercel and Netlify, I just pointed my domain to Netlify.  It's working as expected there.

**Comment by Hebilicious** [comment]
duplicate https://github.com/unjs/nitro/issues/1394

**Comment by hecktarzuli** [comment]
Just so yall don't feel bad, I got my traffic back after switching to Netlify.
![image](https://github.com/unjs/nitro/assets/2112282/e264915b-5a6a-4bc6-835a-af43665462ad)
