### ISSUE TITLE
[docs] nitro website is down

### ISSUE THREAD

**Issue by qin-guan** [unjs/nitro#1667]
### Environment

NA

### Reproduction

Visit https://nitro.unjs.io

### Describe the bug

Nitro documentation is not accessible

![image](https://github.com/unjs/nitro/assets/10321883/8319875a-22f5-4448-9e13-8695fe50ff9e)

**Comment by danielroe** [comment]
Thanks! We're transferring it to a different hosting account but it should be up again shortly.

**Comment by qin-guan** [comment]
Hey @danielroe, glad to know it isn’t a server going up in flames somewhere! 😂 In that case I will close this issue, thanks so much for the prompt response!! 🙏
