### ISSUE TITLE
Rollup error: Could not load unenv/runtime/proxy-cjs/promises.mjs

### ISSUE THREAD

**Issue by leo91000** [unjs/nitro#168]
### Environment

Nitro: `0.3.8`
Node: `16.15.0`

### Reproduction

This is probably a dependency issue, however I can't find a way to know which dependency I should remove or fork to isolate problem. Is there a way to debug similar issues ?

### Describe the bug

When I bundle my code with preset `cloudflare` I get the following error :
```
Rollup error: Could not load node_modules/unenv/runtime/mock/proxy-cjs/promises.mjs: ENOENT: no such file or directory, open 'node_modules/unenv/runtime/mock/proxy-cjs/promises.mjs'
```

### Additional context

It works fine with node preset

**Comment by leo91000** [comment]
I actually found the origin of the problem : I imported module `fs/promises` and it is not mocked by unenv

**Comment by pi0** [comment]
Thanks for the notice. I've escalated it to https://github.com/unjs/unenv/issues/34
