### ISSUE TITLE
[firebase] cloud functions V2 does not compress response

### ISSUE THREAD

**Issue by andrewspy** [unjs/nitro#1680]
### Environment

- Nuxt 3.7.0 with Nitro 2.6.2
- Node 16
- firebase cloud functions V2

### Reproduction

See the response header in a sample deployed at:

[https://x-nuxt-play.web.app/_](https://x-nuxt-play.web.app/_)

### Describe the bug

Server functions do not compress the response with the "Content-Encoding:" header. You can see a deployed sample:

[https://x-nuxt-play.web.app/_](https://x-nuxt-play.web.app/_)

### Additional context

- I'm not sure if V1 has the same issue.

### Logs

```sh
Response header

Accept-Ranges: bytes
Alt-Svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
Cache-Control: private
Content-Length: 270892
Content-Type: text/html;charset=utf-8
Date: Thu, 31 Aug 2023 00:18:54 GMT
Server: Google Frontend
Strict-Transport-Security: max-age=31556926; includeSubDomains; preload
Vary: cookie,need-authorization, x-fh-requested-host, accept-encoding
X-Cache: MISS
X-Cache-Hits: 0
X-Cloud-Trace-Context: 8b940965f6303721a67b120b426f0593;o=1
X-Country-Code: MY
X-Orig-Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,ms;q=0.6,zh-SG;q=0.5,ms-MY;q=0.4,zh-TW;q=0.3
X-Powered-By: Nuxt
X-Served-By: cache-kul9826-KUL
X-Timer: S1693441133.275240,VS0,VE952
```

**Comment by Hebilicious** [comment]
cc @posva

**Comment by luc122c** [comment]
I've used https://www.giftofspeed.com/gzip-test/ and confirmed this to be the case with a mix of gen1 and gen2 Nuxt deployments.

**Comment by andrewspy** [comment]
Closing this in favor of a workaround in #1007.
