### ISSUE TITLE
Firebase gen 2 ignoring httpsOptions

### ISSUE THREAD

**Issue by JabirWiz** [unjs/nitro#1682]
### Environment

Nuxt 3.7.0 with Nitro 2.6.1
Node 18
firebase cloud functions V2

### Reproduction

`httpsOptions: {
  region: 'asia-south1',
}`

### Describe the bug

when selecting a region with Gen 2  function, the region is ignored and is deploying with default region (us-central1).

### Additional context

When looked into the build output:

`const server = onRequest(
  {
    // Must be set to public to allow all public requests by default
    invoker: "public",
    ...firebaseConfig.httpOptions
  },
  toNodeListener(nitroApp.h3App)
);`

`firebaseConfig.httpOptions` is `undefined`
the option object is `firebaseConfig.httpsOptions`

I tried replacing the code with `replace` option in nitro but it didn't work

**Comment by Hebilicious** [comment]
This will be fixed with https://github.com/unjs/nitro/pull/1663
