### ISSUE TITLE
On demand cache invalidation

### ISSUE THREAD

**Issue by hcmlopes** [unjs/nitro#1699]
### Describe the feature

Ability to invalidate the cache on demand.

Example use case:
1. Content changed in CMS could then trigger a rebuild via webhook.

### Additional information

- [X] Would you be willing to help implement this feature?

#### Resources
https://vercel.com/docs/build-output-api/v3
https://github.com/unjs/nitro/blob/main/src/presets/vercel.ts

**Comment by pi0** [comment]
Hi. Are you aiming to invalidate (Vercel) ISR cache or nitro cache?

**Comment by pi0** [comment]
Shall we track it via https://github.com/unjs/nitro/issues/1694?

**Comment by hcmlopes** [comment]
Yes, apologies as searched for cache invalidation and didn't see that. Thanks for bringing it up.

**Comment by jesperbjerke** [comment]
We very much would like the possibility to invalidate the nitro cache using SWR and not ISR for exactly the use case described

**Comment by pi0** [comment]
Extended discussion about nitro native cache / non-vercel ISR invalidation ~> #1060
