### ISSUE TITLE
Incorrect content-type in 304 response for static (text) assets

### ISSUE THREAD

**Issue by samimakela** [unjs/nitro#1700]
### Environment

Node.js 18.17.0
Nitro 2.6.2

### Reproduction

1. Build and start playground
```
pnpm dev:build
pnpm dev:start
````
2. Run
```
curl -i 'http://localhost:3000/test.txt' \
     -H 'if-modified-since: "Thu, 07 Sep 2030 00:00:00 GMT"'
```

### Describe the bug

A 304 response includes a (wrong) content-type header for static assets. 

See example below for `test.txt`:

```
HTTP/1.1 304 Not Modified
content-type: text/html
Date: Thu, 07 Sep 2023 04:49:17 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

304 response ideally would not include the content-type header at all. The next best option would be to include the correct MIME type of the asset.

The bug can lead to quite nasty problems at least with some CDNs (in our case Google Cloud CDN). 

### Additional context

It seems that H3 [sets the content-type header](https://github.com/unjs/h3/blob/12ccb81432a62783fe951a8170976c8162bce44a/src/utils/response.ts#L72) to a default MIME type if no content-type header is provided by the handler.

**Comment by Jamie4224** [comment]
Can confirm that this issue is still present. When a request is made to nitro (/nuxt) for static assets and the `if-modified-since` is present, the response is a 304 with a content-type of text/html.

An issue here is that Google Cloud CDN caches the assets, and then later issues cache validation using the `if-modified-since`. It then overwrites the cached headers with the new ones, which also happens for css and js files. This completely breaks the Nuxt app because strict mime checks prevent the js assets from loading.

**Comment by grob** [comment]
Ran into the same Issue today (using Varnish as reverse Proxy)

**Comment by botic** [comment]
[RFC 7232 suggests](https://www.rfc-editor.org/rfc/rfc7232#section-4.1) sending no Content-Type header for conditional requests:

> The server generating a 304 response MUST generate any of the following header fields that would have been sent in a 200 (OK) response to the same request: Cache-Control, Content-Location, Date, ETag, Expires, and Vary.
> 
> Since the goal of a 304 response is to minimize information transfer when the recipient already has one or more cached representations, **a sender SHOULD NOT generate representation metadata other than the above listed fields** unless said metadata exists for the purpose of guiding cache updates (e.g., Last-Modified might be useful if the response does not have an ETag field).

**Comment by Jamie4224** [comment]
This issue has been fixed upstream: https://github.com/unjs/h3/issues/603#issuecomment-1911060153

**Comment by pi0** [comment]
To recieve the update, you can recreate your lockfile or use package manager's `upgrade` command (nitro uses a semver dependency on h3 that allows using latest release with fix) & thanks for reporting again ❤️
