### ISSUE TITLE
Automatically generate runtime config types from nitro.config the same as Nuxt

### ISSUE THREAD

**Issue by McPizza0** [unjs/nitro#1706]
### Describe the feature

In Nuxt runtimeConfig keys/values are typed.
This improves DX considerably when accessing vis useRuntimeConfig()

Nitro has not yet implemented this, which can cause some confusion for users coming over from Nuxt

Result:
useRuntimeConfig() should be aware of the keys that exist in nitro.config.ts, and provide correct types

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by algora-pbc** [comment]
💎 **$20** bounty created by @McPizza0
👉 To claim this bounty, [submit your pull request on Algora](https://console.algora.io/bounties/clmaktvvc0002mh0fg3gnso7c)
📝 Before proceeding, please make sure you can [**receive payouts**](https://docs.algora.io/bounties/payments#country-support) in your country
💵 Payment arrives in your account 2-5 days after the bounty is rewarded
💯 You keep 100% of the bounty award
🙏 Thank you for contributing to unjs/nitro!

**Comment by pi0** [comment]
This is a good idea. As part of the implementation notes, I think we should enable it only by `nuxi` CLI as an opt-in flag to avoid conflicting with Nuxt types. /cc @danielroe

**Comment by mnmt7** [comment]
I would like to take a look at this.

**Comment by McPizza0** [comment]
This would also help in nuxt when accessing runtime config from server side utils.

Currently when using useRuntimeConfig in a tRPC route, nothing is typed.

**Comment by rishi-raj-jain** [comment]
@McPizza0 @pi0 Can you help me point into the right direction?

**Comment by McPizza0** [comment]
@rishi-raj-jain this may need input from @pi0 and @danielroe 

I'm not sure how it was implemented in nuxt, but I would assume the solution will be fairly similar

Need to make sure it doesn't conflict with nuxt

**Comment by mnmt7** [comment]
@pi0 @McPizza0 @danielroe 

Maybe we can use the TypeScript Compiler API to parse the configuration file and extract the types and then generate TypeScript definition files (.d.ts) based on the extracted types and apply the generated types.

**Comment by pi0** [comment]
We use [unjs/untyped](https://github.com/unjs/untyped) to do inference in Nuxt.

See this for reference: https://github.com/nuxt/nuxt/blob/dfdebf29191b7ef2c00873b1201bf48a206bf95e/packages/nuxt/src/core/templates.ts#L140

**Comment by rishi-raj-jain** [comment]
@ap172x sure go ahead.

**Comment by oleksandr-shvets** [comment]
@ap172x @rishi-raj-jain @karthiknadar1204 can I take this?

/attempt #1706
