### ISSUE TITLE
[cloudflare_pages_static] 404 status code is not allowed in redirects

### ISSUE THREAD

**Issue by Atinux** [unjs/nitro#1714]
![CleanShot 2023-09-11 at 15.52.58.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_09_11_at_15_52_58_996acd3fd6.png)

cc @Hebilicious

**Comment by Hebilicious** [comment]
duplicate https://github.com/unjs/nitro/issues/1674
