### ISSUE TITLE
RouteRules about nuxt.config in nuxt3

### ISSUE THREAD

**Issue by Maxbsy** [unjs/nitro#1717]
### Describe the feature

In nuxt.config.js in nuxt2 I use this
Document address [https://www.nuxtjs.cn/faq/http-proxy](url)
`proxy: {
    "/*.txt": "https://example.com",
  },
`
But using this in nuxt3 does not take effect
` nitro: {
    routeRules: {
      '/**.txt': {
        proxy: 'https://example.com/**.txt'
      },
    }
  },`
Can this feature be made compatible in the future?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by DamianGlowala** [comment]
Having a similar issue, can't get the proxy to work with the following config:
```
export default defineNuxtConfig({
  routeRules: {
    "/api/**": {
      proxy: "<backend_url>/api/**"
    },
    "/cdn/**": {
      proxy: "<cdn_url>/**"
    }
  }
}
```

**Comment by Maxbsy** [comment]
> Having a similar issue, can't get the proxy to work with the following config: A similar issue was encountered and the agent could not be made to use the following configuration:
> 
> ```
> export default defineNuxtConfig({
>   routeRules: {
>     "/api/**": {
>       proxy: "<backend_url>/api/**"
>     },
>     "/cdn/**": {
>       proxy: "<cdn_url>/**"
>     }
>   }
> }
> ```

in nuxt3, you can try this 
```
export default defineNuxtConfig({
  nitro: {
      routeRules: {
      "/api/**": {
        proxy: "<backend_url>/api/**"
       },
      }
    }
})
```

**Comment by DamianGlowala** [comment]
AFAIK, these are equivalent. The `routeRules` instead of `nitro.routeRules` is meant for convenience.

That's what I am currently getting when trying to hit a proxied backend endpoint:
```
{
  "url": "/api/<endpoint_path>",
  "statusCode": 500,
  "statusMessage": "",
  "message": "fetch failed",
  "stack": "<pre><span class="stack internal">at Object.fetch (node:internal/deps/undici/undici:11600:11)</span> <span class="stack internal">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span> <span class="stack internal">at async sendProxy (/C:/<project_path>/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1034:20)</span> <span class="stack internal">at async Object.handler (/C:/<project_path>/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1630:19)</span> <span class="stack internal">at async Server.toNodeHandle (/C:/<project_path>/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1840:7)</span></pre>"
}
```

**Comment by Maxbsy** [comment]
> AFAIK, these are equivalent. The `routeRules` instead of `nitro.routeRules` is meant for convenience.AFAIK，这些是等效的。 `routeRules` 代替 `nitro.routeRules` 是为了方便起见。
> 
> That's what I am currently getting when trying to hit a proxied backend endpoint:这就是我目前在尝试命中代理后端端点时得到的结果：
> 
> ```
> {
>   "url": "/api/<endpoint_path>",
>   "statusCode": 500,
>   "statusMessage": "",
>   "message": "fetch failed",
>   "stack": "<pre><span class="stack internal">at Object.fetch (node:internal/deps/undici/undici:11600:11)</span> <span class="stack internal">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span> <span class="stack internal">at async sendProxy (/C:/<project_path>/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1034:20)</span> <span class="stack internal">at async Object.handler (/C:/<project_path>/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1630:19)</span> <span class="stack internal">at async Server.toNodeHandle (/C:/<project_path>/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1840:7)</span></pre>"
> }
> ```
> 
> Might be to do with [this](https://github.com/nuxt/nuxt/issues/21609#issuecomment-1597723883), but I'm not sure.可能与此有关，但我不确定。

routeRules are handled like fetch，I think there should be a correlation

**Comment by davidstackio** [comment]
I'm trying to do this for [PostHog as instructed here](https://posthog.com/docs/advanced/proxy/nuxt) and I'm getting this 500 error:

```
[nuxt] [request error] [unhandled] [500] fetch failed
at Object.fetch (node:internal/deps/undici/undici:11372:11)  
at async sendProxy (./chunks/nitro/firebase-gen-2.mjs:1998:20)  
at async Object.handler (./chunks/nitro/firebase-gen-2.mjs:2354:19)  
at async toNodeHandle (./chunks/nitro/firebase-gen-2.mjs:2543:7)
```

`get` requests seem to work, but the `post` requests do not. I'm using Nuxt 3.8.2 with Nitro 2.8.1.

How can I make it work for `post` requests?

**Comment by pi0** [comment]
Hi. Both `routeRules` and `nitro.routeRules` are the same.

Only issue I can see in the original description is that `/*.txt` is not a valid route rule (yet) since you cannot combine static (`.txt`) and dynamic `*` in one segment of the path. Something like `'/proxy/*'` as the key would work.

@davidstackio The posthog example seems valid. Feel free to open a discussion in nuxt repository sharing your repo or code 🙏🏼  hat can help to reproduce this issue. They might expect a missing header or so which needs reproduction for debugging.

**Comment by davidstackio** [comment]
Thanks, just made a discussion here: https://github.com/nuxt/nuxt/discussions/25014
