### ISSUE TITLE
Wrong body encoding on `netlify`

### ISSUE THREAD

**Issue by becem-gharbi** [unjs/nitro#1719]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.7.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

 When posting a multipart form, `readMultipartFormData` won't return it on `netlify` environment.

### Describe the bug

Hi there,

`readMultipartFormData` works on development as intended. However when running on Netlify it always returns an empty array.

After debugging, it turns out that on Netlify the `body` is a string encoded in `base64`. When the encoding is falsy, `readRawBody` returns a buffer. The buffer is a created from the body with the default encoding `utf8`. 
https://github.com/unjs/h3/blob/12ccb81432a62783fe951a8170976c8162bce44a/src/utils/body.ts#L83

**Comment by becem-gharbi** [comment]
For deployment to Netlify and maybe other environments I'm not aware of, I recommend adding this Nitro plugin as workaround

```ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook("request", (event) => {

    const isBase64 = (value: string) => {
      if (typeof value !== "string") return false;
      // https://debugpointer.com/regex/regex-for-base64
      return /^(?:[a-zA-Z0-9+\/]{4})*(?:|(?:[a-zA-Z0-9+\/]{3}=)|(?:[a-zA-Z0-9+\/]{2}==)|(?:[a-zA-Z0-9+\/]{1}===))$/gm.test(
        value
      );
    };

    if (isBase64(event.node.req.body)) {
      event.node.req.body = Buffer.from(event.node.req.body, "base64");
    }
  });
});

```

**Comment by passionate-bram** [comment]
The reproduction link now 404s, would you be able to post a reproduction hosted on stackblitz?

**Comment by becem-gharbi** [comment]
I have deleted the reproduction, sorry for that. However it's basic, just try posting a multipart form, `readMultipartFormData` won't return it on Netlify. If the workaround didn't work, then probably it's a different issue.
