### ISSUE TITLE
[FEATURE] Server middlewares should have fine-grained control like client middlewares

### ISSUE THREAD

**Issue by ghoshRitesh12** [unjs/nitro#1735]
### Describe the feature

In Nuxt, I have 2 middlewares in `/middlewares` dir, namely **native** and **admin** and I can use them using the `definePageMeta()` macro in the pages that I prefer. I have a refined control over the client middlewares and which pages I want them to be in.

![image](https://github.com/nuxt/nuxt/assets/101876769/89f00928-c46b-4f53-a846-0c3f4ebbbbe6)

It would be great to have this refined control for server middlewares as well. In `/server/middlewares`, I should be able to define middlewares and use them for specific server routes and **NOT** for all server routes, which is the default behavior. I should also be able to chain middlewares, much like in the client side. 

### Additional information

- [ ] Would you be willing to help implement this feature?
```[tasklist]
### Tasks
```

**Comment by pi0** [comment]
Hi. Thanks for opening issue and explaining but Nuxt middleware are Powered by Vue router and completely different than Nitro/Server middleware. Feel free to open issue in nuxt repository.
