### ISSUE TITLE
Wildcard redirects

### ISSUE THREAD

**Issue by manniL** [unjs/nitro#1748]
### Describe the feature

If the target URL ends with `/**`, treat it as wildcard redirect and append the subpath properly.

```ts
  routeRules: {
    '/single/': { redirect: { to: '/single-2/', statusCode: 301 } }, // Works 
    '/wildcard/**': { redirect: { to: '/single/', statusCode: 301 } }, // Works
    '/wildcard/**': { redirect: { to: '/wildcard-2/**', statusCode: 301 } }, // Does not work but would be nice
  },
```

`wildcard/a` -> `wildcard-2/a`

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Atinux** [comment]
What a timing! I was going to create the same issue 😄

**Comment by pi0** [comment]
@Neoniq can you please open a new issue with preferably nitro minimal reproduction? would be happy to investigate.

**Comment by Neoniq** [comment]
> [@Neoniq](https://github.com/Neoniq) can you please open a new issue with preferably nitro minimal reproduction? would be happy to investigate.

https://stackblitz.com/edit/nuxt-starter-6g4g6thz?file=app.vue

You have to click the links and see he URL showing on the 404 page

![Image](https://github.com/user-attachments/assets/cd0e1c73-0d4e-4d54-b29e-8bb4b8529dbd)

**Comment by Neoniq** [comment]
> [@Neoniq](https://github.com/Neoniq) can you please open a new issue with preferably nitro minimal reproduction? would be happy to investigate.

https://github.com/nitrojs/nitro/issues/3303
