### ISSUE TITLE
Consola logs in Nitro handlers are not displayed with style

### ISSUE THREAD

**Issue by XStarlink** [unjs/nitro#1761]
### Environment

Nitro: 2.6.3
Consola: 3.2.3

### Reproduction

https://stackblitz.com/edit/github-ohaxwc?file=routes%2Findex.ts

### Describe the bug

Hello, I can't get consola to work properly in Nuxt 3's Nitro routes.
Consola displays no logs styles, just white text.

### Thoughts

Considering that consola is already present in Nitro, I was wondering if we couldn't have a new Nitro auto imported utility to get a logger instance like that:

```js
const logger = useLogger()
```

This approach would help circumvent version incompatibility issues, ensuring that we consistently use the appropriate version of Consola aligned with the current Nitro version. What are your thoughts on this?

I believe it aligns with the idea proposed earlier here: https://github.com/nuxt/nuxt/issues/18701

In any case, I wanted to express my gratitude for the continuous efforts in providing the best possible DX to the community. I truly admire how you're always striving to enhance it! Thank you!

**Comment by taksugit** [comment]
@XStarlink 
Hi. I use this workaround below.

You can use `from '~/node_modules/consola/dist/index.mjs';` instead of `from 'consola'`

```ts
// import { consola, createConsola } from 'consola';
import { consola, createConsola } from '~/node_modules/consola/dist/index.mjs';
```

<img width="516" alt="image" src="https://github.com/unjs/nitro/assets/83934561/c123d5c0-1765-433f-be52-4418165fdae3">

or we can get nitro logger

```ts
import { createNitro } from 'nitropack'

const { logger } = await createNitro() // withTag('Nitro')
```

**Comment by XStarlink** [comment]
> @XStarlink Hi. I use this workaround below.
> 
> You can use `from '~/node_modules/consola/dist/index.mjs';` instead of `from 'consola'`
> 
> ```ts
> // import { consola, createConsola } from 'consola';
> import { consola, createConsola } from '~/node_modules/consola/dist/index.mjs';
> ```
> 
> <img alt="image" width="516" src="https://private-user-images.githubusercontent.com/83934561/285561328-c123d5c0-1765-433f-be52-4418165fdae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMjk2MTQsIm5iZiI6MTcwMTAyOTMxNCwicGF0aCI6Ii84MzkzNDU2MS8yODU1NjEzMjgtYzEyM2Q1YzAtMTc2NS00MzNmLWJlNTItNDQxODE2NWZkYWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDIwMDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YWI2MjkxNDgxNDZlNjM3MjA0ZGNiNjRiYTllZTEzYzY3MjY4NjNlMTIyYWEyODAxNWJkMzQxMmRiOThhNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XjCAIRBK0dUE4YmzVouHp87CvDKUkCaA37WwooZlq-M">
> or we can get nitro logger like this.
> 
> ```ts
> import { createNitro } from 'nitropack'
> 
> const { logger } = await createNitro() // withTag('Nitro')
> ```

Thanks a lot for the tip @taksugit !

Just for my understanding, do you know why importing the .mjs version with '~/node_modules/consola/dist/index.mjs' works, but not the .ts version by importing 'consola' ?

**Comment by taksugit** [comment]
Sorry, I implemented this a few months ago, so I've forgotten why I wrote it like this. 😅

**Comment by therealstein** [comment]
@XStarlink this works for me 

utils/logger.ts
```utils/logger.ts
import { useLogger as nuxtLogger } from '@nuxt/kit';

export function useLogger(moduleName: string) {
  return nuxtLogger(moduleName);
}
```
and use wherever you like:

const logger = useLogger('mymodule')
