### ISSUE TITLE
Automatically Providing Helpers

### ISSUE THREAD

**Issue by imcm7** [unjs/nitro#1766]
Is here some think like

```
export default defineNuxtPlugin(() => {
  return {
    provide: {
      hello: (msg: string) => `Hello ${msg}!`
    }
  }
})
```

but for nitro?

And to be able to get that helper not only in api but in any file on server, like services (to access db helper for example or email helper)

> nitroApp.$db = connection;

Some thing at least like `event.context.db` is here for nitroApp?

**Comment by imcm7** [comment]
Module '"#imports"' has no exported member 'useNitroApp'.

**Comment by Hebilicious** [comment]
Hi, on top of regular imports and exports, you can use the [utils](https://nitro.unjs.io/guide/utils) directory or rely on h3 `event.context`.

**Comment by imcm7** [comment]
> Hi, on top of regular imports and exports, you can use the [utils](https://nitro.unjs.io/guide/utils) directory or rely on h3 `event.context`.

To access it in service is need to have event, but no event in it. the same with utils, in service is need to call someAutoImportedUtil(event), but no event here. Is need to pass event to service. But with plugin, siymply call $myPlugin(do somethink) like $myPlugin('') in nuxt.
