### ISSUE TITLE
How to run one plugin after other 

### ISSUE THREAD

**Issue by imcm7** [unjs/nitro#1768]
### Environment

-

### Reproduction
https://nitro.unjs.io/guide/plugins#available-hooks

```
export default defineNitroPlugin(async (nitroApp: NitroApp) => {
   nitroApp.hooks.hook('request', async (event: H3Event) => {
        event.context.data // <------------------- is empty because that plugin that is second finish first his task
   });
})
```

### Describe the bug

I have 2 plugins, but second finish first (make more easy task) and I can get in second plugin result from first, event.context is empty in request hook.

**Comment by imcm7** [comment]
Need one more hook like before request to use different hooks in each plugin

**Comment by imcm7** [comment]
or to not make it async?

**Comment by imcm7** [comment]
And in `nitroApp.hooks.hookOnce('close', async () => {}` no event, but I want to do some think with objects from event.context when app is closing

**Comment by Hebilicious** [comment]
> ### Environment
> 
> ### Reproduction
> [nitro.unjs.io/guide/plugins#available-hooks](https://nitro.unjs.io/guide/plugins#available-hooks)
> 
> ```
> export default defineNitroPlugin(async (nitroApp: NitroApp) => {
>    nitroApp.hooks.hook('request', async (event: H3Event) => {
>         event.context.data // <------------------- is empty because that plugin that is second finish first his task
>    });
> })
> ```
> 
> ### Describe the bug
> I have 2 plugins, but second finish first (make more easy task) and I can get in second plugin result from first, event.context is empty in request hook.
> 
> ### Additional context
> _No response_
> 
> ### Logs
> _No response_

You can order the plugins, it's written in the docs you linked : 

<img width="686" alt="image" src="https://github.com/unjs/nitro/assets/13395944/5756be6d-44d8-4d47-ae85-20426e393942">

**Comment by imcm7** [comment]
Also
```
 nitroApp.hooks.hookOnce('request', async(event: H3Event) => {
   event.context.data = 1;
}

 nitroApp.hooks.hook('request', async(event: H3Event) => {
   event.context.data // is empty ???????????????
}
```

**Comment by robertpatrick** [comment]
@Hebilicious I agree with @imcm7 that nitro needs to support async plugins.  I have async plugin code that runs at server startup but because nitro does not wait for async plugins to complete, I have a complex race condition that I have to solve to prevent API requests from trying to access the data structures being built by the plugins.

**Comment by Hebilicious** [comment]
#916
