### ISSUE TITLE
Nitro modules to extend core

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/nitro#1788]
### Describe the feature

Hello,

I'm currently asking myself how to share code between Nitro app.

Imagine, I'm building a server with auth on app A. I implement auth within code source A. Then, I'm building app B. I also need auth. How could I share code?

Currently, if I use Nuxt with Nitro, I can build a Nuxt module and modify directly the Nitro config to import some utils. If I use Nitro alone, it's not possible. In the same time, some features currently build for Nuxt could be only for Nitro and shared to other Nitro based framework. 

I could create a simple JS package but I will not be able to provide great DX like auto-import, to update the config, inject routes or more...

What do you think of modules for Nitro like in Nuxt?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for making issue. As discussed before internally, this is something i had been thinking too mainly to unblock developing experiments and integrations out of Nitro core.

Currently, you can benefit from Nuxt/Nitro layers. Nitro-only apps, can extend from `server/` directory.
