### ISSUE TITLE
Nitro request context is not available. Enable the experimental flag

### ISSUE THREAD

**Issue by imcm7** [unjs/nitro#1818]
### Environment

Nuxt 3 with auth module

### Reproduction

https://github.com/imcm7/nuxt-event

### Describe the bug

In plugin Nitro request context is not available.
If remove plugin and using the api/auth[...].ts file the useEvent() work.

**Comment by pi0** [comment]
Hi can you please make a runnable reproduction? 🙏🏼 Also does this issue also happens when running in development mode or only in the production?

**Comment by imcm7** [comment]
@pi0 https://github.com/imcm7/nuxt-event

**Comment by pi0** [comment]
closing due to  lack of minimal reproduction.

**Comment by imcm7** [comment]
You can close all and do nothing. I now want to see that framework any more.
