### ISSUE TITLE
cachedEventHandler overrides middleware cookies

### ISSUE THREAD

**Issue by MiniDigger** [unjs/nitro#1837]
### Environment

see codesandbox

### Reproduction

https://codesandbox.io/p/sandbox/interesting-cohen-pnq9y5

notice how / gets two set-cookie headers while /test only gets one

### Describe the bug

when a middleware and a route both define cookies and the  route cookie overrides the middleware cookie instead of just appending the header

### Additional context

the overriding happens here: https://github.com/unjs/nitro/blob/be6bb7ea136c464ab28eb8662eb630e11c7b0b68/src/runtime/cache.ts#L407
the setHeader should be changed to appendHeader (maybe only for the set-cookie case?)
h3 does it like this https://github.com/unjs/h3/blob/b7aca9614e7e8e8921fd54804463ce78fdb034f1/src/utils/response.ts#L341

if a consensus on a solution is reached, am open to PR it.

**Comment by danielroe** [comment]
You are right, we should use `appendHeader` for `set-cookie`.

**Comment by MiniDigger** [comment]
this was fixed by #1838
