### ISSUE TITLE
Simplify type not handling nested objects correctly

### ISSUE THREAD

**Issue by NicholasAntidormi** [unjs/nitro#1845]
Hi,

It looks like nested object are not simplified by the `Simplify` type, is it correct?

https://github.com/unjs/nitro/blob/3611071fae54276c445ff9df338f98ad8a391fa8/src/types/serialize.ts#L56

I think it should be recursive:
```
export type Simplify<TType> = TType extends any[] | Date
  ? TType
  : { [K in keyof TType]: Simplify<TType[K]> };
```

I found this while working with nuxt server apis that return complex objects, it makes manipulating them quiet annoying...

Thanks!

**Comment by danielroe** [comment]
Quite right 👌
