### ISSUE TITLE
`extends` config not working when from node package

### ISSUE THREAD

**Issue by ayoayco** [unjs/nitro#1846]
### Environment

Nitro: v2.7.0
Node: v18.16.0

### Reproduction

https://github.com/ayoayco/nitro-extends-error-recreation#readme

### Describe the bug

Extending a ~~local~~ node package as Nitro config via `extends` property produces a console message:

```
Cannot extend config from `{"devServer":{"watch":["./src/pages","./src/components"]},"serverAssets":[{"baseName":"pages","dir":"./src/pages"},{"baseName":"components","dir":"./src/components"}]}` in /Users/ayoayco/Projects/@ayoayco/nitro-extends-error-recreation
```

More info on the [reproduction readme](https://github.com/ayoayco/nitro-extends-error-recreation#readme)

A workaround I do is to spread it like so:
```ts
import config from "@some-local/config";

/**
 * @see https://nitro.unjs.io/config
 */
export default defineNitroConfig({
  ...config(),
});
```

### Additional context

I have a project https://ayco.io/gh/McFly where I'm working on a Nitro configuration I publish at [@mcflyjs/config](https://ayco.io/n/@mcflyjs/config). I test this locally, but `extends` nitro config is not working for me.

I can recreate it on a minimal [reproduction](https://github.com/ayoayco/nitro-extends-error-recreation) but I'm not sure if the problem is on my function.

### Logs

```sh
ayoayco@Ayos-MacBook-Pro nitro-extends-error-recreation % npm start

> start
> nitropack dev

Cannot extend config from `{"devServer":{"watch":["./src/pages","./src/components"]},"serverAssets":[{"baseName":"pages","dir":"./src/pages"},{"baseName":"components","dir":"./src/components"}]}` in /Users/ayoayco/Projects/@ayoayco/nitro-extends-error-recreation

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

✔ Nitro built in 208 ms                                                    nitro 12:11:03 PM
^C
ayoayco@Ayos-MacBook-Pro nitro-extends-error-recreation % 
ayoayco@Ayos-MacBook-Pro nitro-extends-error-recreation % npm run build:preview

> build:preview
> npm run build && npm run preview


> build
> nitropack build

Cannot extend config from `{"devServer":{"watch":["./src/pages","./src/components"]},"serverAssets":[{"baseName":"pages","dir":"./src/pages"},{"baseName":"components","dir":"./src/components"}]}` in /Users/ayoayco/Projects/@ayoayco/nitro-extends-error-recreation
✔ Generated public .output/public                                          nitro 12:11:12 PM
ℹ Building Nitro Server (preset: node-server)                              nitro 12:11:12 PM
✔ Nitro server built                                                       nitro 12:11:12 PM
  ├─ .output/server/chunks/_...index_.mjs (410 B) (248 B gzip)
  ├─ .output/server/chunks/_...index_.mjs.map (341 B) (188 B gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs (153 kB) (37.2 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs.map (2.93 kB) (735 B gzip)
  ├─ .output/server/index.mjs (266 B) (185 B gzip)
  └─ .output/server/package.json (110 B) (103 B gzip)
Σ Total size: 157 kB (38.6 kB gzip)
✔ You can preview this build using node .output/server/index.mjs           nitro 12:11:12 PM

> preview
> node .output/server/index.mjs

Listening on http://[::]:3000
```

**Comment by ayoayco** [comment]
I tried with a published node package and I get the same console message 🤔 so the issue might not be because it is local... I'm not sure if it's my function now, but I think I'm returning the correct type.

https://github.com/ayoayco/nitro-extends-error-recreation/commit/515b57dd804eb8357e7fa7360d1c62494c4dd86a

**Comment by ayoayco** [comment]
After investigation, I see that we allow `extends?: string | string[] | NitroPreset;` in `NitroConfig`, but there is a check in c12 loader.ts:

```
    if (typeof extendSource !== "string") {
      // TODO: Use error in next major versions
      // eslint-disable-next-line no-console
      console.warn(
        `Cannot extend config from \`${JSON.stringify(
          originalExtendSource,
        )}\` in ${options.cwd}`,
      );
      continue;
    }
```

`extends` now works for me by providing the npm package name as string... so we can close this issue.

**Comment by ayoayco** [comment]
Whoops, reopening as I didn't mean to close it myself... just close if not planned in this project :)

**Comment by pi0** [comment]
Hi! Sorry for late answering.

Config extends is supported with unjs/c12 and it requires this field to point to the **path of config dir or package**.

Is there any specific reason you might need inlined config by manually importing it yourself in extends section? It might be something we could support in c12 btw (feel free to make an issue there to track!)

**Comment by ayoayco** [comment]
No worries! I just misunderstood the intention from the type and passed an object instead, but now it's all good and I just pass the package name as string: https://github.com/ayoayco/McFly/commit/f12bb73fc89ce565a3ae7a75309a3e8c1f9748f7
