### ISSUE TITLE
`event.$fetch` is not available when caching is enabled

### ISSUE THREAD

**Issue by cjpearson** [unjs/nitro#1848]
### Environment

Nuxt@3.80, Nitropack@2.7.0, Node v18.16.0, macOS 13.6

### Reproduction

Create a new app with `nuxi init` and add a `script setup` block to `app.vue`

```
<script setup>
const event = useNuxtApp().ssrContext?.event
if (event && !event.$fetch) {
  console.warn('event.$fetch was not found!')
  console.log(event)
}
</script>
```

Then run `nuxt build` and `nuxt preview`

To reproduce the bug, update the `routeRules` in the nuxt config

```
routeRules: {
  '*': { swr: true }
}
```

### Describe the bug

When caching is enabled, `$fetch`, `fetch`, `waitUntil` and `captureError` are not added to the event object. As a result, API requests that are sent in SSR are missing the context.

**Comment by pi0** [comment]
Thanks for the report. Indeed it seems a bug. We shall polyfill `event.$fetch` from `src/runtime/cache.ts` with `globalThis.$fetch`
