### ISSUE TITLE
`.dev.ts` suffix for dev-only routes 

### ISSUE THREAD

**Issue by manniL** [unjs/nitro#1849]
### Describe the feature

Hey all 👋🏻

An equivalent of e.g. Nuxt's `<DevOnly>` component for Nitro  would be interesting and could be the `.dev.ts` suffix. All routes having a `.dev` suffix in the file would only be loaded during development and would not be present in production. 

Benefits would be automatic removal on production and being able to define e.g. debug endpoints in your dev environment 🙌 

Related: https://github.com/nuxt/nuxt/issues/18730

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
PR is welcome to implement this feature. We might also introduce a new `dev` flag to the event handler object type and allow programmatic registration of them.
