### ISSUE TITLE
Global error handler

### ISSUE THREAD

**Issue by awdr74100** [unjs/nitro#1871]
### Describe the feature

Hi, thank you unjs/nuxt team for providing such a good framework, easy to use and fast!

Consider the following situation:
```ts
export default defineEventHandler(async (event) => {
  await prisma.user.create({
    data: {
      email, // unique constraint
      password: hashedPassword,
    },
  });

  return { ok: true };
});
```

Prisma unique constraint needs to be caught via `trycatch`, but I really don't want to use `trycatch` in every event handler I have.

In express I can use the following error handler to catch:

```ts
app.use((err, req, res, next) => {
    // do something
});
```

I tried to use the composible method recommended by nitro, but I still had to use `trycatch` to catch errors: 

```ts
export default defineEventHandler(async (event) => {
  try {
    await prisma.user.create({
      data: {
        email,
        password: hashedPassword,
      },
    });

    return { ok: true, message: 'Signup successful' };
  } catch (error) {
    captureUnhandledError(error);
  }
});
```

While nitro does provide middleware functionality, I find it not very useful in practice, and I see a lot of use cases where you just use utils and apis to assemble your api logic through functions, which means only the most basic functionality in the framework.

In the latest version of nitro/h3, `onRequest` and `onBeforeResponse` hooks are provided to define handlers through `defineRequestMiddleware` and `defineResponseMiddleware`. These handlers look like they should be placed in the middleware folder but the correct place is the utils folder, like most use cases are placed in the utils folder, This makes the handlers in the middleware folder look a little useless...

Did I misunderstand there? In nitro you must use trycatch to catch unhandled errors, unless you want nitro default error handler to respond to status code 500 errors.

Thank you for reading the entire problem description! My crux is still what are the use cases of middleware and whether there are more cases to refer to. Will strengthening the functionality of middleware bring more usability?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by markthree** [comment]
@awdr74100 

I am currently using plugins to handle errors 👇

```ts
// plugins/error_handler.ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook("error", async (error, { event }) => {
    // send error message，or you can standardize errors in here
    send(event, error.message);
  });
});
```

```ts
// routes/index.ts
export default defineEventHandler((e) => {
  throw new Error("error");
});
```

**Comment by Hebilicious** [comment]
Hi, Could you consider using something like this ?


Define a handler wrapper : 

```ts
const globalHandler = (handler) => {
	try {
		return handler()
	} catch(e) {
		return handleError(e)
	}
}
```

And then you'd use it like this : 
```
export default defineEventHandler(globalHandler(async (event) => {
  await prisma.user.create({
    data: {
      email, // unique constraint
      password: hashedPassword,
    },
  });

  return { ok: true };
}));
```

Alternatively you could create your own defineEventHandler wrapper : 

```ts
export function defineEventHandlerWithErrors<T>(loader: Handler<T>) {
	try {
	  return eventHandler(loader)
	} catch(e) {
	handleError(e)
	}
}
```

**Comment by awdr74100** [comment]
@markthree @Hebilicious Thank you very much for your help! I think my understanding is still stuck in the traditional express framework, which makes me a little uncomfortable using nitro composable method.

All the methods mentioned worked for me, thank you all for your help, I will close this question.
