### ISSUE TITLE
Azure preset should use node 18 for apiRuntime

### ISSUE THREAD

**Issue by DaDlugosch** [unjs/nitro#1872]
### Environment

Nitro v2.7
Nuxt v3.8.0

### Reproduction

Reproduction is not available now, because I fixed it by replacing `node:16` with `node:18`.

### Describe the bug

When using Azure Static Web Apps as a hosting provider for the app which uses `server` folder for routes / middleware, and you are using there `$fetch` with default preset for Azure Functions runtime, which is `node:16`, you encountered an error, that `_fetch is not available`.

It is caused by major update in Nitro 2.7, which uses native `fetch` for fetch requests (https://github.com/unjs/nitro/pull/1724) which is only supported in node engines 18+.

It would be great to replace default `node:16` value for `apiRuntime` Azure property with `node:18` which is still in public preview, however instead of errors responses, fetch requests will start work on Azure Static Web Apps.
Also, after update, it needs to be replaced in docs for Azure preset.

**Comment by jshepard** [comment]
@DaDlugosch how did you replace node:16 with node:18?

**Comment by pi0** [comment]
Default is upgraded in nightly channel and will change in next Nitro release 👍🏼

**Comment by gps-lasrol** [comment]
@pi0 you know when the next release is planned for?

**Comment by pi0** [comment]
This week as planed. You can use [nightly](https://nitro.unjs.io/guide/getting-started#nightly-release-channel) channel btw in the meantime.
