### ISSUE TITLE
Cannot access params in cached event handler

### ISSUE THREAD

**Issue by farnabaz** [unjs/nitro#189]
### Environment

latest nitro version

### Reproduction

https://stackblitz.com/edit/node-1kc5ig?file=routes%2F[slug].ts

### Describe the bug

When using `defineCachedEventHandler`, nitro creates new event and call original handler with that:

https://github.com/unjs/nitro/blob/2b7209aab8667d0470949b636ff383d85057a08d/src/runtime/cache.ts#L127-L128

The problem is, new event does not contains any context, so inside handler we cannot access params or other stuff.

**Comment by farnabaz** [comment]
Ah also there is another issue with `toEventHandler` here:

https://github.com/unjs/nitro/blob/2b7209aab8667d0470949b636ff383d85057a08d/src/runtime/cache.ts#L111

If we write 
```
defineCachedEventHandler((event) => {

})
```
The first argument will become `IncommingMessage` instead of event, because of `toEventHandler` behavior.

https://github.com/unjs/h3/blob/0692656c59074c3900b92b203151590f4ab8e055/src/event.ts#L81-L91

**Comment by pi0** [comment]
Do you mind to open an issue in h3 regarding `toEventHandler`?
