### ISSUE TITLE
Add Deno to runtime list

### ISSUE THREAD

**Issue by kalwabed** [unjs/nitro#1898]
### Describe the feature

To avoid confusion for new users, I have a suggestion that Deno be added as part of the runtime list like Bun and Node.js. 
So there will be two _Deno_, one Deno in the runtime list, and the other Deno Deploy in the provider list replacing the current one.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
PR welcome! (we recently added runtime section and indeed it seems a reasonable thing to do)
