### ISSUE TITLE
Support sending stream

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#19]
h3 support: https://github.com/unjs/h3/pull/68 is landed for Node.js compatible environments.

We might need to improve unenv mocks as well to universally make stream support available.

Currently waiting for [h3 Event API](https://github.com/unjs/h3/issues/73) to be completed and especially with [Event class](https://github.com/unjs/h3/issues/81) we can leverage native web API for sending streams.

**Comment by enemy-senator92** [comment]
Hi there!

Can you please tell me if there are plans to improve this direction?

**Comment by theartkod** [comment]
same question, any update here? @danielroe

**Comment by Hebilicious** [comment]
Looks like we could use https://github.com/ardatan/whatwg-node to support stream everywhere easily (or improve unenv/node-native-fetch)

**Comment by pi0** [comment]
Moving to https://github.com/unjs/nitro/issues/1327
