### ISSUE TITLE
RouteRules CORS option supports customizing preflight request's response status code

### ISSUE THREAD

**Issue by Logosww** [unjs/nitro#1909]
### Describe the feature

  When routeRules' `cors` option set to `true`, response headers of those requests to this route will automaticly add `Access-Control-Allow-Headers: *`, `Access-Control-Allow-Methods: *` and `Access-Control-Allow-Origin: *` to support CORS.

  However, preflight requests which are send in broswer will be automaticly responsed with statusCode `404`, and then cause CORS block error:
`Access to fetch at 'xxx' from origin 'xxx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

![image](https://github.com/unjs/nitro/assets/87473526/778f3201-45f5-4091-afae-3a02f849f1f0)
  So I wish to customize response status to those preflight requests to make it a ok status(2XX) so that I can pass the CORS.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. Can you please provide a reproduction? 🙏🏼

**Comment by jawndiego** [comment]
was this implemented? running into this issue at the moment
