### ISSUE TITLE
await plugins at startup

### ISSUE THREAD

**Issue by huang-julien** [unjs/nitro#1915]
### Describe the feature

Hello :wave: 

https://github.com/unjs/nitro/blob/f412af16b358e941e90cb222586be1e6a77066b7/src/runtime/app.ts#L196

When using nitro plugins, some of them can be async. Since plugins are here to modify/setup nitro, would this make sense to await for all plugins before starting nitro like awaiting nuxt plugins before rendering the nuxt app ? 

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi, thanks for making the suggestion. It would be nice indeed but a tricky thing to do. But ideally (also for Nuxt) it is usually better to use lazy-loaded async composables that are initialized in paths that need them to be preferred over plugins.

Let's track in #915
