### ISSUE TITLE
When prerender crawlLinks set to true, the nuxt device module always returns true for isDesktop

### ISSUE THREAD

**Issue by haidertm** [unjs/nitro#1917]
### Environment

I'm using node latest version v20.9.0

tried on Nuxt version 3.8.1 and 3.6.5

Following is the configuration i have in nuxt.config.ts file.

```
  nitro: {
    prerender: {
      crawlLinks: true,
    },
    compressPublicAssets: true,
  },
  ```
  
  

### Reproduction

when i install nuxt device module
https://nuxt.com/modules/device

and i set crawlLinks to true

```
    prerender: {
      crawlLinks: true,
    },
```

### Describe the bug

it works fine, until i apply the nitro configurations and set crawlLinks to true.

as when crawlLinks are true, and i refresh the homepage, the device module always returns `isDesktop` to true in ssr.

So initially when page is rendered from ssr, its always true for isDesktop, even thou i am using mobile device.

Only when i set `crawlLinks: false` crawlLinks to false, then i get no issue in ssr.

possibly for crawllinks when the pages are generated, it does not has any device context.

**Comment by manniL** [comment]
When you crawl and prerender sites during build time, this behavior makes sense, as no mobile user agent will be detected when building your app. Initially, the device is set to a desktop device then.

The best chance to change this by doing "actual" SSR, not generating the page during build time - or - checking the values only on the client-side and react to them.
