### ISSUE TITLE
 When assets metadata is not found，scanning for real assets as fallback

### ISSUE THREAD

**Issue by markthree** [unjs/nitro#1918]
### Environment

node-server: v18.18.0

### Reproduction

null

### Describe the bug

Metadata lookups are very nice and allow us to know if there is a file without having to rescan the directory.

However, in a traditional node-server standalone service, sometimes we might want to upload file to assets to make it accessible to users, and this won't work.

Maybe we can scan the files as a fallback to solve this problem.

### Additional context

https://github.com/unjs/nitro/blob/a3120b6acfcf67343e411e51107c45d6ccf432b8/src/runtime/static.ts#L55

ref: https://nitro.unjs.io/guide/assets#public-assets

```[tasklist]
### Tasks
```

**Comment by manniL** [comment]
@markthree You'd use something like `server assets` instead then ☺️

**Comment by markthree** [comment]
> @markthree You'd use something like `server assets` instead then ☺️

Thank you, but it doesn't take effect after building 

my code ↓
```js
const storage = useStorage("assets:foo");

// routes/[id].js
export default defineEventHandler(async (e) => {
  const id = getRouterParam(e, "id");

  await storage.setItemRaw(id, id + "txt");

  return await storage.getItem(id);
});
```

```js
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

export default defineNitroConfig({
  serverAssets: [{
    baseName: "/foo",
    dir: resolve(dirname(fileURLToPath(import.meta.url)), "assets/foo"),
  }],
});
```

**Comment by markthree** [comment]
I wrote a `nitro module` to support this functionality → [nitro-public-module](https://github.com/markthree/nitro-public-module/)

If anyone needs can install and configure 👇

```shell
npm i nitro-public-module -D
```

> nuxt

```ts
// nuxt.config.ts
import nitroPublic from "nitro-public-module";

export default defineNuxtConfig({
  nitro: {
    modules: [nitroPublic()],
  },
});
```

> nitro

```ts
// nitro.config.js
import nitroPublic from "nitro-public-module";

export default defineNitroConfig({
  modules: [nitroPublic()],
});
```
Everything will be handled automatically 🥰
