### ISSUE TITLE
`useStorage().getKeys()` returns different result for dev and build (no `build:`, `root:` and `src:` in prod)

### ISSUE THREAD

**Issue by enkot** [unjs/nitro#1941]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zcakjn?file=server%2Froutes%2Ftest.ts

### Describe the bug

Go to the `/test` endpoint in dev and build:
- dev -  there are keys in the list
- build - the list is empty

### Additional context

Similar issue https://github.com/unjs/nitro/issues/374

**Comment by pi0** [comment]
Hi dear @enkot. This is an expected behavior indeed. `build:`, `root:` and `src:` mounts are only in dev (auto configured by nitro using `devStorage` configuration).

If you need a persistent data storage, you can manually mount a new one or use `useStorage('data')`.
