### ISSUE TITLE
nitro docs page bugged

### ISSUE THREAD

**Issue by xalteropsx** [unjs/nitro#1959]
### Environment

latest

### Reproduction

https://nitro.unjs.io/guide/getting-started

### Describe the bug

![image](https://github.com/unjs/nitro/assets/103671642/b1b6f3c7-7f44-4ff7-9ae6-000552b40b5f)
tested on brave firefox and edge

**Comment by pi0** [comment]
Thanks for reporting docs should be up again (https://github.com/unjs/nitro/commit/b4386f8cea471bcdd2dc4f50202a45347e25919f)
