### ISSUE TITLE
Documentation website is broken https://nitro.unjs.io/

### ISSUE THREAD

**Issue by kedniko** [unjs/nitro#1960]
### Environment

https://nitro.unjs.io/

### Reproduction

https://nitro.unjs.io/

### Describe the bug
![image](https://github.com/unjs/nitro/assets/42846752/2a78eb07-0ddd-460b-a173-fee4291a50fb)

**Comment by danielroe** [comment]
let's track in https://github.com/unjs/nitro/issues/1959

**Comment by pi0** [comment]
Docs should be up again, thanks for reporting! (https://github.com/unjs/nitro/commit/b4386f8cea471bcdd2dc4f50202a45347e25919f)
