### ISSUE TITLE
Docs: How to use Cache API in cloudflare module worker with nitro

### ISSUE THREAD

**Issue by ManasMadrecha** [unjs/nitro#1982]
### Describe the feature

Currently, nitro offers really easy to use Cloudflare module preset. However, the Nitro docs are a little incomplete regarding cache strategies and their method of adoption.

It would be great if some documentation is added regarding the same.

## Additional context

https://developers.cloudflare.com/workers/learning/how-the-cache-works/#edge-versus-browser-caching 

> For requests where Workers are behaving as middleware (that is, Workers are sending a subrequest via fetch) it is recommended to use fetch. This is because preexisting settings are in place that optimize caching while preventing unintended dynamic caching. For projects where there is no backend (that is, the entire project is on Workers as in Workers Sites) the Cache API is the only option to customize caching.

If the entire nitro project is a worker (using cloudflare-module preset), then is it not possible to use Fetch API, as mentioned in above link? 😳

- If possible, then how to use the `cf` inside `fetch`  `cf` with `$fetch` and not plain `fetch`? How to simply set the response of a router handler to cache not just in browser but also on the Edge? This link https://developers.cloudflare.com/workers/examples/cache-using-fetch/ uses Request; how to get this Request in a route handler in nitro?

- If not possible (but can use Cache API), then how to actually use the Cache API? Using `const cache = caches.default` in any route handler throws the error (in dev) that caches is undefined. And in prod, even if this error goes away, how to parse the request and `put` it into the Cache API?

Any help will be much appreciated 😊🙏🏻

**Comment by pi0** [comment]
Hi and thanks for suggestion. Moving to https://github.com/unjs/nitro/issues/2124 for followup 👍🏼

**Comment by joebailey26** [comment]
I've used [https://github.com/james-elicx/cf-bindings-proxy](https://github.com/james-elicx/cf-bindings-proxy) which has worked well for caching.

```
import { cacheApi } from 'cf-bindings-proxy'

export default defineEventHandler(async (event: H3Event) => {
  const cache = await cacheApi()

  const cacheKey = new Request(new URL(event.node.req.url, `http://${event.node.req.headers.host}`), event.node.req)

  const cachedResponse= await cache.match(cacheKey)
  if (cachedResponse) {
    return cachedResponse
  }

  // Create a response
  const response = new Response()

  event.waitUntil(await cache.put(cacheKey, response.clone()))
})

**Comment by pi0** [comment]
You can use https://github.com/pi0/nitro-cloudflare-bindings too btw for making bindings to work.

**Comment by cosbgn** [comment]
@pi0 could you share a minimal example on how would this work using the `nitro-cloudflare-binding` module?
[It's been asked also here](https://github.com/nitrojs/nitro-cloudflare-dev/issues/52)
