### ISSUE TITLE
Clearing Vercel Cache After Setting isr: true in Nuxt's routeRule Configuration

### ISSUE THREAD

**Issue by Vi-jay** [unjs/nitro#1984]
### Describe the feature

Hello,

I am currently working on a Nuxt.js project and have set `isr: true` in the `routeRule` configuration. However, I am facing an issue with Vercel's cache not being cleared after this setting.

Could anyone provide guidance on how to clear Vercel's cache when `isr: true` is set in Nuxt's `routeRule` configuration? Any help would be greatly appreciated.

Thank you.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Jamiewarb** [comment]
Did you solve this?

**Comment by pi0** [comment]
You might want to use on-demand revalidation: https://nitro.unjs.io/deploy/providers/vercel#on-demand-incremental-static-regeneration-isr
