### ISSUE TITLE
Inconsistent naming of presets?

### ISSUE THREAD

**Issue by cjpearson** [unjs/nitro#1999]
### Environment

node v20.10.0, nuxt@3.8.2, nitropack@2.8.1

### Reproduction

`NITRO_PRESET=vercel_edge yarn nuxt build`

### Describe the bug

For building for Vercel Edge functions, [the documentation](https://nitro.unjs.io/deploy/providers/vercel#vercel-edge-functions) says to use the preset `vercel_edge`. 

But when ISR is enabled in the route rules, the route config seems to be incorrect when I use that preset. I think because of [this line](https://github.com/unjs/nitro/blob/bd5e14dbc71b28ad571162ba477ac5e0e6fa68c8/src/presets/vercel.ts#L230). Changing to `NITRO_PRESET=vercel-edge` seems to fix the issue, but I'm not sure if that will cause different problems. Could you tell me which format is correct?

**Comment by pi0** [comment]
Both cases are accepted.
