### ISSUE TITLE
Can't access useRuntimeConfig in custom npm package

### ISSUE THREAD

**Issue by imcm7** [unjs/nitro#2009]
### Environment

Nuxt 3

### Reproduction

Can't import useRuntimeConfig
// import { useRuntimeConfig } from 'nitropack/dist/shared/nitro.0456456.mjs'; ///dist/shared/nitro.045645350';
// import { useRuntimeConfig } from '#internal/nitro';
// import { useRuntimeConfig } from  'nitropack/dist/config';
// import { useRuntimeConfig } from '#internal/nitro';

### Describe the bug

I can, but no reason

```
    const nitroAsyncContext = getContext<any>('nitro-app', {
      asyncContext: true,
      AsyncLocalStorage: AsyncLocalStorage,
    });

    console.log(
      // useRuntimeConfig(), // not work
      process.env, // nothing
      nitroAsyncContext.use().event // nothing, just event without runtime config, it is not cached by attaching to event at that momenthttps://github.com/unjs/nitro/blob/5ead36f78eb54ab94b01c48f6da6e0ecf20a79fa/src/runtime/config.ts#L33
    );
    ```

**Comment by imcm7** [comment]
If i put code from mu npm package in nuxt project and import some functions from it and call that functions all work, because of auto import

**Comment by imcm7** [comment]
Or to make it like a nuxt module, https://github.com/sidebase/nuxt-auth/blob/31717715f1e8c3748139e54f5c5daa8284bcc2af/package.json#L19

But I don't need to make a nuxt module. I need only to access nuxt config in some way.

**Comment by imcm7** [comment]
Cannot find module 'nitropack/runtime/config' or its corresponding type declarations.

```
import {
  useRuntimeConfig
} from  'nitropack/runtime/config'; // 'nitropack/dist/runtime/config'; 
```



```
"type": "module",
  "exports": {
    ".": {
      "types": "./types.d.ts",
      "import": "./dist/index.mjs"
    },
    "./config": {
      "types": "./dist/config.d.mts",
      "import": "./dist/config.mjs"
    },
    "./cli": {
      "types": "./dist/cli/index.d.mts",
      "import": "./dist/cli/index.mjs"
    },
    "./runtime/*": {
      "types": "./dist/runtime/*.d.mts",
      "import": "./dist/runtime/*.mjs"
    },
    "./dist/runtime/*": {
      "types": "./dist/runtime/*.d.mts",
      "import": "./dist/runtime/*.mjs"
    },
    "./package.json": "./package.json"
  },
  "main": "./dist/index.mjs",
  "types": "./types.d.ts",
  ```

**Comment by imcm7** [comment]
```
import {
  useRuntimeConfig
} from  'nitropack';
```

Module '"nitropack"' has no exported member 'useRuntimeConfig'.

**Comment by itpropro** [comment]
If you want to use parts of Nitro (or of Nuxt in this case) you should do that in an event handler or a utility and avoid using it in ambient global contexts.
For Nuxt you can achieve this by creating a plugin or a module, in Nitro, you can just use a util for example. You don't need to put your npm packages logic in there, just consider to hand over the configs that you need in your package in a more general way.
That way you could just create a Nitro util, get the setting `const yourSetting = useRuntimeConfig().yourSetting` there and hand it over to your  package.

```
// utils/yourPackage.ts
import { customFunction } from 'customPackage'
export function useCustomPackage() { 
  const yourSetting = useRuntimeConfig().yourSetting
  return {
    customFunction(yourSetting)
  }
}

// routes/index.ts
export default defineEventHandler(() => {
  const customResult = useCustomPackage()
  return { customResult }
})
```

**Comment by itpropro** [comment]
Did the information help you to achieve your goal @imcm7 ? If yes, please consider closing this issue.

**Comment by imcm7** [comment]
No, I need to use nitro in library not library in nitro.

**Comment by pi0** [comment]
For performance reasons, nitro avoids running auto imports in libraries within `node_modules`. You need to:

- Import `{ useRuntimeConfig }` from `#imports`
- Add your library path to `build.transpile` (this is a nuxt config and it is planned to be automatically added in the future)
