### ISSUE TITLE
Missing backslash in index.js file generated by iis preset

### ISSUE THREAD

**Issue by jrojko** [unjs/nitro#2012]
### Environment

Node.js v20.9.0, Nuxt 3.8.2, Nitro 2.8.1

### Reproduction

npx nuxi build --preset=iis_node

### Describe the bug

The generated file index.js in the .output directory has a syntax error caused by a missing backslash (escape character) on this line:

`  if (process.env.PORT.startsWith('\')) {`

This comes from src/presets/iis.ts, line 33 which should be changed to 

`   if (process.env.PORT.startsWith('\\\\')) {`

**Comment by manniL** [comment]
Was fixed via https://github.com/unjs/nitro/pull/2020
