### ISSUE TITLE
Document site (nitro.unjs.io) broken and doesn't display content

### ISSUE THREAD

**Issue by ilharp** [unjs/nitro#2028]
### Environment

Windows / Android

### Reproduction

<https://nitro.unjs.io>

### Describe the bug

Document site (nitro.unjs.io) broken and doesn't display content. The navigation bar and TOC still work fine.

**Comment by guylil** [comment]
Same with Firefox

**Comment by guylil** [comment]
@Hebilicious 
Sorry for the tag but the docs site does not display content

**Comment by guylil** [comment]
Also I can confirm it worked yesterday

**Comment by BalajiSriraman** [comment]
Yep! page is down in multiple locations :( 

@pi0

**Comment by Drswith** [comment]
ops !!!! lol!!!

**Comment by wotschofsky** [comment]
Issue was introduced in 595ad739f878a5c163242ac4978adbcf23d02700 and therefore with the upgrade of `@nuxt/content` from 2.9.0 to 2.10.0

In the meantime, the docs are still available at https://github.com/unjs/nitro/tree/main/docs/content

**Comment by pi0** [comment]
Docs are fixed back (https://github.com/unjs/nitro/commit/0c216cf3e317a926c221324e9abc2da5dc29125a) thanks for notice ❤️  such a shame that this happened multiple times now due to lockfile issues.
