### ISSUE TITLE
Netlify edge preset does not upload public directory

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/nitro#2032]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

- Create a new project using npx nuxi init nuxt-netlify-app
- Deploy to netlify, add NITRO_PRESET=netlify-edge in env
- Open the deployment

You can also take a look at this website (https://dynamic-taiyaki-ead18e.netlify.app/), from this repo https://github.com/barbapapazes/nuxt-netlify-edge. If you take a look at the network tab, the favicon is not loaded.

![image](https://github.com/unjs/nitro/assets/45267552/0bb5c07b-8ad8-42d5-8d64-78fae21e93de)

### Describe the bug

Hello,

The public directory is not uploaded using the preset netlify-edge. As you can see in the picture, There is no public directory.

![image](https://github.com/unjs/nitro/assets/45267552/8d9676c4-0b9a-4038-9fd7-f889cbf00890)

**Comment by Barbapapazes** [comment]
We have to set the dist folder as "dist" but by default (on netlify ui), it's ".nuxt/dist". I will create a PR to update documentation to avoid this issue.

**Comment by manniL** [comment]
This is strange 🤔
I've seen this in a project recently too though I thought it was misconfigured. We maybe should also notify Netlify as this should not be the default behavior 🙈

**Comment by Barbapapazes** [comment]
> This is strange 🤔
> I've seen this in a project recently too though I thought it was misconfigured. We maybe should also notify Netlify as this should not be the default behavior 🙈

Yes! I agree to notify netlify but I do not have any contact! 😄

**Comment by pi0** [comment]
For reference, Netlify only does change the default (incorrectly) for Nuxt projects (auto detected).
