### ISSUE TITLE
any graphql server/middleware support ?

### ISSUE THREAD

**Issue by jahir9991** [unjs/nitro#2055]
### Describe the feature

any graphql server/middleware support ?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by itpropro** [comment]
You can easily setup any GraphQL server with Nitro. I created a minimal example for GraphQL Yoga (remember to open in new tab in Stackblitz for full visual support): https://stackblitz.com/edit/unjs-nitro-yoga

You can test is under `/graphql` and use a query like this:

```graphql
query MyQuery {
  hello
  me {
    username
  }
}
```

Set the headers to any user in the headers setting to see the query results change:

```json
{
  "user": "Jane Doe"
}
```
