### ISSUE TITLE
@ alias does not work

### ISSUE THREAD

**Issue by Aareksio** [unjs/nitro#2058]
### Environment

nitropack@2.8.1
nitropack-nightly@2.9.0-28406650.c8e8549

### Reproduction

https://stackblitz.com/edit/github-bjch62

### Describe the bug

Aliases (`~`, `@`) are not working in new nitro project. Should not [this code](https://github.com/unjs/nitro/blob/main/src/rollup/config.ts#L341-L353) enable them? As per [PR comment](https://github.com/unjs/nitro/pull/1533#issuecomment-1666938679) it should work. But it does not seem to.

### Additional context

- both `@` and `~` do not provide types
- `~` seems to work as alias, `@` does not, see logs

### Logs

```sh
"@/import-me" is imported by "routes/index.ts", but could not be resolved – treating it as an external dependency.
```

**Comment by manniL** [comment]
StackBlitz link is a 404

**Comment by manniL** [comment]
Repro: https://stackblitz.com/edit/github-qytsgh?file=routes%2Findex.ts

Apparently `@//path-to-file.js` works.

**Comment by Aareksio** [comment]
Sorry, cut one character from stackblitz link. Fixed.
<img width="533" alt="Screenshot 2024-01-08 at 17 52 25" src="https://github.com/unjs/nitro/assets/11166786/7df0b5fa-c1bd-4d28-8403-d3ed41790a79">

Apart from `alias`, `tsconfig.json` must be adjusted. `~/path-to-file.ts` works, but is not recognized by typescript.

**Comment by kspace-trk** [comment]
Hi. Is this issue likely to be closed by this PR?
https://github.com/unjs/nitro/pull/2318

**Comment by Aareksio** [comment]
Seems to still be present in nightly build:
https://stackblitz.com/edit/github-bjch62-15nb1v

```
"@/import-me" is imported by "routes/index.ts", but could not be resolved – treating it as an external dependency.
```

To be precise:
- 🟩 both `@` and `~` provide types now, **this has been fixed** 
- 🟥 `~` seems to work as alias, `@` does not, **this is still broken**

**Comment by pi0** [comment]
Please always prefer `~` for aliases. `@` can be always tricky and conflicting with node package namespaces and an unreliable alias method we kept for historic compatibility reasons.
