### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by angel-luis** [unjs/nitro#2061]
### Environment

Node: v20.9.0
OS: MacOS (Darwin 23.2.0 arm64)
Also tried with: Cloudflare Workers

### Reproduction

`bunx giget@latest nitro nitro-app`
`bun install`

Add route rules to `nitro.config.ts`:
```
routeRules: {
		"/**": {
			cors: true,
			headers: { "access-control-allow-origin": "https://google.com" },
		},
	},
```

`bun dev`

### Describe the bug

Tested it with any API request. It will take and reply to the request. Also tried to create a route API, and point to `/api/**`in the `routeRules`, and still not working.

Also tried uploading it to Cloudflare Workers with Wrangler, and I still can make requests. Is supposed to only accept requests from Google domain.

I need to configure something else? I'm guided by the documentation, and I only have seen CORS configuration in that part. I've seen functions like `appendCorsHeaders` and I've think to create a plugin to use this function in every request, but then, the `routeRules` it has non sense.

**Comment by itpropro** [comment]
Hi,
can you please provide a minimal reproduction for example on stackblitz?

**Comment by itpropro** [comment]
I was not able to reproduce that with a stock instance of Nitro. Feel free to reopen, if you can share a stackblitz/codesandbox/repo reproduction.
