### ISSUE TITLE
Cache is not invalidated in development when code change

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/nitro#2081]
### Environment

nitro@latest

### Reproduction

https://stackblitz.com/edit/github-1ye2kf?file=routes%2Findex.ts

### Describe the bug

Hello,

On the reproduction, start by fetching the `/` route. Then, change the value to another value. Refresh. I expect to have a different time but that is not the case. This issue is annoying when cache is an important part of the application since it force me to remove the .nitro/cache folder after every code modification and before refreshing the page. This can easily leads to unwanted behavior such a wanted change in data that does not occur because the cache is not invalidated.

**Comment by pi0** [comment]
Hi. This is because in your example the variable is unused and treeshaken. ` return 4 + new Date();` editing 4 to 5 immediately updates.

However it is only working for the function code itself.

I highly recommend to split your logic into multiple small catchable utils and fine-control the caching configuration for development. this is best method to keep a balance.

**Comment by Barbapapazes** [comment]
Ooooh, this is very interresting to note that code is treeshaken in dev mode.

**Comment by manniL** [comment]
Linking https://github.com/unjs/nitro/issues/649 here ☺️

**Comment by pi0** [comment]
(i guess you might wanted here in other issue? 😅 i guess clearly explained it here already..)

**Comment by manniL** [comment]
@pi0 Just to double check:

```ts
// endpoint.get.ts
import { arr } from '../arr';

export default defineCachedEventHandler(() => arr, { maxAge: 0 });
```

```ts
// arr.ts -> change something here will not trigger
export const arr = [1, 2, 3, 4, 5];
```

does not update because the cache busting in dev only works for the code *inside* the event handler file, not for imported files or dependencies?

And

```ts
// endpoint.get.ts
const arr = [1, 2, 3, 4, 5];

export default defineCachedEventHandler(() => arr, { maxAge: 0 });
```

Works fine because of the mentioned reason above?

**Comment by pi0** [comment]
> However it is only working for the function code itself.

yes I mentioned that fact :) In dev, you should set a caching strategy that fits the usecase. Nitro cannot do magic to do cache HMR in nested code (well it can but with expensive code instruments)

**Comment by pi0** [comment]
> So, you mean that in dev, you e.g. wouldn't cache at all (in this case)?

Really depends on the case and project IMO. I would only disable the cache when developing that particular method using `$development` because in larger project, when a small unit does not needs frequent updates, making it catchable improves dev perf.
