### ISSUE TITLE
Firebase deploy Failure on MacBook M1: Incorrect Platform Detection for @css-inline/css-inline-darwin-arm64

### ISSUE THREAD

**Issue by davies-maina** [unjs/nitro#2096]
### Environment

node version: 18
nitro version: 2.8.1

nitro: {
    preset: 'firebase',
    firebase: {
      nodeVersion: '18',
      gen: 2,
      httpsOptions: {
      region: 'us-central1',
      maxInstances: 100,
      },
    },

### Reproduction

1. Include @css-inline/css-inline-darwin-arm64@0.12.1 in the project's dependencies.
2. Attempt to build and then deploy the application on a MacBook M1.

### Describe the bug

I am experiencing a build failure when attempting to deploy my application from a MacBook M1 (ARM64 architecture) to Firebase Hosting. Despite using an ARM64-based MacOS, the npm package @css-inline/css-inline-darwin-arm64@0.12.1 is being flagged as incompatible, with npm incorrectly identifying my environment as Linux x64.

### Additional context

- This issue is blocking deployment to Firebase Hosting

- By removing packages with 'darwin' in their names from my dependencies in the **_.output/server/package.json_**, the build and deployment process completes successfully. 

### Logs

Build failed with status: FAILURE and message: npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @css-inline/css-inline-darwin-arm64@0.12.1: wanted {"os":"darwin","cpu":"arm64"} (current: {"os":"linux","cpu":"x64"})
npm ERR! notsup Valid os: darwin
npm ERR! notsup Actual os: linux
npm ERR! notsup Valid cpu: arm64
npm ERR! notsup Actual cpu: x64

**Comment by harlan-zw** [comment]
Are you using Nuxt OG Image? I haven't done much testing with it and Firebase, likely I need to prefer the wasm build

**Comment by Chuiantw1212** [comment]
Same issue here. A workaround is deleting the  attribtes from pacakge-lock.json
![image](https://github.com/unjs/nitro/assets/10844438/10b215af-4467-46f6-939b-d3748c69e09b)

**Comment by harlan-zw** [comment]
Thank you, yes this is from nuxt-og-image, I've make a duplicate issue on that repo. (https://github.com/nuxt-modules/og-image/issues/170)

I think this one can be closed as I don't think Nitro itself can solve this.
