### ISSUE TITLE
Custom preset

### ISSUE THREAD

**Issue by imcm7** [unjs/nitro#2100]
### Environment

-

### Reproduction

https://github.com/unjs/nitro/issues/1373

### Describe the bug

If I make a custom preset it run only on build command?
In dev it is not used?

**Comment by markthree** [comment]
From what I understand, yes.

The preset only works in production, development is a node environment

**Comment by imcm7** [comment]
Ugly

**Comment by imcm7** [comment]
Very limited framework. With such limitations it can be used only for hello world and developers personal web pages.
