### ISSUE TITLE
node os cpus is POSIX-only: on Windows it is 0

### ISSUE THREAD

**Issue by userquin** [unjs/nitro#2103]
### Environment

Nuxt 3.9.1 with Nitro 2.8.1 and Node 20.10.0 LTS 

Linked: https://github.com/nuxt/nuxt/issues/25360

### Reproduction

Request from @pi0 in nuxt discord server.

NA

### Describe the bug

From Nuxt discord insiders channel https://discord.com/channels/473401852243869706/880750893635633182/1198554904134946846:

node os cpus is POSIX-only

### Additional context

In Nuxt `packages/nuxt/src/core/nitro.ts` module:

![imagen](https://github.com/unjs/nitro/assets/6311119/b2f0c111-c334-47e8-914b-592f62c12247)

Node os.d.ts jsdocs:

![imagen](https://github.com/unjs/nitro/assets/6311119/d202685b-1c10-419c-ade9-3189f72848ff)

**Comment by pi0** [comment]
https://github.com/nuxt/nuxt/issues/25360#issuecomment-1902682418
