### ISSUE TITLE
@builder.io/sdk-vue runtime is not honored on Vercel

### ISSUE THREAD

**Issue by 20x-dz** [unjs/nitro#2111]
### Environment

Nuxt 3.9.3, Vercel default (nodejs 18), nitropack 2.8.1

### Reproduction

When building a minimal Nuxt3 project integrating the builder.io toolkit and deploying it on vercel, the output does not use the `vercel-light` edge export defined in the package's `package.json`.

See https://github.com/20x-dz/builder-vue-test for a simple project and https://builder-vue-test.vercel.app/ for the current output.

### Describe the bug

After deploying to vercel, the package export for the `edge-light` environment is not used, but the default `node` environment is used instead, resulting in the following error: `Cannot find module 'isolated-vm' Require stack: - /var/task/node_modules/@builder.io/sdk-vue/lib/node/index.29fcda33.js`

As mentioned in https://github.com/BuilderIO/builder/issues/2933#issuecomment-1904494105 adjusting the import to use the `edge` export directly fixes this issue (`import { Content, fetchOneEntry, isPreviewing } from "@builder.io/sdk-vue/edge";`), but then breaks when developing locally.

**Comment by pi0** [comment]
Hi. Please note that `edge-light` condition should be used for vercel_edge preset (not lambda which is default). For this, you might need to set `NITRO_PRESET=vercel_edge` environment variable or locally use `build --preset vercel_edge`

**Comment by 20x-dz** [comment]
Thx @pi0 . I am using `NITRO_PRESET=vercel` because `NITRO_PRESET=vercel_edge` fails building with sentry (https://github.com/getsentry/profiling-node/issues/170). I just quoted `edge-light` because it was mentioned in the [linked builder io PR](https://github.com/BuilderIO/builder/issues/2933#issuecomment-1904494105).

**Comment by pi0** [comment]
These are two completely different runtimes:

- `vercel`: Uses AWS Lambda and Node.js (resolving libraries with `node` condition)
- `vercel_edge`: Uses a Worker to run your code in edge (resolving libraries with `edge-light`

One deployment/project can be against one of these. From your requirements, it seems you both need Node.js for sentry profiling and builder.io with `edge-light` conditions. 

Also I notice that your reproduction the SDK is imported `pages/[...app].vue` (it is bundled by Vite and Nuxt not Nitro directly).

Have you tried to update your import to `@builder.io/sdk-vue/edge`?

**Comment by 20x-dz** [comment]
> Have you tried to update your import to `@builder.io/sdk-vue/edge`?

Yes, that works fine. On Vercel. Locally (running `npm run dev`, so node runtime I would guess?) this does not work.

From what I understand, using the import `@builder.io/sdk-vue` should resolve to the correct runtime automagically depending on the context given the `exports` defined in `package.json`, shouldn't it?

**Comment by pi0** [comment]
Yes it should work and i ever a library author, I would use main subpath export for universal builds (not a Node.js dependent variant).

Thanka for confirming that `@builder.io/sdk-vue/edge` works fine.

I think there is nothing much for us to do (vercel is a node preset and they never request any different condition that I am aware of. if there is one, both Nitro and libraries can use them. Best luck ;)

**Comment by 20x-dz** [comment]
Thank you very much for your swift and detailed reponses. Very much appreciated! 🙏
