### ISSUE TITLE
Custom Response Handler (Javascript)

### ISSUE THREAD

**Issue by recoiladam** [unjs/nitro#2117]
Hello! We are using h3 with Nuxt 3 and would like to use a custom response handler to create a custom response object. I have been all over the documentation, Google, and StackOverflow but for the life of me, I cannot figure this out. I did find one issue here that was related to Typescript and as much as we tried to convert it to Javascript, we have failed every time. Any help would be greatly appreciated.

Essentially, I would like to create a file in `server/plugins` or `server/middleware` that uses the Nitro `beforeResponse` hook to format the response object a specific way (I assume this is the best approach). The following code does successfully run after my requested endpoint but I cannot figure out from here how to modify the response object itself:

```
export default defineNitroPlugin((nitro) => {
  nitro.hooks.hook('beforeResponse', async (event, { body }) => {
    console.log('-------------------- custom response plugin: start --------------------')
    console.log('-------------------- custom response plugin: stop --------------------')
  })
})
```

Also, there seems to be quite a few features missing from `h3` to be considered a modern framework such as logging. I prefer to use Winston but I am unable to figure out how to use Winston in a plugin so that I can log all requests. Is this even possible?

Thank you.

**Comment by pi0** [comment]
Hi dear @recoiladam thanks for reaching out and I am sorry that you are having a hard time figuring things out. We are aware of lack of enough docs and trying to make them better.

h3, is more a minimal server layer that focuses on one task of being a server. Usually, it is better to rely on higher-level features (Nitro) for this.

I have made an (JS) example that both use Winston logger and response modification:

https://stackblitz.com/edit/unjs-nitro-nvhk1f?file=plugins%2Flogger.mjs&title=Nitro%20Starter

If you like to also hook into Nuxt level SSR hooks for response modification, here is another example:

[pi/blob/main/server/plugins/timing.ts
](https://github.com/pi0/nuxt-on-pi/blob/main/server/plugins/timing.ts)


Please let me know if you have any other questions or want to do something else and can't figure out how.

**Comment by recoiladam** [comment]
> Hi dear @recoiladam thanks for reaching out and I am sorry that you are having a hard time figuring things out. We are aware of lack of enough docs and trying to make them better.
> 
> h3, is more a minimal server layer that focuses on one task of being a server. Usually, it is better to rely on higher-level features (Nitro) for this.
> 
> I have made an (JS) example that both use Winston logger and response modification:
> 
> https://stackblitz.com/edit/unjs-nitro-nvhk1f?file=plugins%2Flogger.mjs&title=Nitro%20Starter
> 
> If you like to also hook into Nuxt level SSR hooks for response modification, here is another example:
> 
> [pi/blob/main/server/plugins/timing.ts ](https://github.com/pi0/nuxt-on-pi/blob/main/server/plugins/timing.ts)
> 
> Please let me know if you have any other questions or want to do something else and can't figure out how.

Hello and thank you for the response, I greatly appreciate it! I was able to get Winston working and logging how I want it, thank you. Unfortunately, we are not able to modify the response. We are still learning Nuxt but have multiple production applications written in Vue 2 as well as Vue 3 and some mobile apps written in Ionic + Vue so we are no strangers to Vue or Vite but Nuxt is all new to us.

That all being said, what we are trying to do is modify the API `error response body` to make it the same as our normal response bodies. For example, a good response from our API would look something like this:

```
{
    "data": null,
    "message": null,
    "error": false,
    "status": 200
}
```

The current error response body looks something like this for a 401:

```
{
    "status": 401,
    "text": "Unauthorized"
}
```

It would be great if I could standardize all responses to look like my response object when the request is successful. Again, this is only for the API.

Based on the reading that we have done, it does not look like this is possible. We did notice that there was a reference to using the Mozilla response object found here: https://developer.mozilla.org/en-US/docs/Web/API/Response - If this is the case, then why can we not intercept the response to modify the body?

One last thing, why is it so difficult to set a proper response status code? For example, we have to use the following code everywhere we return some kind of an error:

```
setResponseStatus(event, 500, 'Internal Server Error')

const status = getResponseStatus(event)
const text = getResponseStatusText(event)

return { status, text }
```

This seems like a lot of code to write just to set the status code and text. I tried with the following code but it did not work:

```
throw createError({
  statusCode: 500,
  message: 'Internal Server Error,
})
```

In Express, you can simply do the following which set the status code to a 500 and an empty JSON object:

```
response.status(500).json({})
```

Being able to do something like this would help tremendously and would also fix the fact that we cannot modify the response body.

Any help is greatly appreciated.

Thank you!

**Comment by pi0** [comment]
Okay I have updated our [playground](https://stackblitz.com/edit/unjs-nitro-nvhk1f?file=routes%2Findex.js,routes%2Ferror.js,plugins%2Flogger.mjs,nitro.config.js,error-handler.js,routes%2Fapi.js&title=Nitro%20Starter) with both.

If you need to also modify json responses universally (so all API endpoints that return an object to be wrapped to an standard object, you can use `beforeResponse` hook to modify them also for objects too) -- I added to example

For error handling, `throw createError` is the right way to do and it should work. Only consider that error handling is a different path. You can catch any thrown error using `error` hook if you need to modify it or add any more context to it.

Also if you need to make a custom error response that also follows with your desired convention globally across project, you probably want to override global `errorHandler` (it can be configured using `nitro.errorHandler` in `nuxt.config` as well). I have also added an example error handler in playground you can inspire.

**Comment by recoiladam** [comment]
Thank you for replying again and providing the examples, I greatly appreciate it. Unfortunately, we have abandoned Nuxt due to all the problems we are having and after during some additional reading we agree with others that Nuxt is just not ready for primetime production applications. Keep up the great work though and maybe one day it will be awesome! Thank you again.

**Comment by pi0** [comment]
Of course. I would be really interested though to see why you finally concluded this and what were the limitations you faced. Nuxt had been in production for 7 years and active development now. Wish you best as well anyway.
