### ISSUE TITLE
defineCachedFunction stopped working

### ISSUE THREAD

**Issue by kleinpetr** [unjs/nitro#2125]
### Environment

Hi,

once I've updated the latest Nitro version I am facing an issues with `defineCachedFunction()`

I am getting

```
[nuxt] [request error] [unhandled] [500] Cannot use 'in' operator to search for '__is_event__' in CZK
  at isEvent (project/node_modules/.pnpm/h3@1.7.1/node_modules/h3/dist/index.mjs:1164:25)  
  at <anonymous> (project/node_modules/.pnpm/nitropack@2.8.1/node_modules/nitropack/dist/runtime/cache.mjs:93:18)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
``` 

note: the CZK in the error is the query parameter I call within the server route. `/my-endpoint/CZK`

### Reproduction

TBD

### Describe the bug

TBD

**Comment by manniL** [comment]
Could you provide a reproduction?

**Comment by kleinpetr** [comment]
Yes I will later today. I just tried a chance if there was any breaking change, because it stopped working just by the upgrade ;)

**Comment by kleinpetr** [comment]
The minimal reproduction worked. So I had to completely remove pnpm.lock, node_modules and .nuxt and after the fresh install it is working now, so don't know if there was a hotfix, because I did it this cleanup week ago. But anyways it is working now. Closing
