### ISSUE TITLE
[DOCUMENTATION] - SQL Database - Config

### ISSUE THREAD

**Issue by go4cas** [unjs/nitro#2187]
### Environment

This section of the database docs seems to include a few errors:
```javascript
export default defineNitroConfig({
  database: {
    default: {
      driver: 'sqlite3',
      options: { name: "db" }
    },
    users: {
      driver: 'postgresql',
      url: "postgresql://username:password@hostname:port/database_name"
    }
  }
})
```

- `driver` should be `connector`
- `sqlite3` should be `sqlite` (using the `better-sqlite3` library)

### Reproduction

Link to docs page: https://nitro.unjs.io/guide/database

### Describe the bug

Minor config issues in docs.

**Comment by pi0** [comment]
Do you mind to make a PR to fix? 🙏🏼
