### ISSUE TITLE
Cookies are not available in defineCachedEventHandler

### ISSUE THREAD

**Issue by joemaylor** [unjs/nitro#2208]
### Environment

Node 20.11.1
Nitro 2.9.1 (Nuxt 3.10.3)

### Reproduction

https://stackblitz.com/edit/github-k1vndd?file=app.vue

### Describe the bug

When trying to retrieve a cookie value within `defineCachedEventHandler`, the cookies are not available. They are available within `defineEventHandler`. See repro.

### Additional context

My general use case is that I want to protect an endpoint so that only authenticated users can access it, and also want it to be cached for those users who can access it.

I already have a wrapper handler that works just for the authenticated use case:
```ts
import type { EventHandler, EventHandlerRequest } from 'h3'
import { verifyToken } from './verifyToken'

export function defineAuthenticatedEventHandler<T extends EventHandlerRequest, D>(handler: EventHandler<T, D>): EventHandler<T, D> {
  return defineEventHandler<T>(async (event) => {
    const user = verifyToken(event)
    event.context.user = user
    return handler(event)
  })
}
```

However when I try and do something similar for cached, I run into an error because I can't retrieve cookies from my event within `verifyToken()`

```ts
import type { EventHandler, EventHandlerRequest } from 'h3'
import type { CachedEventHandlerOptions } from 'nitropack'
import { verifyToken } from './verifyToken'

export function defineCachedAuthenticatedEventHandler<T extends EventHandlerRequest, D>(handler: EventHandler<T, D>, opts?: CachedEventHandlerOptions<T>): EventHandler<T, D> {
  return defineCachedEventHandler<T>(async (event) => {
    const user = verifyToken(event)
    event.context.user = user
    return handler(event)
  }, opts)
}
```

**Comment by pi0** [comment]
This is expected behavior. To avoid cache leakage, all incoming headers are dropped. You might use `varies` to opt-in but consider doing so, uses much more of your memory/cache storage as each request will be unique. Alternatively, you might use `shouldBypassCache`.

https://nitro.unjs.io/guide/cache#cached-event-handlers

**Comment by joemaylor** [comment]
Just noting here for anyone who runs into a similar use case, I ended up using `defineCachedFunction()` instead.

```ts
import { db } from '~/services/db'

const cachedDatabaseCall = defineCachedFunction(async () => {
  const data = await db.doStuff()
  return data
}, {
  // make sure to set `getKey` to return a constant value.
  // this ensures all requests get the same response.
  getKey: () => 'default',
  name: 'my-database-call'
})

export default defineAuthenticatedEventHandler(cachedDatabaseCall)
```

This means that anyone who isn't authenticated won't be able to retrieve the data, and all authenticated users share the same cached version.
