### ISSUE TITLE
bug: import functions from h3 with relative path, breaks with pnpm and no shamefully hoist

### ISSUE THREAD

**Issue by Louis9902** [unjs/nitro#2249]
### Environment

tried with `3.10.3(vite@5.1.6)`

### Reproduction

https://stackblitz.com/edit/github-bshclz?file=.nuxt%2Ftypes%2Fnitro-imports.d.ts%3AL128

### Describe the bug

Some declarations use just 'named' imports, which cause resolution problems when the project is restored with `pnpm` and no `shamefully-hoist` as the dependencies are not really present in the `node_modules`.

This includes files like `nitro-imports.d.ts (h3)` `nitro-nuxt.d.ts (nuxt/schema, h3, ...)` `nitro-config.d.ts (defu)` `nitro-routes.d.ts (nitropack)`

### Additional context

I partially tried to fix this in [PR 2207](https://github.com/unjs/nitro/pull/2207), but noticed since then that there are a lot more of occurrences. I find this strange because of [nuxt/nuxt 14146](https://github.com/nuxt/nuxt/issues/14146).
With this problem, I can not create server handler with `defineEventHandler` without type problems.

**Comment by danielroe** [comment]
This issue should be resolved in the latest version of Nuxt with https://github.com/nuxt/nuxt/pull/26085.

**Comment by pi0** [comment]
@danielroe what about nitro usage alone?

**Comment by danielroe** [comment]
Nitro usage alone is fine - the issue IIRC is that Nuxt is using nitropack types, but TS can't find nitropack .

**Comment by pi0** [comment]
thanks for confirming. then let's track for nuxt.

---

btw related discussion for nitro itself (direct import types don't work today with hosting): https://github.com/unjs/nitro/issues/2232
