### ISSUE TITLE
Enable environment-specific configuration

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/nitro#2254]
### Describe the feature

Hello,

In c12, you talk about environment-specific configuration but it's impossible to use it within the Nitro configuration.

For example, if I want to use the default `data` kv storage, it's easy but once I need to change it for production, I cannot just use `$production` but I have to rewrite `storage` and `devStorage`.

See https://github.com/unjs/website/pull/327#discussion_r1522157540

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for report.

1. This feature is actually supported by nitro but the types are not available (https://stackblitz.com/edit/unjs-nitro-starter-npqvdb?file=nitro.config.ts&title=Nitro%20Starter)
2. For Nuxt, the production and development env is hardcoded however it shouldn't be an issue with this, but supporting custom env needs https://github.com/nuxt/cli/issues/357

**Comment by Barbapapazes** [comment]
> Thanks for report.
> 
> This feature is actually supported by nitro but the types are not available ([stackblitz.com/edit/unjs-nitro-starter-npqvdb?file=nitro.config.ts&title=Nitro%20Starter](https://stackblitz.com/edit/unjs-nitro-starter-npqvdb?file=nitro.config.ts&title=Nitro%20Starter))

Ok, nice to know!
