### ISSUE TITLE
missing dep: ioredis "Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ioredis'"

### ISSUE THREAD

**Issue by McPizza0** [unjs/nitro#2265]
_@maintainers - please leave this issue open for people who are facing the issue.
I saw nothing and assumed the bug was elsewhere_

### FIX
please install ioredis into your nitro projects manually, it is no longer a dependency of unstorage

### Environment

node v20
pnpm v8.15
macos

### Reproduction

existing nitro project using redis with unstorage
run dev
error missing dep

### Describe the bug

yesterday a minor patch was made to unstorage that brought breaking changes: https://github.com/unjs/unstorage/releases/tag/v1.10.2
ioredis now needs to be installed manually

**if you are getting an error that ioredis is missing or not found, please install it manually in your project**

**Comment by pi0** [comment]
https://github.com/unjs/unstorage/issues/412

**Comment by pi0** [comment]
will be added as nitro peer dep in next release 👍🏼
