### ISSUE TITLE
Missing .d.mts files in /dist/runtime folder

### ISSUE THREAD

**Issue by zsilbi** [unjs/nitro#2277]
### Environment

nitropack@2.9.4
unbuild@2.0.0

### Reproduction

1. Build nitro 
2. Check /dist/runtime folder

### Describe the bug

In `package.json` there are exports defined for the `runtime` folder:

```json
    "./runtime/*": {
      "types": "./dist/runtime/*.d.mts",
      "import": "./dist/runtime/*.mjs"
    },
    "./dist/runtime/*": {
      "types": "./dist/runtime/*.d.mts",
      "import": "./dist/runtime/*.mjs"
    },
```

The `.d.mts` files are missing.

### Additional context

If I add (for example) `"src/runtime/timing"` to the `entries` in `build.config.ts`, it works as expected, the `dist/runtime/timing.d.mts` file is created.

**Comment by pi0** [comment]
it might be an issue but please reopen with reproduction 🙏🏼

**Comment by zsilbi** [comment]
@pi0 the issue is with the Nitro build itself, not in a project built with Nitro

**Comment by pi0** [comment]
how it makes an issue with your external usage? (again, i understand it is an issue, but in order to track any issue report, this is expected, otherwise i have to try to make first setup first).

**Comment by zsilbi** [comment]
Thank you for the explanation, you can find the reproduction here: 
https://github.com/zsilbi/nitro-mts-repro

A temp. fix is to modify `package.json` from `*.d.mts` to `*d.ts` for the runtime entries.
