### ISSUE TITLE
Scheduled tasks type on nitro options are incorrect

### ISSUE THREAD

**Issue by noook** [unjs/nitro#2283]
### Environment

Nitro 2.9

### Reproduction

— (I'll do the PR)

### Describe the bug

https://github.com/unjs/nitro/blob/8a62e7dbaeeffb6dff533c7000aba51a5c85e479/src/types/nitro.ts#L342

The types are incorrect, it should be 

```ts
 scheduledTasks?:  { [cron: string]: string[] }; 
```

I think maybe of having to handle the undefined case when we have no scheduled tasks, we could just make this property be an empty object as default (as it's assignable).

**Comment by pi0** [comment]
Thanks for helping on this but please either make a proposal for enhancement and wait for discussion or an issue with reproduction next times 🙏🏼
