### ISSUE TITLE
UnJS: Add abstraction to object / file storage (e.g. local, S3, R2, Vercel Blob)

### ISSUE THREAD

**Issue by MickL** [unjs/nitro#2304]
### Describe the feature

This is a feature request for the UnJS ecosystem but I am unsure where else to put it:

It would be amazing to have a library that abstracts / unifies the usage of object/file storages (like S3). 

Possible drivers could be:

- File system
- AWS S3
- Cloudflare R2
- Vercel Blob

Benifits:
- Easy to use like unjs/unstorage :)
- Easy to transfer from one provider to another
- Use different driver for local development than on production (e.g. file system on local, Vercel Blob on production)

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by danielroe** [comment]
I think unstorage is this very thing. It supports writing 'raw' content to FS/blob storage, etc.

**Comment by MickL** [comment]
Arent there then all the drivers for file storages missing? Like AWS S3, Cloudflare R2, Vercel Blob, etc

I always thought there is a huge difference between a KV store like Redis and a file store like S3

**Comment by pi0** [comment]
@MickL Unstorage combines all storage with a unified/simplified interface via drivers. There is an open tracker for S3, and R2 is supported too. Always feel free to open improvement suggestions to add more drivers to [unjs/unstorage](https://github.com/unjs/unstorage) if feel something is missing 👍🏼
