### ISSUE TITLE
Cannot import from `nitropack/runtime`

### ISSUE THREAD

**Issue by MickL** [unjs/nitro#2305]
Reproduction (@pi0): https://stackblitz.com/edit/unjs-nitro-starter-w9u6yx?file=server%2Froutes%2Findex.ts,nitro.config.ts&title=Nitro%20Starter

### Describe the bug

I am trying to figure out how to use Nitro without auto imports. I know `defineEventHandler` is imported from `h3` but I cant find any module exporting `defineCachedEventHandler`, `nitropack` is not exporting it:

<img width="556" alt="Bildschirmfoto 2024-03-24 um 16 42 53" src="https://github.com/unjs/nitro/assets/5103210/b71b8c54-523a-42e0-b087-8fef258f3b0a">

**Comment by markthree** [comment]
@MickL You can use the following import method ↓
```ts
import { defineCachedEventHandler } from "#imports"
```

**Comment by MickL** [comment]
Isnt this the exact same as using auto imports? The import comes from a file that needs to be pregenerated and obscures the real origin of the function?

I was hoping to get rid of this :/

<img width="614" alt="Bildschirmfoto 2024-03-25 um 11 41 21" src="https://github.com/unjs/nitro/assets/5103210/e8998dc7-499f-4474-a0ba-39767447b8d9">

**Comment by pi0** [comment]
You are right. While (current) recommendation is using `#imports`, if `imports: false` is used, there is no way of using direct import for `nitropack/runtime` which is actually the implementation.
