### ISSUE TITLE
Add testing utilities

### ISSUE THREAD

**Issue by MickL** [unjs/nitro#2307]
### Describe the feature

At least missing:

- Setup Nitro app
- Provide fetch function

Something like this: https://github.com/johannschopplich/nitro-starter/blob/main/test/utils.ts

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
~> https://github.com/unjs/nitro/issues/2303

**Comment by pi0** [comment]
I have a plan to work on a novel testing system for Nitro server which i need to better explain later once more shaped idea but in the meantime any setup that works for you. Setup function in shared repo seems nice 👍🏼

**Comment by MickL** [comment]
Sounds good! Possibly for v3?

**Comment by johannschopplich** [comment]
For the record: I've built [nitro-test-utils](https://github.com/johannschopplich/nitro-test-utils) until the official utilities are ready. 🙂
