### ISSUE TITLE
Crash of production bundle with custom preset

### ISSUE THREAD

**Issue by mrmurnst** [unjs/nitro#2315]
### Environment

Nitro 2.9.4 (and probably earlier) on Node 18 (and probably others)

### Reproduction

https://stackblitz.com/edit/unjs-nitro-starter-rok6dt?file=package.json

#### Problem
When adding a rule with `cache` in `routeRules` and adding a custom preset, the resulting production bundle crashes with a ReferenceError.

#### What's happening?
There are various circular dependencies between modules in Nitro core.
For some reason, the warnings, that Rollup spits out about them, have been suppressed in e5f9900bc73456ddcb8a4c25649ed2d4f797c099 a long time ago...

Specifically, one of these circular dependencies is between [app.ts](https://github.com/unjs/nitro/blob/main/src/runtime/app.ts) and [cache.ts](https://github.com/unjs/nitro/blob/main/src/runtime/cache.ts).
Because of this, the order, in which they are assembled by Rollup in the output bundle, is not well-defined, and may change...
However, **the resulting bundle only works reliably, if `cache` is included before `app`**, because of a reference to `cachedEventHandler` from within `createNitroApp`.
This reference is only hit, if a cache route rule is defined for some handler, but I think that's a common occurrence (see additional context).

#### Reproducibility
Now, a plain Nitro 2.9.4 project with a cache route rule always seems to build a working bundle (with `cache` before `app`) for me. As soon as I include a custom preset though - the repro just has [the example from the docs](https://nitro.unjs.io/deploy/custom-presets) - it stops working.

If I'm right about the module order not being well-defined, this may be very fragile, though. I don't know much about the internals of Rollup and how it orders modules within its chunks.

### Additional context

This has originally surfaced in a larger project with a more complex custom preset when upgrading from Nuxt 3.7 to Nuxt 3.11 with Nitro being updated from 2.8.0 to 2.9.4.
Because of the nature of the problem (see above), this does not mean that Nitro 2.8.0 didn't already have the problematic circular reference. It probably just worked by chance...

That project uses [@nuxtjs/sitemap](https://github.com/nuxt-modules/sitemap), which specifies `cache` via `routeRules` internally for its own routes ➡️ I guess this is a common setting.

**Comment by pi0** [comment]
Hi. You can fix it by importing `useNitroApp` explicitly from `#imports` in entry:

```js
import { useNitroApp } from '#imports';
```

PS: I would not recommend custom preset usage in anyway. If you are facing any limitation with built-in presets, please raise an issue for them and best luck.

**Comment by pi0** [comment]
Hi. You can fix it by importing app directly:  (make sure to use `>=2.9.5`)

```js
import { nitroApp } from 'nitropack/runtime/app';
```

PS: I would not recommend custom preset usage in anyway and above usage might get broken. If you are facing any limitation with built-in presets, please raise an issue for them and best luck.

**Comment by mrmurnst** [comment]
How do you ensure the order of modules in the bundle, though? Doesn't this seem a bit fragile to you, too?

**Comment by pi0** [comment]
Yes that's why we never exposed entry usage yet for stable custom presets.
