### ISSUE TITLE
Documentation not rendering example correctly

### ISSUE THREAD

**Issue by robokozo** [unjs/nitro#2329]
### Environment

Website
Chrome: Version 123.0.6312.86 (Official Build) (64-bit)

### Reproduction

https://nitro.unjs.io/guide/routing#request-filtering

### Describe the bug
The example code is not rendering correctly.
`For example, you can use the URL to apply a middleware to a specific route:`
![image](https://github.com/unjs/nitro/assets/1719221/7ad9ce7e-b75e-40ff-b569-4bb9ef4d8b16)

The code seen here:
https://github.com/unjs/nitro/blob/2bce7adafd988ffef186b70012a4b45087f11ca5/docs/1.guide/2.routing.md?plain=1#L213C1-L222C4

**Comment by pi0** [comment]
Thanks for the report. Should be fixed now thanks to @cpreston321
