### ISSUE TITLE
add example code for tasks in guide

### ISSUE THREAD

**Issue by rrd108** [unjs/nitro#2330]
### Describe the feature

Current guide (https://nitro.unjs.io/guide/tasks) contains all info about task except an example of a task.

I would add something like this

```ts
// server/tasks/taskGroup/taskName.ts
export default defineTask({
  meta: {
    description: "Example task",
  },
  async run() {
    // add any custom task logic here and set result to return/log
    return result;
  },
});
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by JCtapuk** [comment]
![image](https://github.com/unjs/nitro/assets/61321608/1ec6a933-2475-4a56-adaa-ac281992ff8c)
Where did you look? The documentation contains

**Comment by rrd108** [comment]
:rofl: 
OMG I read the whole thing like 5 times, and I did not noticed that...
