### ISSUE TITLE
Root "/" doesn't get prerendered with Github Pages preset

### ISSUE THREAD

**Issue by sby1ce** [unjs/nitro#2333]
### Environment

nitro 2.9.5

### Reproduction

In `nitro.config.ts`
```ts
export default defineNitroConfig({
  srcDir: "server",
  preset: "github-pages"
});
```
https://codesandbox.io/p/github/unjs/nitro/csb-rqd4sc/draft/old-sky?file=%2Fnitro.config.ts%3A6%2C1

### Describe the bug

`nitro build` with "github-pages" preset doesn't prerender `index.html` file like with the "static" preset which doesn't seem to be intended behaviour. \
this is due to github pages preset adding `404.html` route in prerender object
https://github.com/unjs/nitro/blob/eb377abf3332f431b388d3fa53b2c8786f832183/src/presets/github-pages.ts#L10-L15

this check is no longer true
https://github.com/unjs/nitro/blob/2bce7adafd988ffef186b70012a4b45087f11ca5/src/prerender.ts#L40-L43

so `index.html` doesn't get prerendered

### Additional context

manually adding "/" to routes array should fix this but maybe there's a better solution

**Comment by pi0** [comment]
please share reproduction

**Comment by sby1ce** [comment]
here you are \
https://codesandbox.io/p/github/unjs/nitro/csb-rqd4sc/draft/old-sky?file=%2Fnitro.config.ts%3A6%2C1

**Comment by pi0** [comment]
Thanks for repro. Feel free to make a PR for adding `/` by default for `github-pages` 👍🏼
