### ISSUE TITLE
Error 500 on any page of the docs website

### ISSUE THREAD

**Issue by mathix420** [unjs/nitro#2337]
### Environment

https://nitro.unjs.io/

### Reproduction

https://nitro.unjs.io/

### Describe the bug

https://nitro.unjs.io/

![image](https://github.com/unjs/nitro/assets/37625778/2a2eb8ee-1fe0-4ea0-8029-cefdb1fcb682)

**Comment by pi0** [comment]
Thanks report. It should be solved. Please see https://github.com/unjs/nitro/issues/2335
