### ISSUE TITLE
Not serving index.html

### ISSUE THREAD

**Issue by nitedani** [unjs/nitro#243]
### Environment

nitropack: 0.4.4
node: 16.13.2
no config

### Reproduction

1. create the folder structure seen in the picture
2. npx nitropack build
3. node .output/server/index.mjs
4. navigate to localhost:3000

### Describe the bug

The built server is not serving index.html on the baseurl. 
It is trying to look for assets "/" and "//index.html", when it should look for "/" and "/index.html" instead. There is an extra slash.

The issue shows in the attached picture.
![image](https://user-images.githubusercontent.com/67418286/168511997-ac3f5ff5-9816-42ca-bb3c-396718447c81.png)
![image](https://user-images.githubusercontent.com/67418286/168512308-f6f67537-a689-4887-b408-c49bc7e8f777.png)

If this is intended, is there a way to configure nitro to serve "/index.html" for all unhandled routes?
I'm looking for a behavior like:
`for (const _id of [id, id + "/index.html", "/index.html"]) {`

**Comment by pi0** [comment]
Testing with latest nitro, putting `public/index.html` works as expected with `nitro build` and `nitro dev`. 

If you experience issue with a specific preset, please feel free to open a new issue 🙏🏼
