### ISSUE TITLE
Support Netlify-Vary header in netlify v2 preset

### ISSUE THREAD

**Issue by Rigo-m** [unjs/nitro#2431]
### Environment

See reproduction.
Relevant branches:
https://github.com/Rigo-m/netlify-v2-repro/tree/no-cdn-cache-control
https://github.com/Rigo-m/netlify-v2-repro/tree/cdn-cache-control

Check route rules.

### Reproduction

https://cache-key-variations.netlify.app/guess?value=2 you can see how this page gets cached at the edge, including the variation on the value query parameter (take a look specifically at the Netlify-Vary heade, the Cdn-Cache-Control header and the Age header for verification).

Here: https://no-cdn-cache-control--netlify-v2-nitro.netlify.app/?page=3 you can see that while the Netlify-Vary header is present, it's not actually caching the page.
Here: https://cdn-cache-control--netlify-v2-nitro.netlify.app/?page=3 you can see that by adding the Cdn-Cache-Control header everything works accordingly.

### Describe the bug

Netlify v2 preset appends a Netlify-Cdn-Cache-Control header to instruct the netlify edge platform on how to handle CDN caching.
Only setting this header makes the edge network ignore the Netlify-Vary header (somehow).
We should send the Cdn-Cache-Control header as well, so that when setting the additional header Netlify-Vary from routeRules works accordingly without handling other headers.

### Additional context

I'll drop two PRs after https://github.com/unjs/nitro/pull/2425 gets merged, one with the relevant fix, another with relevant documentation on the Netlify-Vary header for the netlify v2 preset :)

**Comment by Rigo-m** [comment]
@serhalp do you have any insights on the situation?

**Comment by serhalp** [comment]
Hey @Rigo-m, thanks for writing this up.

Isn't a `Vary` or `Netlify-Vary` header meaningless when no caching is enabled? I'm not sure I'm understanding why you're expecting the Netlify CDN to cache the serverless function response in this case. The function is even explicitly sending `cache-control: no-cache` on your repro site.

**Comment by Rigo-m** [comment]
In the "no-cdn-cache-control" branch you can see that I've set the routeRule for caching the page [here](https://github.com/Rigo-m/netlify-v2-repro/blob/no-cdn-cache-control/nuxt.config.ts), using the new netlify v2 preset.
Now, if you visit the homepage without the query parameter it actually gets cached (check age and cache-control), whilst adding a query parameter returns no-cache.
- https://no-cdn-cache-control--netlify-v2-nitro.netlify.app/ -> cached
- https://no-cdn-cache-control--netlify-v2-nitro.netlify.app/?page=3 -> not cached despite setting netlify-vary on page

Setting `isr` value in routeRules should add the `Netlify-Cdn-Cache-Control` Header to the response, am I missing anything?

**Comment by serhalp** [comment]
Thanks for clarifying @Rigo-m – I'm with you now.

I think I see where the regression is coming from. I'll have a PR up soon.

**Comment by serhalp** [comment]
@Rigo-m https://github.com/unjs/nitro/pull/2440

**Comment by Rigo-m** [comment]
Amazing, left a small comment for you there
