### ISSUE TITLE
[nightly] Could not resolve entry module "node_modules/nitropack/dist/chunks/runtime/node-server"

### ISSUE THREAD

**Issue by daniluk4000** [unjs/nitro#2448]
### Environment

Nitro 2.10.0-28597966.b2831dd5, Node 20 latest

### Reproduction

I'll be happy to create repro if it will be needed but let me create this one without repro for now

### Describe the bug

I'm currently on Nuxt Nightly (for some of bug fixes), we updated nitro today and our project sadly stopped building

![image](https://github.com/unjs/nitro/assets/10450717/232937c8-b76b-4ac4-9756-6ed28546dafb)

![image](https://github.com/unjs/nitro/assets/10450717/43f02a1c-8f34-41b1-8e8b-9e1c0754156c)

### Additional context

I've pinned nitro to `2.10.0-28585081.346a4950` and it builds just fine

**Comment by daniluk4000** [comment]
This looks sus

![image](https://github.com/unjs/nitro/assets/10450717/7ff00bf8-b289-4246-9c51-897d276d5f97)

**Comment by daniluk4000** [comment]
Latest nuxt nightly also fails for me with `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/frontend/.output/server/node_modules/@opentelemetry/instrumentation/hook.mjs' imported from /frontend/.output/server/node_modules/@sentry/node/esm/sdk/init.js`

I don't know what changed there...

**Comment by pi0** [comment]
Thanks for reporting. Ill look into it. For context nitro main branch is going under heavy refactors to prepare for v3 so more issues like this are likely to happen on nightly channel.

**Comment by daniluk4000** [comment]
> Thanks for reporting. Ill look into it. For context nitro main branch is going under heavy refactors to prepare for v3 so more issues like this are likely to happen on nightly channel.

Thanks! We'll keep it pinned then :)
