### ISSUE TITLE
[nightly] RollupError if project install with PNPM

### ISSUE THREAD

**Issue by casualmatt** [unjs/nitro#2453]
### Environment

WSL with Ubuntu 20.x
Nuxt 3.12.0-28598578.dad89c2b with Nitro 2.10.0-28597966.b2831dd5   

### Reproduction

`pnpx nuxi init`
Chages to `package.json`  ` "nuxt": "npm:nuxt-nightly@latest",` 
And to `nuxt.config.ts`:
```
 future: {
    compatibilityVersion: 4,
  },
```
`pnpm i`  at runtime will give an RollupError that you will not get if you use `npm i`
`pnpm dev`

### Describe the bug

 ERROR  RollupError: Could not resolve entry module "node_modules/.pnpm/nitropack-nightly@2.10.0-28597966.b2831dd5_@opentelemetry+api@1.8.0/node_modules/nitropack-nightly/dist/chunks/runtime/nitro-dev".

**Comment by Rigo-m** [comment]
Duplicated of https://github.com/unjs/nitro/issues/2448

**Comment by manniL** [comment]
Closing in favor of https://github.com/unjs/nitro/issues/2448
