### ISSUE TITLE
Keep nitro agnostic - Maybe not have FileRouting convention baked in

### ISSUE THREAD

**Issue by birkskyum** [unjs/nitro#2454]
### Describe the feature

This seems highly opinionated, and not like something that generalize well across meta-frameworks.

https://nitro.unjs.io/guide/routing#filesystem-routing

Could it make sense to pull this out of nitro and let e.g. nuxt/vinxi/analog provide their own conventinos, to make sure nitro is agnostic?

**Comment by Rigo-m** [comment]
You can always opt-out of it

**Comment by birkskyum** [comment]
sure, and you're totally right it's not a blocking issue in any way, but my understanding was that unjs is all about separation of concerns and leaning into the "agnostic excellence", so all I'm saying is that seemed a bit like an odd one out for Nitro to bundle what appear to be the [Nuxt server-endpoints and middleware](https://nuxt.com/docs/getting-started/server#server-endpoints-middleware).

**Comment by Rigo-m** [comment]
Unjs is **runtime agnostic**, not **unopinionated**. Those are two different things. I feel like having file based routing as an opt out default or having it as an opt in commodity is just a matter of preference. One of those things that ultimately splits communities apart without being so relevant after all

**Comment by birkskyum** [comment]
Aha, runtime agnostic! Makes sense :) throught the idea was that it was meta-framework agnostic. I see your point now.
