### ISSUE TITLE
Caching fails when you cache a nested route and its parent

### ISSUE THREAD

**Issue by UnderKoen** [unjs/nitro#248]
### Environment

nitro: 0.4.0

### Reproduction

`/api/test/index.get.ts`
```ts
import { defineCachedEventHandler } from '#internal/nitro'

export default defineCachedEventHandler(() => 'test')
```

`/api/test/test2/index.get.ts`
```ts
import { defineCachedEventHandler } from '#internal/nitro'

export default defineCachedEventHandler(() => 'test2')
```

### Describe the bug

When caching for two routes overlap one of the routes can't generate a file for the cached route.

### Logs

```sh
[nitro] [cache] [Error: ENOENT: no such file or directory, open 'E:\Projects\Nuxt\nitro\playground\.nitro\cache\nitro\handlers\_\api\test\test2'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\Projects\\Nuxt\\nitro\\playground\\.nitro\\cache\\nitro\\handlers\\_\\api\\test\\test2'
}
```
```

**Comment by pi0** [comment]
Hi @UnderKoen and thanks for reporting this issue. But I can't reproduce it on 0.4.4. Two test/test2 cache entries are generated properly. Do you mind to provide a reproduction in codesandbox or stackbliz? 🙏🏼
