### ISSUE TITLE
Request to add cloudflare worker email handler

### ISSUE THREAD

**Issue by dalbodeule** [unjs/nitro#2480]
### Describe the feature

The cloudflare worker has a feature that allows email handling by declaring the `email` function [added as beta](https://developers.cloudflare.com/email-routing/email-workers/).
I would like to use this feature. However, nitro does not officially support this feature.

Therefore, I hope you will consider using this feature.
In addition, I hope that the queue consumer is also well created.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by dalbodeule** [comment]
I implemented the Email function in [my fork's emailTask ​​branck](https://github.com/dalbodeule/nitro/tree/emailtask). Is it okay to implement it this way?

**Comment by pi0** [comment]
I think we can simply expose a hook from cloudflare one and allow integrating it since this feature is mostly vendor specific (cloudflare preset calls `cloudflare:email(event, context)` hook)

**Comment by dalbodeule** [comment]
`cloudflare:email` and `cloudflare:queue` handler is mareged. close this issue!

**Comment by dalbodeule** [comment]
<img width="783" alt="image" src="https://github.com/unjs/nitro/assets/11470513/4410da78-ccaa-43d7-a275-1c98e14432aa">

after [the chore](https://github.com/unjs/nitro/blob/63526f24b03e5e5de65934c697c92dd00f1e1ab1/src/presets/cloudflare/types.ts#L88), "cloudflare:email" and "cloudflare:queue" hook is not detected properly. Could you possibly know a solution to this?

**Comment by dalbodeule** [comment]
<img width="1236" alt="image" src="https://github.com/unjs/nitro/assets/11470513/51662925-1d7a-4843-a3e8-f125ac1ace40">

I placed the plugin in the exact location just in case, but it's still the same. It seems that TypeScript does not recognize the existence of the "cloudflare:email" and "cloudflare:queue" hooks.

**Comment by dalbodeule** [comment]
issue moved [here](https://github.com/unjs/nitro/issues/2587)

**Comment by zou-yu** [comment]
> `cloudflare:email` and `cloudflare:queue` handler is mareged. close this issue!

@dalbodeule Good job! Thank you for your contribution!! I really need this feature (email handler)
