### ISSUE TITLE
Remove preset "render.com"

### ISSUE THREAD

**Issue by MickL** [unjs/nitro#2535]
### Describe the feature

I was wondering what is the difference between setting no preset (which is using `node-server`) and `render.com` but looking at the [preset](https://github.com/unjs/nitro/blob/main/src/presets/render.com/preset.ts) there seems to be none.

Therefor I would suggest to remove the preset `render.com`. Instead I would suggest to keep it the provider in the docs but update the docs that we can use no preset, `node-server` or even `bun`.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
We use presets as forward compatibility to make sure Nitro can adjust it's behavior automatically for the platform.
