### ISSUE TITLE
renderer paths ending with `/favicon.ico` will be always served as placeholder

### ISSUE THREAD

**Issue by jgitlin-nypr** [unjs/nitro#2552]
https://github.com/unjs/nitro/blob/928373ccecffc7c1bf519543ffeba11bfcfeb4ea/src/runtime/renderer.ts#L26

This line of code is insufficiently defensive and caused a major issue for us. By only doing a string match, it's possible to append "favicon.ico" to a URL (ie via a query string) and get served a broken favicon instead of a page. If you are using a CDN that ignores query params, then it's a vector for cache poisoning. This [Stackblitz example](https://stackblitz.com/edit/github-sukl2f?file=handlers%2Frender-handler.ts) shows the issue.

**Comment by pi0** [comment]
Thanks for report. #2553 will fix it for [nightly channel](https://nitro.unjs.io/guide/nightly) and next minor release.
