### ISSUE TITLE
Replace chalk with picocolors

### ISSUE THREAD

**Issue by boehs** [unjs/nitro#2572]
### Describe the feature

Picocolors is both faster and about 6.9% of the size of chalk. There is a quite simple migration guide [here](https://github.com/alexeyraspopov/picocolors?tab=readme-ov-file#replacing-chalk)

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/boxen/issues/95#issuecomment-2198041994

**Comment by boehs** [comment]
@sindresorhus, I cannot respond to your comment because you locked the issue, but

> In addition, it's likely Chalk is already in the dependency tree, so Chalk is actually 100% smaller than Picocolors in most situations.

Picocolors is also very likely in the dependency tree by now, eg. with babel switching to it in babel 8. Lets not forget that it is very likely multiple versions of chalk are being installed, due to version changes. Docs are a ridiculous requirement in the context of a terminal coloring library, where the available methods are automatically inferred. The additional features point is moot as these features are not being utilized, and furthermore, I don't know why you would make your *own* colouring library and not use it. As noted in this issue, **I am more than willing to implement the switch myself**, so "You are wasting both your and maintainers' time on this effort", I am only "wasting" my own time, as instead of simply saying "I refuse" you decided to type out an entire paragraph on... why it makes sense to include a completely redundant package, *then* you stalked my profile to leave a reference to this on another repository.

The size of dependency trees *does* have transitive impacts on users, especially in serverless contexts where additional kilobytes slow down cold start times. Perhaps, there are even lower hanging fruits, but this is, indisputably, also one.

**Comment by pi0** [comment]
Thanks for the suggestion dear @boehs. Across unjs we use [consola](https://consola.unjs.io) as standard CLI tooling (and a common dependency that is likely installed) and migrating to color and formating utils from `consola/utils`.

As chalk is already installed as a sub dependency of nitro dependencies that use babel v7, removal of chalk dependency has no immediate effect..

> The size of dependency trees does have transitive impacts on users, especially in serverless contexts where additional kilobytes slow down cold start times

Nitro does not bundle chalk or consola or any other formatting library in the production bundles.

**Comment by boehs** [comment]
> Nitro does not bundle chalk or consola or any other formatting library in the production bundles.

That was my misconception, thank you regardless ❤️
