### ISSUE TITLE
404 error after running npx nuxi generate with app.baseURL set.

### ISSUE THREAD

**Issue by khopha** [unjs/nitro#2579]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, app
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-zk6sfo

Steps:
1. Set `app.baseURL` in nuxt.config.ts.
2. Run `npx nuxi generate`.
3. Run `npm run preview`.
4. Click the links in the generated HTML.

### Describe the bug

The links in the generated HTML navigate to a 404 error. After removing **base** from the URL, it works correctly. For example, **localhost/base/about** results in a 404 error, whereas **localhost/about** is correct.

### Additional context

Reported in https://github.com/nuxt/nuxt/issues/27923

**Comment by danielroe** [comment]
Thank you so much! I've created https://github.com/unjs/nitro/issues/2580 as a tracker issue which I think should fully resolve this. Let's track there. (Sorry for asking you to create this and then creating another issue instead. 🤦)
