### ISSUE TITLE
"cloudflare:email", and "cloudflare:queue" hook isn't have.

### ISSUE THREAD

**Issue by dalbodeule** [unjs/nitro#2587]
### Environment

Node v22.2.0

### Reproduction

<img width="1236" alt="image" src="https://github.com/unjs/nitro/assets/11470513/9c0e7b3b-368c-4775-8706-af986b16ab20">

### Describe the bug

Inner defineNitroPlugin, nitro.hook.hooks (NitroRuntimeHooks) don't have "cloudflare:email", "cloudflare:queue" hook keys.

After [this chore](https://github.com/unjs/nitro/blob/63526f24b03e5e5de65934c697c92dd00f1e1ab1/src/presets/cloudflare/types.ts#L88), is issue created.

### Additional context

This issue re-issued on [this issue](https://github.com/unjs/nitro/issues/2480)

**Comment by dalbodeule** [comment]
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/bd4ace9b-3e74-4a8e-9c18-7d53a3efdb39">

Just in case, I went through the nitro install process and performed the same task in the nitro-app directory. However, even if I try to import cloudflare-module, the result is the same.

**Comment by zou-yu** [comment]
It works fine for me, check if you are using nightly build nuxt or nitro likes: `"nuxt": "npm:nuxt-nightly@latest"`.
![image](https://github.com/user-attachments/assets/7655a358-a19b-4071-92bb-31b0b3513c63)

**Comment by dalbodeule** [comment]
![image](https://github.com/user-attachments/assets/6b941e8e-9f25-4f41-b0f8-9dd73ddcae6e)

I didn't even think about nightly builds.
After using the Nigitly build, I was able to use the "cloudflare:email" and "cloudflare:queue" hooks. thank you for telling me.

**Comment by dalbodeule** [comment]
What was originally supposed to be MessageBatch<unknown>, I looked it up today and found that it was written as CloudflareEmailContext.
