### ISSUE TITLE
nuxt 3 firebase-hosting not working

### ISSUE THREAD

**Issue by rendomnet** [unjs/nitro#260]
### Environment

node: v14.18.1

### Reproduction
// REPRODUCTION REPO
https://github.com/rendomnet/nuxt3-firebase
just change the project-id "project-name" in firebase.json and .firebase.rc

I'm following this QUICK-START guides.
nuxt-3
https://v3.nuxtjs.org/getting-started/quick-start

Firebase
https://nitro.unjs.io/deploy/providers/firebase.html

```


npx nuxi init nuxt-app
cd nuxt-app
yarn install

firebase login
firebase init hosting

{
  "functions": { "source": ".output/server" },
  "hosting": [
    {
      "site": "<your_project_id>",
      "public": ".output/public",
      "cleanUrls": true,
      "rewrites": [{ "source": "**", "function": "server" }]
    }
  ]
}
set NITRO_PRESET="firebase yarn build"
firebase emulators:start
```

### Describe the bug
firebase emulators:start

> i  emulators: Starting emulators: functions, hosting
> **!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, pubsub, storage**
> i  emulators: Shutting down emulators.
> i  functions: Stopping Functions Emulator
> i  hub: Stopping emulator hub

**Comment by robokozo** [comment]
I'd love to see some progress on this front. Firebase seems to be working on this from their side too: https://firebase.google.com/docs/hosting/frameworks-overview
At the moment they have next, angular, and express beta support with plans for nuxt down the line.

**Comment by davidstackio** [comment]
Looks like basic Nuxt support was added a few weeks ago: https://github.com/firebase/firebase-tools/releases/tag/v11.22.0

But I have yet to find any proper documentation on how to get it working.

**Comment by Hebilicious** [comment]
closing in favour of https://github.com/unjs/nitro/issues/1370

The new issue has working instructions that will be added to the documentation shortly.
