### ISSUE TITLE
nitro.experimental.openAPI doesn't accept a json configuration like the documentation highlights.

### ISSUE THREAD

**Issue by jonasfroeller** [unjs/nitro#2632]
### Environment

NodeJS: v18.19.0
Nitro: version that nuxt ^3.12.3 uses

### Reproduction

```
nitro: {
    imports: {
      dirs: ['./server/utils'],
    },
    experimental: {
      openAPI: {
        meta: {
          title: 'Nuxai API Documentation',
          description: 'Chat with different AI models using this REST-API.',
          version: '0.0.0',
        }
      },
    },
};    
```

```bash
 ERROR(vue-tsc)  Type '{ meta: { title: string; description: string; version: string; }; }' is not assignable to type 'boolean | undefined'.
 FILE  A:/xxx/nuxt.config.ts:27:7

    25 |     },
    26 |     experimental: {
  > 27 |       openAPI: {
       |       ^^^^^^^
    28 |         meta: {
    29 |           title: 'API Documentation',
    30 |           description: '',
```

### Describe the bug

This doesn't actually work (https://nitro.unjs.io/config#experimental):

![image](https://github.com/user-attachments/assets/906e3c2f-4713-410b-86a2-87d0fc516ad8)

**Comment by manniL** [comment]
Because https://github.com/unjs/nitro/pull/2299 didn't land yet. You can try it in nightly mode though.

**Comment by jonasfroeller** [comment]
> Because #2299 didn't land yet. You can try it in the nightly release though.

Thank you for the quick response!  
I was confused, because the docs just said the scalar implementation is in nightly and not the openai stuff. But makes sense.
![image](https://github.com/user-attachments/assets/c04d7545-9984-4808-879f-60a50383c961)
