### ISSUE TITLE
Run tasks single time even in cluster mode + max instances

### ISSUE THREAD

**Issue by dethdkn** [unjs/nitro#2647]
### Describe the feature

Hello I have a nuxt app running in pm2 with cluster mode and max instances, that means I have 8 instances of the same app.
I created a task that I want to run every day at 8 AM, It works perfectly, the problem is, it runs 8 times every day at 8 AM, I guess it's running 1 time for each instance.
Is there a way to make it run only once? I read the docs but I cant find a solution. Thanks a lot for the help!

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by markthree** [comment]
I think pm2's [Specific environment variables](https://pm2.keymetrics.io/docs/usage/environment/) should solve your problem. 

By default, you can keep only one process running a timed task by determining 
`process.env.NODE_APP_INSTANCE`

**Comment by dethdkn** [comment]
> I think pm2's [Specific environment variables](https://pm2.keymetrics.io/docs/usage/environment/) should solve your problem.
> 
> By default, you can keep only one process running a timed task by determining `process.env.NODE_APP_INSTANCE`

🤯 Awesome idea, I will try this!

**Comment by dethdkn** [comment]
This worked for me, thanks!

```ts
const { NODE_APP_INSTANCE } = process.env

if(NODE_APP_INSTANCE !== '0') return { result: 'Task stopped' }
```

**Comment by GalacticHypernova** [comment]
@dethdkn my apologies that I am mentioning you after all this time about this, but with the time you have had to test, how does this fare against localized failures? If the 0th instance fails and stops, does the task still get run? Does the 1st instance take the place  of the 0th, or does the task just never gets ran again?

**Comment by dethdkn** [comment]
Hello @GalacticHypernova, the tasks runs only on instance 0 with the code I provided.
Since I started using it, it never failed, but I guess if it failed, the task would simply stop and only run again on the next call.
For me thats not a problem, but maybe you could write a catch block to run the task again on another instance if it failed!?

**Comment by markthree** [comment]
@GalacticHypernova 
If the process exits unexpectedly, pm2 restarts, but I'm not sure if `process.env.NODE_APP_INSTANCE` is still the same (semantically intuitively it should be).
Theoretically the task will run again after the process restarts with the same rules as before.

**Comment by GalacticHypernova** [comment]
Isn't it a bit risky if it sends a SIGKILL and terminates it without restarting?

**Comment by markthree** [comment]
@GalacticHypernova If your task is particularly important, you shouldn't have it in the same process as the api service, because both the task language and the framework-built api service can crash due to oom, and you'll never be able to guarantee that your task will run perfectly.

**Comment by GalacticHypernova** [comment]
Well, if the task is meant to be a background process, it's a perfect candidate for a scheduled task, which nitro supports. If it also is related to the api service (as in, the api service uses this task for its data), it would be logical to group them together. One way I found to guarantee it runs perfectly is via a Redis lock, which will be thread safe and ensure synchronicity, and also avoid duplicated tasks

**Comment by markthree** [comment]
@GalacticHypernova Yes, I agree with you that using redis for synchronisation is more robust.

**Comment by GalacticHypernova** [comment]
So I think that just in case, I'll go for the redis approach for more robustness. Even though using an env variable would be faster, I think redis would be faster than the overhead of the API calls I would otherwise need to make to handle updates in the app from outside the api service, because I am fairly certain that even if the nitro redis mount point gets cloned to all instances, the database itself would still be shared. 

Thanks for the help!

**Comment by markthree** [comment]
> What if it sends a SIGKILL and terminates it without restarting? Of course if it restarts it will keep working, but I'm asking about localized failure of the instance that causes it to stop, not restart.

For signalling an exit, you can actually wait for it with the close hook, as in this example → [graceful-shutdown/plugins/db.ts](https://github.com/nitrojs/nitro/blob/v2/examples/graceful-shutdown/plugins/db.ts)。

Using env for process differentiation simply avoids duplication of tasks, there is no special magic. When using nitro alone, the task still follows the rules of the system process, and there is no guarantee of its robustness (the task can always fail).

**Comment by GalacticHypernova** [comment]
The problem isn't awaiting the exit, it's that if the instance unexpectedly gets terminated with a critical issue that prevents pm2 from restarting it (such as SIGKILL instead of a SIGTERM)

You also can't listen to SIGKILL by the way. The task can have its own error handling, but if the instance itself fails and doesn't get restarted, I'm afraid the env variable won't reflect that correctly (I.e. instance 0 fails, and all other instances remain with their identifiers, which means the task will never run again until you even notice first that the instance failed and restart it)

**Comment by GalacticHypernova** [comment]
Of course! Glad I could help along of the way of asking for help 🙂 

This was just a little something that is a part of my app, which requires the exact status checker I described in the example, with the subsequent database writes, so I thought it would be better to consult with people who have touched on the subject of repeated operations, as performance is critical to avoid straining the server too much and risking degrading the apps performance

**Comment by juretopolak** [comment]
Thank you for the detailed discussion above. The suggested solutions—using NODE_APP_INSTANCE or Redis locks—work great as user-level fixes. However, I’m curious if there are any plans or openness to having an official, built-in mechanism in Nitro for tasks that should run only once in a clustered environment. It’d be tremendously helpful to have this as a core feature (or maybe a plugin) that handles “singleton tasks” more robustly.

Is this something you’d consider adding to Nitro, or would you accept a PR implementing it?

Thanks again for all your hard work on Nitro!
