### ISSUE TITLE
Provide a way to terminate websocket connections

### ISSUE THREAD

**Issue by ms0ur** [unjs/nitro#2667]
### Describe the feature

The crossws library (which is used for ws connections in h3) [provides](https://crossws.unjs.io/guide/peer#instance-properties) a way to terminate ws connections, but Nitro currently does not support this functionality. Could you please add support for terminating ws connections in Nitro?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
It will be supported as soon as crossws is released and updated for nitro.
