### ISSUE TITLE
waitUntil not working in cloudflare pages preset

### ISSUE THREAD

**Issue by retuerto** [unjs/nitro#2672]
### Environment

Nuxt 3.12.4 with Nitro 2.9.7  with cloudflare pages preset through nuxthub

### Reproduction

https://stackblitz.com/edit/github-ch89s7?file=routes%2Findex.ts,plugins%2Fbackground.ts

### Describe the bug

I just found out that it works in development environment but it doesn't work as expected when deployed on cloudflare throught nuxthub. event.waitUntil gets blocked and the user waits for the response when it shouldn't happen like that. I tried this and it works:

```ts
const waitFor = (ms: number) =>
  new Promise((resolve) => setTimeout(resolve, ms))

async function backgroundTask(id: number) {
  await waitFor(5000)
  console.log(`Task ${id} is done!`)
}

export default defineEventHandler((event) => {
  const cfCtx = event.context.cloudflare.context
  const taskId = Math.round(Math.random() * 1000)
  event.context.taskId = taskId
  let now = new Date()
  console.log('Time before backgroundTask : ' + now.toLocaleTimeString())
  cfCtx.waitUntil(backgroundTask(taskId))
  now = new Date()
  return `Task ${taskId} is running in background... : ${now.toLocaleTimeString()}`
})
```

**Comment by Eckhardt-D** [comment]
@atinux I'm not sure if this is related, but it seems that via NuxtHub this also causes issues with the cached endpoints and functions. I have a cached function with maxAge of 15s. I see the cache entries being created, but they are never updated / removed by Nitro if the `mtime` or `expires` date is past due, resulting in always seeing stale data. cc @pi0 

![image](https://github.com/user-attachments/assets/1f8d6b31-60c5-4d17-a22c-c579b28a8149)

**Comment by pi0** [comment]
Consider that CPU time [limits](https://developers.cloudflare.com/workers/platform/pricing/#workers) still applied to `waitUntil` task (10ms free / up to 30sec pair)

If CPU time for generating response + serialization + and KV update takes more than this, it won't update the cache entry.

This is not a bug with nitro but a runtime limitation.


PS: Please consider using `event.waitUntil`, it will directly call cloudflare `waitUntil` from the context and is universally available.
