### ISSUE TITLE
Define `import.meta.test` on test environmenet

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/nitro#2693]
### Describe the feature

Hello 👋,

Do you think it is a good idea to define `import.meta.test` like in Nuxt: https://github.com/nuxt/nuxt/blob/76f3ab400d0073eee31f2db68b66f1fb4709c701/packages/schema/src/config/vite.ts#L30

Is it a good practice?

related to https://github.com/johannschopplich/nitro-test-utils/blob/main/README.md?plain=1#L85 and https://github.com/johannschopplich/nitro-test-utils/pull/7

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
we can discuss it once nitro had an official testing system. it is not like nuxt.
