### ISSUE TITLE
Alias "@/*" cannot be resolved

### ISSUE THREAD

**Issue by chengzhuo5** [unjs/nitro#2705]
### Environment

nitropack@2.9.7

### Reproduction

1. Configure `tsconfig.json`: 
```json
{
"compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  }
}
```
2. Import a value with "@/*" alias in `routes` directory:
```ts
import xxx from '@/enum';
```
3. Run server with `pnpm dev`, and an error will be throwed:
```
"@/enum" is imported by "routes/test.ts", but could not be resolved – treating it as an external dependency.
[worker reload] Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@/enum' imported from D:\Code\nitro-test\.nitro\dev\index.mjs
```

### Describe the bug

I find the issue is caused by this line:
https://github.com/unjs/nitro/blob/78a5f9d364d005c29a218cc128a8485b8549ada5/src/rollup/config.ts#L398

`@rollup/plugin-alias` plugin will match alias in this way:
https://github.com/rollup/plugins/blob/8550c4b1925b246adbd3af48ed0e5f74f822c951/packages/alias/src/index.ts#L18
So the pattern should be `@` instead of `@/`.

`@@/` is the same:
https://github.com/unjs/nitro/blob/78a5f9d364d005c29a218cc128a8485b8549ada5/src/rollup/config.ts#L400

**Comment by pi0** [comment]
Please use `~/` alias instead. `@/` can conflict with npm package namespaces sadly and not guaranteed to work.
