### ISSUE TITLE
Nuxt app.baseURL is not replaced when forwarding proxy

### ISSUE THREAD

**Issue by drdevelop** [unjs/nitro#2708]
### Environment

nuxt: 3.13.0
node: 20.10.0

### Reproduction

defineNuxtConfig({
  nitro: {
    routeRules: {
      '/api/**': {
        proxy: {
          to: `${envData.VITE_API_PREFIX}/api/**`,
        },
      },
    },
  },
  app: {
    baseURL: '/h5/',
  },
})

### Describe the bug

frontend request url: /h5/api/test
forward final url: {forward host}/h5/api/test
expect forward url: {forward host}/api/test

```[tasklist]
### Tasks
```

**Comment by drdevelop** [comment]
![image](https://github.com/user-attachments/assets/e96c4ec1-7d44-42c4-b27e-96f9a71749e1)

**Comment by drdevelop** [comment]
Or can i submit a pull request?

**Comment by drdevelop** [comment]
@brandonroberts @Ky6uk @kasperkronborg @marshallswain Please take a look.

**Comment by pi0** [comment]
- Please do not ping the maintainers 
- Please report a new issue with a "Nitro" minimal reproduction
