### ISSUE TITLE
Durable Object support from h3 & crossws

### ISSUE THREAD

**Issue by vinayakkulkarni** [unjs/nitro#2727]
### Describe the feature

- work is done in crossws – https://github.com/unjs/crossws/pull/54#issuecomment-2337663758
- work yet to be done in h3 – https://github.com/unjs/h3/issues/880

Adding issue so we can reference it against PR

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Nitro will support a new cf-worker-durable preset once ready. It is apart from crossws upgrade which is an experimental feature.
