### ISSUE TITLE
Experimental typescript decorator support

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#273]
ESBuuild decorator support is not landed yet (https://github.com/evanw/esbuild/issues/104#issuecomment-1100130046). We can support an experimental flag to enable decorators using `rollup-plugin-typescript2`. Other solution is swc. (https://github.com/vitest-dev/vitest/issues/708#issuecomment-1118628479)

Reference: https://github.com/nuxt/nuxt.js/issues/14080

**Comment by itpropro** [comment]
What about supporting esbuild plugins and use [this plugin](https://www.npmjs.com/package/@anatine/esbuild-decorators) in the meantime?

**Comment by itpropro** [comment]
There is also another esbuild plugin that could be used:
https://github.com/thomaschaaf/esbuild-plugin-tsc

**Comment by pi0** [comment]
esbuild plugins are configurable. closing since stalled and not priority.

**Comment by Ttou** [comment]
use unplugin-swc

```ts
import swc from 'unplugin-swc'

export default defineConfig({
  rollupConfig: {
    plugins: [
      swc.rollup()
    ]
  }
})
```
