### ISSUE TITLE
ignore directory in url stucture (Route Groups)

### ISSUE THREAD

**Issue by Vestedmarius** [unjs/nitro#2756]
### Describe the feature

In Nuxt, when using pages its posible to ignore folder in the url of the app. This can be doen with a folder like `(name)`, i think it would be nice to have this option in Nitro aswell.  For more info see the [Nuxt docs](https://nuxt.com/docs/guide/directory-structure/pages#route-groups)

For example:
Directory: `api/admin/(ignored)/test.get.ts` URL: `api/admin/test`

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by carlos-duran** [comment]
It would be great if we could access groups from middleware. This way, we could create a (private) folder to easily protect routes within it.

**Comment by aarvinr** [comment]
This was just resolved with #1205 and #2664, and should be available with the next release.
