### ISSUE TITLE
How to set up nitro server

### ISSUE THREAD

**Issue by mik7up** [unjs/nitro#290]
### Environment

How to set up nitro server from nuxt like express with all packages like: csurf, helmet and cors.

### Reproduction

---

### Describe the bug

example of production ready app with all things set up

**Comment by eduardosada** [comment]
For anyone who wants to know how to implement cors with nitro:

```ts
// middleware/cors.ts
import cors from 'cors';

export default defineEventHandler(({ req, res }) => new Promise((resolve) => cors()(req, res, resolve)));
```

Or helmet or any express package:

```ts
// middleware/helmet.ts
import helmet from 'helmet';

export default defineEventHandler(({ req, res }) => new Promise((resolve) => helmet()(req, res, resolve)));
```
