### ISSUE TITLE
503 (server unavailable) for dynamic route params on Windows

### ISSUE THREAD

**Issue by Jclong98** [unjs/nitro#305]
### Environment

|software|version|
|--|--|
|nitropack|0.4.0 (latest)|
|Node.js|v16.14.0|
|Windows 11|21H2 (OS Build 22000.739)|

### Reproduction

https://stackblitz.com/edit/github-vzz459

### Describe the bug

When making lots of requests to a route that has a dynamic parameter, it will throw a `503 (Server Unavailable)` error. 

### Additional context

This only happens in windows environments. When using WSL or StackBlitz, this doesn't occur

![screenshot of error](https://i.imgur.com/Co5Xac3.png)

### Logs

```sh
Trace: null
    at devErrorHandler (C:\Users\jclon\Downloads\github-vzz459\nitro.config.ts:5:13)
    at Object.handler (file:///C:/Users/jclon/Downloads/github-vzz459/node_modules/nitropack/dist/chunks/prerender.mjs:2369:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Users/jclon/Downloads/github-vzz459/node_modules/h3/dist/index.mjs:420:19     
    at async Server.nodeHandler (file:///C:/Users/jclon/Downloads/github-vzz459/node_modules/h3/dist/index.mjs:370:7)
```
```

**Comment by Masutayunikon** [comment]
Same for me, did you fix it ?

**Comment by Jclong98** [comment]
> Same for me, did you fix it ?

No, I started working on something else sorry

**Comment by pi0** [comment]
Sorry for delay on this. I need to use my windows machine in order to debug and fix. PR for fix is more than welcome!

**Comment by Masutayunikon** [comment]
the only fix for the moment its to use wsl

**Comment by pi0** [comment]
Hi. I made a new tracker for this issue to investigate Tracking via https://github.com/unjs/nitro/issues/1454
