### ISSUE TITLE
503 Server Unavailable

### ISSUE THREAD

**Issue by kalaomer** [unjs/nitro#310]
### Environment

OS: Macos
Platform: Docker Compose
Version: 0.4.8
Nuxt Version: v3
External Modules: @nuxtjs/tailwindcss

### Reproduction

```
import {defineNuxtConfig} from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    modules: ['@nuxtjs/tailwindcss'],

    css: [
        'element-plus/dist/index.css',
        "@/assets/scss/main.scss"
    ],


    tailwindcss: {
        cssPath: '~/assets/scss/tailwind.scss',
        viewer: false,
    },

    build: {
        extractCSS: true,
    }
})
```

### Describe the bug

When I change file, hot reload fails and break the server.

CLI Command: nuxt dev --host=0.0.0.0 --port=8080

There is two thing may break the code, first tailwind integration and second custom port number. But actually which one is the main issue i couldn't get it.

<img width="1287" alt="Screen Shot 2022-06-23 at 00 19 02" src="https://user-images.githubusercontent.com/2925345/175139554-2c72eece-1f41-4c0a-aac1-d991230c2ffe.png">

![Screen Shot 2022-06-23 at 00 18 41](https://user-images.githubusercontent.com/2925345/175139698-75c093d8-973b-476e-9168-61360fcecbe7.png)

**Comment by pi0** [comment]
Hi again. I have made a new tracker for this issue https://github.com/unjs/nitro/issues/1454
