### ISSUE TITLE
Server doesn't properly restart

### ISSUE THREAD

**Issue by darklight9811** [unjs/nitro#376]
### Environment

nitropack: 0.4.12
node: 14.20.0

### Reproduction

Use something that persists through reloads (such as databases), in my case I used prisma, if create a server that has prisma, and reload (make a change in the code), the server will reload but won't answer any more requests.

### Describe the bug

The server reloads (the changes made) but requests stop working. From time to time the server crashes.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by darklight9811** [comment]
@danielroe hi, sorry for the lack of response. I'm really struggling with time right now so I can't provide a proper reproduction. It seems to trigger at random.

Those are my dependencies:
``` json
{
	"dependencies": {
		"@prisma/client": "^4.1.1",
		"nitropack": "^0.4.12",
		"ts-node": "^10.9.1"
	},
	"devDependencies": {
		"@types/node": "^18.6.2",
		"@typescript-eslint/eslint-plugin": "^5.12.1",
		"@typescript-eslint/parser": "^5.12.1",
		"eslint": "^8.20.0",
		"prisma": "4.0.0",
		"typescript": "^4.7.4"
	}
}
```

This is how I'm adding prisma:
``` typescript
import { PrismaClient } from "@prisma/client"

declare global {
	// eslint-disable-next-line no-var
	var prisma: PrismaClient | undefined
}

export const db = global.prisma || new PrismaClient()

if (process.env.NODE_ENV !== "production") global.prisma = db

```

I'm going to try to find some time to properly do a reproduction. Because its not an immediate bug too

**Comment by darklight9811** [comment]
From time to time it throws this error:
``` bash
error Command failed with exit code 3221225477.
```

**Comment by Lucky-Strike1695** [comment]
Can confirm the bug.
If prisma is connected to DB while server reloads, in hangs without error and stop responding to requests.
It has already been reported but not fixed : https://github.com/unjs/nitro/issues/257#issue-1248275871 (repro in linked post)

**Comment by chuahziyang** [comment]
having the exact same issue, can confirm that WSL works as a workaround in the meantime

**Comment by mubaidr** [comment]
For me, this occurs only on `windows` platform, never encountered this issue on `linux`. Maybe that is why `WSL` also works fine in this case. 

```bash
 ELIFECYCLE  Command failed with exit code 3221225477.
```

**Comment by manniL** [comment]
Closing as no reproduction was provided. Feel free to open a new issue with a reproduction if the problem still exists 👍🏻
