### ISSUE TITLE
Error building with `cloudflare`, `vercel-edge` or `netlify-edge` presets

### ISSUE THREAD

**Issue by maoosi** [unjs/nitro#378]
### Environment

- Node.js v16.14.2
- Nuxt 3.0.0-rc.6
- Nitropack 0.4.12

### Reproduction

[Click here to access reproduction on Stackblitz](https://stackblitz.com/edit/nitro-preset-cloudflare-issue?file=src/app.vue), then run the below command:

```shell
# working as expected
npm run build

# build errors
NITRO_PRESET=cloudflare npm run build
NITRO_PRESET=vercel-edge npm run build
NITRO_PRESET=netlify-edge npm run build
```

### Describe the bug

Nuxt3 build is failing when running with edge-related presets such as:

- `NITRO_PRESET=cloudflare`
- `NITRO_PRESET=vercel-edge`
- `NITRO_PRESET=netlify-edge`

### Additional context

Probably related to:

- https://github.com/unjs/nitro/issues/280.
- https://github.com/unjs/nitro/issues/293

### Logs

Example logs when using `NITRO_PRESET=cloudflare`:

```sh
ERROR  Rollup error: Cannot resolve "/home/projects/nitro-preset-cloudflare-issue/node_modules/unenv/runtime/node/stream/index/web.cjs" from "/home/projects/nitro-preset-cloudflare-issue/node_modules/cross-undici-fetch/dist/create-node-ponyfill.js" and externals are not allowed!

ERROR  Cannot resolve "/home/projects/nitro-preset-cloudflare-issue/node_modules/unenv/runtime/node/stream/index/web.cjs" from "/home/projects/nitro-preset-cloudflare-issue/node_modules/cross-undici-fetch/dist/create-node-ponyfill.js" and externals are not allowed!
```

**Comment by warflash** [comment]
#293 is probably also be related. Seems like unfortunately the cloudflare preset is pretty dead at the moment

**Comment by maoosi** [comment]
I've edited my initial post to include #293. I also noticed the same issue with `NITRO_PRESET=vercel-edge`, so this issue is probably affecting all edge-related presets.

**Comment by warflash** [comment]
@maoosi Did you get a chance to verify the fix yet? I just updated my nuxt brige app to use nitro 0.4.18 and am still running into the same rollup `externals not allowed` error on edge presets. Wondering if I'm experiencing something unrelated or if the error still persists

**Comment by danielroe** [comment]
The original reproduction (linked above) is now succeeding: https://stackblitz.com/edit/nitro-preset-cloudflare-issue-yxjhpg. I can't speak to your project @warflash but you are welcome to open a new issue with a reproduction and I'll be very happy to look into it.

**Comment by warflash** [comment]
Oh right, I missed the repro link, sorry about that. Opened #410, thanks for taking a look! 💯
