### ISSUE TITLE
SWR behaviour

### ISSUE THREAD

**Issue by dave-calleja** [unjs/nitro#379]
### Environment

- Node v14
- nitopack 0.4.12

### Reproduction

Tried the following cache response.

```
export default cachedEventHandler(async (event) => {
    await new Promise(resolve => setTimeout(resolve, 5000));
    return `Response generated at ${new Date().toISOString()}`
  }, { swr: true, maxAge: 10 })
  ```

### Describe the bug

I may have misunderstood the functionality of SWR so please excuse this issue if that is the case. I was under the impression that nitro would serve cached data, revalidate in the background and serve the updated cached response. Currently the `swr` does not appear to affect functionality (although it does add the correct cache headers). I still hit the 5s loading delay every 10 seconds.

### Additional context

Cache config is using `fs`

**Comment by pi0** [comment]
Hi. If you have issues with latest nitro v2 feel free to open a fresh issue 🙏🏼
