### ISSUE TITLE
Cloudflare `request.cf`

### ISSUE THREAD

**Issue by jjjrmy** [unjs/nitro#391]
I'd like to be able to access the [Incoming Request CF Properties](https://developers.cloudflare.com/workers//runtime-apis/request#incomingrequestcfproperties)

**Comment by pi0** [comment]
Latest unenv contains a fix that allows accessing raw event object. As a temporary workaround, you can access it using `event.node.req.__unenv__.event.request.cf` (requires fresh lock)
