### ISSUE TITLE
swagger API

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#4]
expose swagger compatible API from dev server based on handler defenitions.

**Comment by BracketJohn** [comment]
Quoting from https://github.com/nuxt/framework/discussions/4582:

> [..] swagger UI is a great feature for newcomers, product managers and smoke-testing (:

So would really love to see this - with the correct pointers I'd even try myself on it, but am unsure if this is a good first issue.

**Comment by septatrix** [comment]
Is the whole `/server/api` of Nuxt 3 mostly handled by nuxt or nitro? ...if nitro only has access to the routes and url arguments but not the return type or similar it would make little sense to implement it inside nitro.

**Comment by sannajammeh** [comment]
Is there any more work being done on this? Could it be possible to export a json schema or zod type to reflect what the endpoint is returning in the OpenAPI spec?

**Comment by pi0** [comment]
Currently it is exposed via experimental flag as `/_nitro/openapi.json`. So you can use it already.

It is in our roadmap after introducing route meta support to improve this feature and iterate.

**Comment by MrlolDev** [comment]
how can you modify the tags?

**Comment by chenyuncai** [comment]
is there any way to support nested route. Api need to be grouped in most case.

**Comment by pi0** [comment]
@chenyuncai feel free to open new individual issue for it 👍🏼 (or any other idea related to openapi)
