### ISSUE TITLE
Cannot prerender with service-worker presets

### ISSUE THREAD

**Issue by farnabaz** [unjs/nitro#452]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8-27698890.b90d286`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-bqru3d?file=nuxt.config.ts

### Describe the bug

When using service worker presets nitro fails to pretender API routes.
<img width="660" alt="Screenshot 2022-08-31 at 15 16 28" src="https://user-images.githubusercontent.com/2047945/187687310-3d886250-70a3-4f47-bccd-6ed715ce6282.png">

Seems that `route.contents` object in `prerender:generate` hook is readonly

https://github.com/unjs/nitro/blob/3aa3bcfef4b98528db6b31d620177a57a69afdf4/src/presets/service-worker.ts#L52-L55

See: 
https://github.com/unjs/nitro/blob/d1d1015228f5297741951e596079900816241f50/src/prerender.ts#L60-L67

**Comment by pi0** [comment]
Thanks for reporting early. Should be resolved in last edge
