### ISSUE TITLE
Using `storage` does not register files for build process

### ISSUE THREAD

**Issue by manniL** [unjs/nitro#485]
### Environment

Node: LTS
Nitro: 0.5.1

### Reproduction

1. Clone https://github.com/manniL/nitro-485
2. Run `pnpm i --shamefully-hoist`
3. Run `pnpm dev`
4. See `{  "data": "This is a test file" }`
5. Run `pnpm build`
6. Run `node .output/server/index.mjs`
7. See same result (still)
8. Run `pnpm build:vercel` and see that there is no `test.mjs` generated
9. Alternative: deploy to Vercel, see `{ "data": null }`
10. Comment in the `serverAssets` part in `nitro.config.ts`
11. Run `pnpm build:vercel` and see that there is a `test.mjs` now
12. Alternative: deploy to Vercel, see correct result

### Describe the bug

When using `storage` in the `nitro.config.ts`, the corresponding files are not registered to be processed when building for platforms like e.g. vercel. That means, using them via `useStorage` creates a different result between dev (and normal server preset) vs. Vercel preset (or any other platform I suppose).

### Additional context

Is that behavior intended?

**Comment by keisanng** [comment]
Same issue here deploying to Netlify.

**Comment by TutorFx** [comment]
Same issue here.

------------------------------
- Operating System: Windows_NT
- Node Version:     v21.6.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.13.1
- Builder:          -
- User Config:      modules, i18n, routeRules, experimental, colorMode, googleFonts, runtimeConfig, nitro, ogImage, app, pinia, typescript, site, devtools, eslintConfig, content, tailwindcss
- Runtime Modules:  nuxt-build-cache@0.1.1, nuxt-site-config@2.2.12, nuxt-speedkit@3.0.0-next.51, @nuxtjs/seo@2.0.0-rc.10, @nuxtjs/sitemap@5.1.4, @vueuse/nuxt@10.9.0, @pinia/nuxt@0.5.1, @nuxtjs/i18n@8.3.0, @nuxtjs/color-mode@3.3.3, @nuxtjs/tailwindcss@6.11.4, @nuxtjs/google-fonts@3.2.0, @nuxt/image@1.5.0, @nuxt/content@2.12.1, @nuxthq/studio@1.0.13, nuxt-module-eslint-config@0.1.1, nuxt-icon@0.6.10
- Build Modules:    -
------------------------------

**Comment by pi0** [comment]
`serverAssets` is probably the right way to bundle assets for universal production.

While we can try to improve mounts to handle relative paths better, it is not always predictable about deployment target fs support or relative path handling...
