### ISSUE TITLE
improve heroku preset

### ISSUE THREAD

**Issue by danielroe** [unjs/nitro#49]
heroku is very customisable but mostly this is done with buildpacks. Here's [the node one](https://devcenter.heroku.com/articles/nodejs-support).

By default the node buildpack will build, prune dev dependencies + package the entire app folder into a docker image. This is lots more space than Nitro needs. Options:

1. create our own heroku buildpack
2. create docker image (which can be shared with other platforms): https://github.com/unjs/nitro/issues/54

If you use the default heroku buildpack, you'll need to run `heroku config:set HOST=0.0.0.0`

**Comment by danielroe** [comment]
heroku is very customisable but mostly this is done with buildpacks. Here's [the node one](https://devcenter.heroku.com/articles/nodejs-support).

By default the node buildpack will build, prune dev dependencies + package the entire app folder into a docker image. This is lots more space than Nitro needs. Options:

1. create our own heroku buildpack
2. create docker image (which can be shared with other platforms)

**Comment by Hebilicious** [comment]
@danielroe Can you confirm that this issue is still open to optimise the Heroku preset ?

**Comment by pi0** [comment]
Considering it is an unattended issue for long time and we have a working preset, closing this tracker. [docker support](#54) might allow improving Heroku preset too.
