### ISSUE TITLE
digital ocean preset

### ISSUE THREAD

**Issue by danielroe** [unjs/nitro#50]
## Usage notes/documentation:

1. Need to add `engines.node` version to `package.json` ([docs](https://docs.digitalocean.com/products/app-platform/languages-frameworks/nodejs/#node-version))
2. set `HOST` to `0.0.0.0`

also supports docker images: https://github.com/unjs/nitro/issues/54

**Comment by pi0** [comment]
Let's iterate over later for docker support.
