### ISSUE TITLE
user-set preset in config is ignored

### ISSUE THREAD

**Issue by danielroe** [unjs/nitro#501]
### Environment

this repository

### Reproduction

Try setting `preset: vercel` in the playground and run `pnpm nitro build playground`.

### Describe the bug

If not specified in environment variable, `node-server` will always override any user preset config.

Related: https://github.com/unjs/nitro/pull/495 and https://github.com/nuxt/framework/issues/7459.

**Comment by pi0** [comment]
Working on it. Preset resolving got little bit complex to support external presets in latest 0.5.x
