### ISSUE TITLE
split aws lambda into multiple presets 

### ISSUE THREAD

**Issue by danielroe** [unjs/nitro#505]
Context: https://github.com/unjs/nitro/pull/357#issuecomment-1247562089, https://github.com/unjs/nitro/issues/504

Currently we cover AWS v1, AWS v2 and Netlify, but not all responses are valid between the different versions.

(We could also return different returns based on detecting the type of the request.)

**Comment by pi0** [comment]
with new structure, we can actually do this flexibly if we need + new netlify is not using lambda syntax anymore.
