### ISSUE TITLE
Port/Pipe binding for windows server

### ISSUE THREAD

**Issue by alimozdemir** [unjs/nitro#507]
### Environment

- Node LTS
- Nuxt3-rc10
- Nitro 0.5.3

### Reproduction

[Reproduce link ](https://github.com/alimozdemir/nitro_pipe_port)

### Describe the bug

This is a problem in an azure app service.  Our app was working with Nuxt3 rc8 and yesterday I have updated it to rc10. After that, it stopped working. And the error message was like this.

```
RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received \\.\pipe\22da0d35-ff9f-4b64-90ee-d606ecb2dbc7.
    at new NodeError (node:internal/errors:371:5)
    at validatePort (node:internal/validators:216:11)
    at Server.listen (node:net:1461:5)
    at file:///D:/home/site/wwwroot/.output/server/chunks/nitro/node-server.mjs:1352:18
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
```

I first thought the port was wrong and I needed to set it to some kind of numeric value like 3000, 8080 but it didn't solve the problem. The app was okay it was working but it was not exposed in the azure app service I was getting 500 internal server error.  After some research, I found there is a thing called a "pipe" for windows e.g. [Source](https://docs.microsoft.com/en-us/windows/win32/ipc/named-pipes) And it is assigned to "PORT" environment variable.

So I dig into the problem, and the problem was about a change in "server.listen" part. 

Nuxt3-rc8 was using nitro 0.4.0 and it was 

https://github.com/unjs/nitro/blob/6e1a0e732c93e0d2cf23cc08a364aad260593b59/src/runtime/entries/node-server.ts#L17

in the 0.5.3

https://github.com/unjs/nitro/blob/5c302975c1180c56c682d83aea8a34dc445218ff/src/runtime/entries/node-server.ts#L18

The major change was the "listen" part. 

Here are the things that get interesting. In the old function, it was treated as a pipe and in the second one, it was treated as a numeric port. You can see the code below it looks for the first argument of the function and check if it is a "pipe" or not. 

https://github.com/nodejs/node/blob/5c77d7723e0602123bffce991ff74b3bfacd23cc/lib/net.js#L240

Maybe there could be a feature flag to use the pipe or not and switch between the "listen" methods.  Until then we will stay with rc8 to make it work.

**Comment by danielroe** [comment]
cc: @pi0

**Comment by pi0** [comment]
Thank you so much for nice pointers @alimozdemir 💯 I think best would be revert the change back to let node handle port for now.

**Comment by tolgahanbeyazoglu** [comment]
@alimozdemir problem çözümleme yapabilrdinizmi bende projemi 3.7.1 versiyonunda IIS yayınlamak istedim bu hatayla karşılaştım

**Comment by alimozdemir** [comment]
@tolgahanbeyazoglu yaptıkları değişikliği revert ettiklerinde çözülmüştü, şuan için artık Windows kullanmıyorum. Bunun gibi bir kaç sorun daha yaşadığım için hem de daha uygun olduğu için linux'a geçtim.

**Comment by tolgahanbeyazoglu** [comment]
@alimozdemir  şuan problem yaşıyorum çözüm için onlardan adım beklemeliyim her alde

**Comment by fabianwohlfart** [comment]
I have the same problem that my environment gives me a socket, put the port should be a number.
How to solve this in Nuxt?
