### ISSUE TITLE
Generated package.json is not valid

### ISSUE THREAD

**Issue by TheDutchCoder** [unjs/nitro#508]
### Environment

Node: v16.15.1
Nitro: 0.5.3

### Reproduction

Probably doesn't need a reproduction, but let me know if I need to supply a Stackblitz or GH repro

### Describe the bug

When using the `aws-lamda` preset (probably goes for other ones too), the generated package.json is missing the required fields `name` and `version`, which means that deploying the code through (for example) SAM fails.

Maybe the name and version could be grabbed from the root's package.json?

**Comment by pi0** [comment]
Hi @TheDutchCoder. I think the package.json is valid with `private: true` field to omit name an version and it is only a placeholder meta file. What exact error are you getting?

**Comment by pi0** [comment]
BTW surely we can add placeholder name and version to the file as well 👍🏼

**Comment by TheDutchCoder** [comment]
This probably comes from some form of validator on the AWS side, which (I think) assumes the package is a publishable one.

I can't find any docs that say `private: true` make name and version _not _ required, but I also can't find any docs that they _are_ required when setting `private: true` haha.

NPM themselves mark name and version as required: https://docs.npmjs.com/creating-a-package-json-file so I _think_ that's what the AWS validator uses as a base.

I'm more than willing to PR this, but I couldn't find the root's imported package.json in the code that generates the output package.json. I think it might be a good idea to grab the name and version from the root's file, with backup values in case they're missing?

**Comment by TheDutchCoder** [comment]
Yeah that sounds good, do you want me to PR it?
