### ISSUE TITLE
render.com preset

### ISSUE THREAD

**Issue by danielroe** [unjs/nitro#52]
Looks like render.com does not have a separate setup for serverless/edge rendering: https://render.com/docs/web-services.

Setting up render was super-simple, and took only 30 sec. or so from creating an account to connecting the repository. This may just be a documentation task. (It deploys as a node server within a docker container.)

cc: @Atinux

**Comment by Atinux** [comment]
Indeed render.com is similar to Heroku so should be straightforward :grinning:

**Comment by pi0** [comment]
@danielroe Since we have the preset, do you mind helping to add basic deployment docs? https://nitro.unjs.io/deploy/providers/render.html
