### ISSUE TITLE
deno deploy preset

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#53]
Supporting deno deploy: https://dash.deno.com/

It is actually almost possible via worker preset! We only need documentation and an official preset.

**Comment by DaZiYuan** [comment]
I can't wait to use nuxt3 on deno deploy, if possible please add documentation soon.

**Comment by so1ve** [comment]
Hi, has this function been implemented?

**Comment by BoxenOfDonuts** [comment]
In case anyone else runs into issues with static assets not loading when using the deno deploy preset, it appears it has been fixed in #694 and is not yet in stable.
