### ISSUE TITLE
Support mixing dynamic params with static string in same segment 

### ISSUE THREAD

**Issue by SilentDepth** [unjs/nitro#532]
### Environment

Nitro: 0.5.4
Node: 16.14.2

### Reproduction

https://stackblitz.com/edit/nitro-8ovcqq?file=routes/one/%5Ba%5D.json.ts

#### `/routes/[a].json.js`
**URL:** `/foo.json`
**Expected params:** `{ "a": "foo" }`
**Actual params:** `{ "a.json": "foo.json" }`

#### `/routes/[a]-[b].js`
**URL:** `/foo-bar`
**Expected params:** `{ "a": "foo", "b": "bar" }`
**Actual params:** `{ "a-:b": "foo-bar" }`

#### `/routes/hello-[a].js`
**URL:** `/hello-foo`
**Expected params:** `{ "a": "foo" }`
**Actual response:** 404

**Comment by pi0** [comment]
Upstream issue https://github.com/unjs/radix3/issues/11

**Comment by pi0** [comment]
Let's track from upstream nothing much to track here or we can shortfix.
