### ISSUE TITLE
Possibility to change api and middleware paths

### ISSUE THREAD

**Issue by n4an** [unjs/nitro#541]
### Environment

---

### Reproduction

[handlers](https://nitro.unjs.io/config#handlers)
Server handlers and routes.
If routes/, api/ or middleware/ directories exist, they will be automatically added to the handlers array.

How to modify api and middleware paths?

### Describe the bug

---

**Comment by danielroe** [comment]
Would you explain a bit more about your use case? And if you rename `api/` to `something-else/` would you still expect that it would be accessed via the `/api` prefix when served by nitro?

**Comment by n4an** [comment]
That also can be configurable with global prefix option https://docs.nestjs.com/faq/global-prefix

**Comment by n4an** [comment]
And that looks ugly 

```
defineEventHandler((event) => {
if (event.method === 'get') {
} else if (event/method === 'post') {
}
})
```

but can be like so

```
@Controller('cats')
export class CatsController {
  @Get()
  findAll(): string {
    return 'This action returns all cats';
  }
}
```

**Comment by danielroe** [comment]
You also have the option to use `something.get.ts` and `something.post.ts`.

**Comment by n4an** [comment]
> You also have the option to use `something.get.ts` and `something.post.ts`.
I know

**Comment by danielroe** [comment]
That is not related to this issue, and I do not believe we are likely to implement a pattern with decorators in https://github.com/unjs/h3.

**Comment by itpropro** [comment]
> And that looks ugly
> 
> ```
> defineEventHandler((event) => {
> if (event.method === 'get') {
> } else if (event.method === 'post') {
> }
> })
> ```
> 
> but can be like so
> 
> ```
> @Controller('cats')
> export class CatsController {
>   @Get()
>   findAll(): string {
>     return 'This action returns all cats';
>   }
> }
> ```
> 
> All speak about OOP

Looks overcomplicated to me, I think using the `something.get.ts` and `something.post.ts` pattern is fine, didn't have any problems with that in projects so far.
For the initial question, you can just create a folder in the `/routes` folder, as the `/api` folder is also just a shortcut to `/routes/api`.

**Comment by pi0** [comment]
#1763
