### ISSUE TITLE
docs: missing overflow-y scroll on configuration table of content

### ISSUE THREAD

**Issue by huang-julien** [unjs/nitro#556]
### Environment

https://nitro.unjs.io/config

### Reproduction

https://nitro.unjs.io/config

### Describe the bug

Hi, i did not verify which component yet but the sidebar on the configuration page is missing a scrollbar (with an auto scroll ?). We need to scroll all the way down manually to the see the endpart of the sidebar (such as hooks, entry, commands ....)

### Additional context

![image](https://user-images.githubusercontent.com/63512348/194820685-3ab49475-3b8d-4652-90e2-e4802b2334ac.png)

**Comment by pi0** [comment]
Hi, this should be fixed.
