### ISSUE TITLE
Migrate to rollup v3 

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#569]
https://github.com/rollup/rollup/releases/tag/v3.0.0

**Comment by itpropro** [comment]
Are there any plans to merge the PR @pi0 ? I am using import assertions in some projects, which are only supported from rollup 3 upwards.

**Comment by pi0** [comment]
Hi @itpropro. Since we want to align this upgrade with Vite and Nuxt3, trying to upgrade after Nuxt 3 rc.13 (today) and a semver-minor release of nitropack.

**Comment by itpropro** [comment]
Sounds right around the corner, thanks for the update :)
