### ISSUE TITLE
Nitro entry missing for the cleavr preset

### ISSUE THREAD

**Issue by anishghimire862** [unjs/nitro#600]
Running the build command `NITRO_PRESET=cleavr npm run build --production` we're encountering an error with the following message:

 `ERROR  Nitro entry is missing! Is "cleavr" preset correct?` 

Please check the gist file for the full log https://gist.github.com/anishghimire862/9bc8964aecad9d26dc0ab3fdb9b7ebe2

This must be due to the missing entries. We added the preset but somehow forgot about the entries.

**Comment by pi0** [comment]
I think this is because `cleavr` is not exported from PRESETS? (https://github.com/unjs/nitro/blob/main/src/presets/index.ts)

Also do you expect a (req, res) export from entry or that entry runs server itself? (node-server entry does)

**Comment by anishghimire862** [comment]
Hello @pi0,

The entry should run the server itself.  I'll remove the entry file that I've added and export `cleavr` from presets. 

Thank you for the help.
