### ISSUE TITLE
Unable to build nuxt for cloudflare workers with pnpm

### ISSUE THREAD

**Issue by oleghalin** [unjs/nitro#611]
### Environment

Node 18
Nitro 0.6.0

### Reproduction

NITRO_PRESET=cloudflare pnpm run build
npx wrangler publish

### Describe the bug

When it uploads to cloudflare throws error 

```
 Cannot destructure property 'createComponentInstance' of 'Dn.ssrUtils'
```
Same error face when try to run in local mode. (If i build it with yarn everything looks great)

**Comment by Twitch0125** [comment]
I had a similar issue but with Nitro 2.1.1
I had to reinstall with `pnpm install --shamefully-hoist=true`, then it built correctly.

**Comment by oleghalin** [comment]
Shameful hoist "fixes" it

**Comment by manniL** [comment]
This is necessary for PNPM regardless of the environment :)

**Comment by pi0** [comment]
Note: Nitro does not needs shamefully hoist it is fully compatible. Also Nuxt without router is semi working i hope rest of issues specially with multi-vue instance get solved some day....

**Comment by manniL** [comment]
> Note: Nitro does not needs shamefully hoist it is fully compatible with pnpm! Also Nuxt without router is semi working i hope rest of issues specially with multi-vue instance get solved some day....

Sorry, had the wrong repo in mind. 🙈

**Comment by oleghalin** [comment]
> Note: Nitro does not needs shamefully hoist it is fully compatible with pnpm! Also Nuxt without router is semi working i hope rest of issues specially with multi-vue instance get solved some day.... 

Yeah, basically this problem was related exactly to nuxt project only
