### ISSUE TITLE
[plugins] No way to pass options to Nitro plugins

### ISSUE THREAD

**Issue by steveworkman** [unjs/nitro#622]
### Describe the feature

Whilst working on https://github.com/prashantpalikhe/nuxt-ssr-lit I want to create a nitro plugin that hooks onto `render:html`. To do this, I can make a plugin, but I can't pass any parameters to it (such as the Lit elements that I want to custom render).

Ideally, there would be a way to pass options to these plugins in a factory pattern, similar to how Rollup/Vite has its plugins

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by danielroe** [comment]
You can do something like this: https://github.com/nuxt-modules/html-validator/blob/main/src/module.ts#L29-41.

**Comment by 1aron** [comment]
> You can do something like this: https://github.com/nuxt-modules/html-validator/blob/main/src/module.ts#L29-41.

Maybe the way this option is passed limits the ability to have multiple instantiations of the same plugin?
We also encountered this problem when integrating Master CSS with Nuxt.

There's no good way to handle customization options besides virtual mods.
```js
import { renderHTML } from '@master/css'
import type { NitroAppPlugin, RenderResponse } from 'nitropack'

export default <NitroAppPlugin>async function (nitro) {
    nitro.hooks.hook('render:response', async (response: RenderResponse, { event }) => {
        if (typeof response.body === 'string' && (response.headers['Content-Type'] || response.headers['content-type'])?.includes('html')) {
            response.body = renderHTML(response.body)
        }
    })
}
```
We can only give up on creating a Nuxt Module package for now.
```diff
- export default defineNuxtConfig({
-     modules: [
-         '@master/css-server.nuxt'
-     ]
- })
```
Thus using a poorer experience to initialize Nitro plugins:
```js
// server/plugins/css.ts ( manually )

import { createCSSServerPlugin } from '@master/css.nitro'
import config from '../../master.css.ts'

export default createCSSServerPlugin({ config })
```

**Comment by pi0** [comment]
You might use either `runtimeConfig` or a virtual file (`vfs` config) to pass through config to nitro plugins.

In case having any further questions related to Nitro-side feel free to use the Discussions 🙏🏼
