### ISSUE TITLE
devProxy add wildecard support

### ISSUE THREAD

**Issue by mgd216** [unjs/nitro#636]
### Describe the feature

The devProxy feature was just added to Nitro which is great.  However, when I'm using Nuxt3, I want to be able to add this config to the nuxt.config.ts:
```
nitro: {
devProxy: {
  '/api/**': {target: 'http://my-dev-api-server:4040/api', changeOrigin: true}
}
}
```
This is similar to the routeRules configuration.  The devProxy works by hard coding each route, for example:
```
nitro: {
devProxy: {
  ...
  '/api/release/latest': {target: 'http://my-dev-api-server:4040/api/release/latest', changeOrigin: true}
  ...
}
}
```
I have over 240 routes in my application, so a wildcard on /api/** would be extremely helpful.  Thanks!

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi dear @mgd216. Actually it works like this without specifying `/**`. Dev proxy will be registers as a middleware with key as **prefix**:

```ts
    devProxy: {
      '/api': { target: 'https://example.com', changeOrigin: true }
    }
```

This handles http://localhost:3000/api/foo/bar/baz too


However, for consistency it wouldn't be a bad idea to normalize keys and remove `/**^` from paths.

**Comment by mgd216** [comment]
Awesome.... I thought I had tried that, sure enough I had a typo in my target.  I saw the documentation on routeRules regarding 'api/**' and thought it was seomthing missing from devProxy.

Again, works great, thank you for the quick response.
