### ISSUE TITLE
`$fetch` type-safety for calling other Nitro endpoints

### ISSUE THREAD

**Issue by manniL** [unjs/nitro#646]
### Describe the feature

Hey! It might be a far fetch, but sometimes, one nitro endpoint calls another one via `$fetch` (e.g. a Nuxt server route calling an API endpoint). Would it be possible to achieve `$fetch` type-support here too?

Opening in this repo instead of the nuxt framework repo because it could be supported for all nitro setups.

https://stackblitz.com/edit/unjsnitroissues646?file=routes%2Findex.ts,routes%2Fabout.ts

<img width="737" alt="image" src="https://user-images.githubusercontent.com/640208/200802735-22ac93d8-a7db-44bf-a85f-86036a9a8d90.png">

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by danielroe** [comment]
This should work already. Would you give an example of it not working?

**Comment by manniL** [comment]
Yes, sure! StackBlitz attached, tested locally.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/640208/200802735-22ac93d8-a7db-44bf-a85f-86036a9a8d90.png">

**Comment by pi0** [comment]
It seems to be working in latest nitro

<img width="366" alt="image" src="https://github.com/unjs/nitro/assets/5158436/d4207ef3-d9e2-4506-a899-e12a3eed4fba">
 

please feel free to reopen if can reproduce.
