### ISSUE TITLE
Unable to get query when using netlify-builder preset

### ISSUE THREAD

**Issue by so1ve** [unjs/nitro#660]
### Environment

Nuxt 3.0.0-rc.13 with Nitro 0.6.1, Node 16.18.1.

### Reproduction

Repo: https://github.com/so1ve/nuxt-netlify-builder-query-repro
Online: https://bespoke-praline-c7de7b.netlify.app/api?s=1

### Describe the bug

The Query in the URL should be obtained instead of a blank object.
It seems that netlify-builder can only get the url that does not include query?

**Comment by danielroe** [comment]
When using the builder preset, as when prerendering a page, queries are ignored.

**Comment by so1ve** [comment]
Thanks for your reply!
