### ISSUE TITLE
When using service-worker preset, process.env and import.meta.env should be inlined

### ISSUE THREAD

**Issue by so1ve** [unjs/nitro#663]
### Environment

Nuxt 3.0.0-rc.13 with Nitro 0.6.1, Node 16.18.1.

### Reproduction

N/A

### Describe the bug

When using the service-worker preset, I see the sw.js imports server.mjs directly. Process.env is preserved, but obviously, there is no process.env in the browser.

**Comment by pi0** [comment]
This is to allow shimming. virtual `process.env` in browser is empty.
