### ISSUE TITLE
[preset: firebase] Allow setting of memory allocation for Firebase functions

### ISSUE THREAD

**Issue by Sandlens** [unjs/nitro#666]
### Describe the feature

I would like to be able to set the memory allocation and timeout for Firebase functions generated by Nitro. For Nuxt, Nitro generates the `server` function which is used for SSR.

The default memory allocation for Firebase functions is 256MB, however this results in poor performance and slow loading for SSR Nuxt applications. I would like to be able to increase this memory allocation to improve application speed.

As per [Firebase documentation](https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation), this is normally done by setting `Runtime Options` within the `runWith` parameter. However, as far as I can tell, we do not have the ability to modify these currently. I would like these settings exposed on the Nitro API if possible.

Note that it is currently possible to change the memory allocation in the Google Cloud Console, but every time the Nitro Firebase functions are built and deployed, the memory allocation is reset to the default (256MB). This is probably because the `Runtime Options` are not specified in the source code.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Sandlens** [comment]
Workaround using "replace": https://github.com/unjs/nitro/issues/90#issuecomment-1430548908

**Comment by Hebilicious** [comment]
Should be fixed by https://github.com/unjs/nitro/pull/1142
