### ISSUE TITLE
Azure functions We are not awaiting readAsset 

### ISSUE THREAD

**Issue by mcremer-able** [unjs/nitro#669]
### Environment

Nuxi 3.0.0-rc.13                                                                                                                                                                     19:19:41  
Nuxt 3.0.0-rc.13 with Nitro 0.6.1   
node v16.03

### Reproduction

-

### Describe the bug

In https://github.com/unjs/nitro/blob/72c912e75b32b851bfebd2c5b9b289fa7ae86a6d/src/rollup/plugins/public-assets.ts#L55
We are returning a promise to read a file and not the file itself.
so in https://github.com/unjs/nitro/blob/72c912e75b32b851bfebd2c5b9b289fa7ae86a6d/src/runtime/static.ts#L90
We return a Promise as well.
This causes static assets not to work.
This might me specific to the `azure-function` preset

This causes assets to not to show up correctly or get downright rejected by the sanitizer for the incorrect file size
![grafik](https://user-images.githubusercontent.com/102793246/202264482-905edb07-3683-4adb-a9ff-8ef6d1d4e978.png)

### Additional context

If I go in to the compiled js files and modify the runtime/static.ts file, then it does work again.
I make the handler _async_ and _await_ the read operation.

```js
const _f4b49z = eventHandler(async (event) => {
  if (event.req.method && !METHODS.includes(event.req.method)) {
    return;
  }
  let id = decodeURIComponent(withLeadingSlash(withoutTrailingSlash(parseURL(event.req.url).pathname)));
  let asset;
  const encodingHeader = String(event.req.headers["accept-encoding"] || "");
  const encodings = encodingHeader.split(",").map((e) => EncodingMap[e.trim()]).filter(Boolean).sort().concat([""]);
  if (encodings.length > 1) {
    event.res.setHeader("Vary", "Accept-Encoding");
  }
  for (const encoding of encodings) {
    for (const _id of [id + encoding, joinURL(id, "index.html" + encoding)]) {
      const _asset = getAsset(_id);
      if (_asset) {
        asset = _asset;
        id = _id;
        break;
      }
    }
  }
  if (!asset) {
    if (isPublicAssetURL(id)) {
      throw createError({
        statusMessage: "Cannot find static asset " + id,
        statusCode: 404
      });
    }
    return;
  }
  const ifNotMatch = event.req.headers["if-none-match"] === asset.etag;
  if (ifNotMatch) {
    event.res.statusCode = 304;
    event.res.end();
    return;
  }
  const ifModifiedSinceH = event.req.headers["if-modified-since"];
  if (ifModifiedSinceH && asset.mtime) {
    if (new Date(ifModifiedSinceH) >= new Date(asset.mtime)) {
      event.res.statusCode = 304;
      event.res.end();
      return;
    }
  }
  if (asset.type && !event.res.getHeader("Content-Type")) {
    event.res.setHeader("Content-Type", asset.type);
  }
  if (asset.etag && !event.res.getHeader("ETag")) {
    event.res.setHeader("ETag", asset.etag);
  }
  if (asset.mtime && !event.res.getHeader("Last-Modified")) {
    event.res.setHeader("Last-Modified", asset.mtime);
  }
  if (asset.encoding && !event.res.getHeader("Content-Encoding")) {
    event.res.setHeader("Content-Encoding", asset.encoding);
  }
  if (asset.size && !event.res.getHeader("Content-Length")) {
    event.res.setHeader("Content-Length", asset.size);
  }
  return await readAsset(id);
});
```

**Comment by Hebilicious** [comment]
@mcremer-able Could you provide a reproduction please ?

**Comment by danielroe** [comment]
I think we can close this as there is no reproduction. If you are still experiencing this, would you provide a reproduction? 🙏
