### ISSUE TITLE
The public folder is not accessible at root of server with Cloudflare Pages

### ISSUE THREAD

**Issue by luzzardik** [unjs/nitro#673]
### Environment

Using Nuxt 3.0.0; Node.js 16.13.1

### Reproduction

Create a blank project with Nuxt 3, add images to "public/" and publish to Cloudflare Pages using environment variables "NITRO_PRESET=cloudflare_pages".

### Describe the bug

The files added to public/ will not be accessible from the server root.

**Comment by luzzardik** [comment]
I'm trying using ".output/public" as a root directory, it may be the issue.

**Comment by luzzardik** [comment]
It was just a configuration error, without using Wrangler and using Git Connect, this parameter has to be set correctly !

**Comment by YankeeTube** [comment]
@luzzardik I set it the same as you, but functions don't work for me.

**Comment by luzzardik** [comment]
@YankeeTube 
Make sure you have such settings:

BUILDS & DEPLOYMENTS
Build command - npm run build
Build output directory - /.output/public
Root directory - /

ENVIRONMENT VARIABLES
NITRO_PRESET = cloudflare_pages
NODE_VERSION = 16.13.1 (seems to be the only one to work on Pages)
