### ISSUE TITLE
Type NitroError and expose it

### ISSUE THREAD

**Issue by qnp** [unjs/nitro#688]
### Describe the feature

In our (nuxt3) app, we handle many errors from our event handlers. These are of that shape: https://github.com/unjs/nitro/blob/a31db233a73cf55cbd58119a0cd4b93bf12c259f/src/runtime/error.ts#L20

I think it would be very useful to expose an interface `NitroError`:
```ts
export interface NitroError {
    url: string;
    statusCode: number, // or HttpStatusCode if you would type it
    statusMessage: string;
    message: string;
    stack?: string[];
}
```

what do you think ?
I can make the PR, I only need guidance on where I put that interface.

Best regards

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
We already have `H3Error` from h3 that acts as kinda standard server error format.

Feel free to reopen if you belive we could benefit from a Nitro-specific error wrapper also.

**Comment by qnp** [comment]
Indeed, `H3Error` is enough. Thanks for you reply
