### ISSUE TITLE
`nitro prepare` command

### ISSUE THREAD

**Issue by sasial-dev** [unjs/nitro#695]
### Describe the feature

A `nitro prepare` command, similar to the `nuxt prepare` command to add the type studs/tsconfig.json in the `.nitro` folder!

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by johannschopplich** [comment]
I'm all in for a `prepare` command! At the moment, especially in monorepo-contexts, it's a bit cumbersome to manually call a custom prepare script like:

```ts
// @ts-check
import { createNitro, writeTypes } from 'nitropack'

export async function prepare({ rootDir = process.cwd() } = {}) {
  const nitro = await createNitro({
    rootDir,
  })

  await writeTypes(nitro)
}

prepare().catch(console.error)
```

**Comment by pi0** [comment]
PR more than welcome 👍🏼
