### ISSUE TITLE
Handle files and multipart/form-data

### ISSUE THREAD

**Issue by silvercent011** [unjs/nitro#698]
### Describe the feature

Should be great have a feature like multer on express and handle multipart/form-data on readBody() hook.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
This is supported by H3, so this should work already.

ts
```
export default eventHandler(event => {
const form = readMultipartFormData(event)
// do stuff
})
```

Implemented here
https://github.com/unjs/h3/blob/5f503c23286e431a249bf379b6bb779d62e71059/src/utils/body.ts#L111

**Comment by Hebilicious** [comment]
Leaving this opens until this is documented.

**Comment by MickL** [comment]
@Hebilicious 
Is it possible to limit what file types can be uploaded and what is the max file size?

Also I wonder if this counts as the documentation or is it still missing?
https://www.jsdocs.io/package/h3#readMultipartFormData

**Comment by shyamchen** [comment]
https://h3.unjs.io/utils/request#readmultipartformdataevent

**Comment by Shyam-Chen** [comment]
https://h3.unjs.io/utils/request#readmultipartformdataevent
