### ISSUE TITLE
Preset `digital-ocean` broken, errors with `ERROR: failed to launch: determine start command: process type web was not found`

### ISSUE THREAD

**Issue by madebyfabian** [unjs/nitro#710]
### Environment

Node.js 16, Nuxt3.

package.json:
```json
{
	"private": true,
	"engines": {
		"node": "16.x"
	},
	"scripts": {
		"build": "nuxt build",
		"dev": "nuxt dev",
		"generate": "nuxt generate",
		"preview": "nuxt preview",
		"postinstall": "nuxt prepare"
	},
	"devDependencies": {
		"nuxt": "3.0.0"
	}
}

```

### Reproduction

1. Created a new empty [nuxt project](https://github.com/madebyfabian/nuxt-on-digitalocean), and setuped like in tutorial https://nitro.unjs.io/deploy/providers/digitalocean. 
2. Now push to digitalocean with the global env variable provided while creating the new app project.
    ![Bildschirm­foto 2022-11-29 um 19 11 48](https://user-images.githubusercontent.com/32813692/204612170-f1da6599-d3bb-43ad-b175-d5816488911c.jpg)

The nuxt build itsself seems to run through, but after that, the console errors with:

`[2022-11-29 18:01:03] ERROR: failed to launch: determine start command: process type web was not found`

without any further information. I'm not a DigitalOcean expert, and if this is not related to the preset, I'll contact them.

### Describe the bug

Using the tutorial https://nitro.unjs.io/deploy/providers/digitalocean to deploy to digitalocean, the deploy errors with the code provided above. 

### Logs

[nuxt-on-digitalocean-build.txt](https://github.com/unjs/nitro/files/10115923/nuxt-on-digitalocean-build.txt)

**Comment by TrurlMcByte** [comment]
```json
{
   "scripts": {
      "start": "node .output/server/index.mjs"
   }
}
```

**Comment by madebyfabian** [comment]
@TrurlMcByte thanks for your addition! Cannot reproduce it anymore because it was just a test project, going to close this for now.
