### ISSUE TITLE
Add 'provide' option to Nitro Plugins.

### ISSUE THREAD

**Issue by lnstuder** [unjs/nitro#711]
### Describe the feature

It would be nice if you could provide objects from Nitro plugins, like you can with Nuxt plugins. In my opinion, this would make the usage of something like Prisma ORM with Nitro much easier.

For example using this syntax, inspired by Nuxt plugins:
```ts
import { PrismaClient } from "@prisma/client";

// plugins/prisma.ts
export default defineNitroPlugin((nitroApp) => {
  const prisma = new PrismaClient();

  return {
    provide: {
      db: prisma
    }
  };
});
```

If there is a better way to do this, or I am misunderstanding something, please let me know.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Meleemaru2k** [comment]
Would love that too, because I literally ran into just that...also with prisma.
Did you find a good way to get this done for now?

**Comment by manniL** [comment]
You can use a nitro middleware and do sth. like


```ts
import { PrismaClient } from '@prisma/client'

let prisma
export default defineEventHandler((event) => {
  if (!prisma) {
    prisma = new PrismaClient()
  }
  event.context.prisma = prisma
})
```

**Comment by manniL** [comment]
A workaround would be a middleware doing sth. like:

```ts
import { PrismaClient } from '@prisma/client'

let prisma
export default defineEventHandler((event) => {
  if (!prisma) {
    prisma = new PrismaClient()
  }
  event.context.prisma = prisma
})
```

**Comment by pi0** [comment]
For prisma, I simply do this:

Create `utils/prisma.ts` (`server/utils/prisma.ts` for nuxt):

```ts
import { PrismaClient } from '@prisma/client'

let _prisma: PrismaClient

export const usePrisma = () => {
  if (!_prisma) {
    _prisma = new PrismaClient()
  }
  return _prisma
}
```

You now have `usePrisma()` globally in any event handler with types support!

----

If a service needs context, you can pass `event` as well to cache it in `event.context` instead of global context.

```ts
import type { EventHandler } from 'h3'

export const useAPIClient = (event: EventHandler) => {
  if (!event.context.apiClient) {
    event.context.apiClient = new MyClient({ /* options basd on events */ })
  }
  return event.context.apiClient
}
```

You now have `useAPIClient(event)` in any event handler.

---

I would generally highly recommend the above solutions, over using a classic global initializer in plugins or middleware providing to the rest of the app. Both H3 and Nitro are designed to have low startup+runtime impact with this mindset.
  - Global services will be only initialized when the first handler needs them
  - Request services, will be only initialized when inside a handler, we reach to the first point that needs them

If you prefer, you can still use `useNitroApp().prisma = new PrismaClient()` to access it in other places with `useNitroApp().prisma`.

**Comment by awdr74100** [comment]
Thank @pi0 for your detailed and clear answer!

So what to do with `$connect()`?

```ts
// @/server/utils/prisma.ts

import { PrismaClient } from '@prisma/client';

let _prisma: PrismaClient;

export const usePrisma = () => {
  if (!_prisma) _prisma = new PrismaClient();

  return _prisma;
};
```

```ts
// @/server/plugins/prisma.ts

export default defineNitroPlugin(async (nitroApp) => {
  const prisma = usePrisma();

  await prisma.$connect();
});
```

**Comment by pi0** [comment]
As far as i know, prisma does the connection on first query (it is not required) but if any other usecase needs it, we can cache the promise and access utility as `const db = await useDBConnection()`

**Comment by trylovetom** [comment]
> For prisma, I simply do this:
> 
> Create `utils/prisma.ts` (`server/utils/prisma.ts` for nuxt):
> 
> ```ts
> import { PrismaClient } from '@prisma/client'
> 
> let _prisma: PrismaClient
> 
> export const usePrisma = () => {
>   if (!_prisma) {
>     _prisma = new PrismaClient()
>   }
>   return _prisma
> }
> ```
> 
> You now have `usePrisma()` globally in any event handler with types support!
> 
> If a service needs context, you can pass `event` as well to cache it in `event.context` instead of global context.
> 
> ```ts
> import type { H3Event } from 'h3'
> 
> export const useAPIClient = (event: H3Event) => {
>   if (!event.context.apiClient) {
>     event.context.apiClient = new MyClient({ /* options basd on events */ })
>   }
>   return event.context.apiClient
> }
> ```
> 
> You now have `useAPIClient(event)` in any event handler.
> 
> I would generally highly recommend the above solutions, over using a classic global initializer in plugins or middleware providing to the rest of the app. Both H3 and Nitro are designed to have low startup+runtime impact with this mindset.
> 
> * Global services will be only initialized when the first handler needs them
> * Request services, will be only initialized when inside a handler, we reach to the first point that needs them
> 
> If you prefer, you can still do `useNitroApp().prisma = new PrismaClient()` in a plugin to access it in other places with `useNitroApp().prisma` or better make a companion utils file that exports `usePrisma()` for types support.

Thanks @pi0, I must say, your approach to using the Prisma Client is very clear and concise! You've made it incredibly easy to understand how to implement and use it. I am impressed with the way you've structured the code.

However, I am curious about how to gracefully shut down the Prisma Client. Could you kindly provide some guidance or best practices on handling a graceful shutdown? Your expertise would be greatly appreciated.

**Comment by pi0** [comment]
Thanks for the kind words and happy it was helpful @trylovetom. 

I think you need to depend on a node worker event for dev preset to gracefully shutdown. Let me check and come back to you.

**Comment by trylovetom** [comment]
@pi0 This topic is important as it may be related to proper resource management and ensuring a smooth application shutdown process, as well as being potentially connected to [nuxt #9219](https://github.com/nuxt/nuxt/issues/9219). Your insight and guidance on this matter would be greatly appreciated.

**Comment by trylovetom** [comment]
@pi0 Hello! I've come across a few workarounds that seem to address this issue. If you have some time, would you mind taking a look and providing your thoughts?

You can find the workarounds here: https://github.com/nuxt/nuxt/issues/19888#issuecomment-1542111353. Your feedback would be much appreciated!

**Comment by pi0** [comment]
Since Nitro is aiming to be a composable framework, this pattern won't be supported (nor I would advice to use plugins to inject server-wide utils, please consider `utils/` dir instead)
