### ISSUE TITLE
GitHub Issues template doesn't apply default labels

### ISSUE THREAD

**Issue by NozomuIkuta** [unjs/nitro#713]
### Environment

This is not a bug in Nitro itself but in GitHub Issues templates.

### Reproduction

While `pending triage` label is set as default label in GitHub Issues templates, they are not applied when you create issues.

- https://github.com/unjs/nitro/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml
- https://github.com/unjs/nitro/blob/main/.github/ISSUE_TEMPLATE/feature-request.yml

### Describe the bug

`pending triage` label is not applied by default just because the label is not registered in this repository.

You can fix this bug just by registering the label, or by setting another label in the templates.
I don't have a permission to register labels, so need maintainers' help. 🙌 

### Additional context

N/A

### Logs

```sh
N/A
```

**Comment by manniL** [comment]
Label created! Thanks ☺️

**Comment by NozomuIkuta** [comment]
@manniL 

Oh, it seems that you have created `pending-triage` label, which is hyphenated.
But, the label in GitHub Issues templates is space-separated, `pending triage`.

You can check if default label works by going to Issue Create pages (direct links are below):

- https://github.com/unjs/nitro/issues/new?assignees=&labels=pending+triage&template=bug-report.yml
- https://github.com/unjs/nitro/issues/new?assignees=&labels=pending+triage&template=feature-request.yml

**Comment by manniL** [comment]
My bad! THanks for the heads up 😋
