### ISSUE TITLE
`getRouterParam`/`getRouterParams` are empty in middleware.

### ISSUE THREAD

**Issue by sasial-dev** [unjs/nitro#715]
### Environment

Nitro: `1.0.0`
Node.js: `16.16.0`

### Reproduction

Repo: https://github.com/sasial-dev/nitro-middleware-repro

1. Run `yarn dev`
2. Go to http://localhost:3000/test/param/ (param can be substitued for your choice)
3. You will see the following:
<img width="789" alt="Brave Browser-n1hq2lHw@2x" src="https://user-images.githubusercontent.com/44125644/204681655-92c95966-a5a3-4084-baf4-8115037e1b89.png">

### Describe the bug

`getRouterParam`/`getRouterParams` are empty in middleware.

### Logs

```sh
(from my logging):

PARAM: undefined
PARAMS: {}
```

**Comment by pi0** [comment]
Middleware runs before the router in the stack. Making it possible requires changing the underlying design of h3 middleware. (PS: route params actually make sense in a matched route not middleware before them)
