### ISSUE TITLE
Support `app.config`

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#728]
Similar to Nuxt 3's `app.config` feature (https://github.com/nuxt/nuxt.js/issues/14670), nitro could support app.config as well. Benefit over runtime config is that it can be extended per-request from any source (not just environment variables). It also benefits Nuxt for consistent support for `app.config` (Nuxt might use namespacing for server)

**Comment by gitFoxCode** [comment]
Any news on this?

**Comment by pi0** [comment]
It is little bit tricky to support as we need to _map_ `server` key in `app.config` from a nuxt project to `app.config` top level in Nitro.
