### ISSUE TITLE
CommonJS error when trying to `import { Pool } from 'pg'`

### ISSUE THREAD

**Issue by leo91000** [unjs/nitro#73]
### Environment

NodeJS version : 14.16.2
Nitropack : 0.2.2

### Reproduction

- Install the library "pg" (e.g : `npm i pg`)
- Use `import { Pool } from 'pg'` in a route

### Describe the bug

I have a problem when trying to import `Pool` from 'pg', a postgres library to connect to a postgres database.

I get the following error :

```
SyntaxError: Named export 'Pool' not found. The requested module 'file:///project_root/node_modules/.pnpm/pg@8.7.3/node_modules/pg/lib/index.js' is a CommonJS module, which may not support all module.exports as named exports.
```

Nitro then make the recommandation to use use the default export, however it still doesn't work, I get a typescript error : `Module pg has no default export`.

Is there a way to get around the problem ? If no do you know any esm library for postgres ?

**Comment by immannino** [comment]
I ran into this same issue! Pool isn't explicitly exported. You can just import the entire package and call the Pool constructor:

```js
import pg from 'pg';

const pool = new pg.Pool(config);
```

**Comment by leo91000** [comment]
> I ran into this same issue! Pool isn't explicitly exported. You can just import the entire package and call the Pool constructor:
> 
> ```js
> import pg from 'pg';
> 
> const pool = new pg.Pool(config);
> ```

Thanks it works. However you can't bundle the lib `pg` to run on edge because it cannot bundle the optional peer dependency `pg-native`

**Comment by amandesai01** [comment]
This is addressed in https://github.com/unjs/db0/issues/62. Fix for this is available at https://github.com/unjs/db0/pull/63.

**Comment by pi0** [comment]
let's track via db0 issue.
