### ISSUE TITLE
Add possibility to change the default "/api" directory

### ISSUE THREAD

**Issue by enkot** [unjs/nitro#770]
### Describe the feature

There are scenarios when `/api` route handled by another server/proxy. To make it possible still send request to local Nuxt server without additional `/server/routes/front-api` directory, we can have `defaultApiDir` option in Nitro config.

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi @enkot. PR is welcome to introduce `apiDir` (filesystem) and `apiRoutePrefix` (route prefix /api) options 👍🏼 BTW in meantime, you can simply make a symlink using `ln -s server/api server/routes/front-api` to alias.

**Comment by enkot** [comment]
Hi @pi0. Great, thanks for the almost instant feedback! Will be happy to add it 👍🏼
