### ISSUE TITLE
Example in route handling docs still uses deprecated "useBody()"

### ISSUE THREAD

**Issue by pschnyder** [unjs/nitro#789]
### Environment

n/a

### Reproduction

I tried to set up a post endpoint and first copied the code from the example in the docs ([Link](https://nitro.unjs.io/guide/introduction/routing))

```
// routes/user.post.ts
export default eventHandler(async event => {
  const body = await useBody(event)
  // TODO: Handle body and update user
  return `User updated!`
})
```
It did not work. After some searching I found out that `useBody()` is deprecated: https://github.com/unjs/h3/issues/147#issuecomment-1202617183

Using `readBody()` did the trick. Updating the docs would be great!

### Describe the bug

see above

**Comment by manniL** [comment]
PR Welcome 👍🏻
