### ISSUE TITLE
CTA and links in light mode are pretty much unreadable

### ISSUE THREAD

**Issue by Todomir** [unjs/nitro#850]
### Describe the feature

In the docs, the yellow color used in active menu items and links in light mode, and as the background of the call to action button does not have enough contrast, making it really hard to read the text. I suggest changing it to a darker shade in light mode, and changing the text to black in the call to action so that the text can be readable.

e.g
![image](https://user-images.githubusercontent.com/39444892/213161815-f1d854f1-3574-434b-9fcb-7d5068415523.png)
![image](https://user-images.githubusercontent.com/39444892/213161849-8d26f372-d3ff-4948-9ac5-9dc73b9866dd.png)

to

![image](https://user-images.githubusercontent.com/39444892/213161609-d7518da8-ca03-4fc1-923a-e4d542d83b25.png)
![image](https://user-images.githubusercontent.com/39444892/213161761-05ea647a-a329-480d-9b58-91d81b2dfd51.png)

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
Closing this as the website has a new UI now.
