### ISSUE TITLE
Use unimport v3 built-in type gen for dirs

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#877]
Dep upgraded in https://github.com/unjs/nitro/pull/869

Context: https://github.com/unjs/unimport/issues/213

/cc @antfu Do you mind helping on this?

**Comment by antfu** [comment]
Do we have an example/playground with this feature set up? If not, should we create one for that?

**Comment by pi0** [comment]
Would be nice adding to playground indeed 👍🏼 (i think added a basic test in fixture)

**Comment by pi0** [comment]
You can also reproduce `.ts` issue by commenting out this line: https://github.com/unjs/nitro/blob/963c587308561cd24841cc279f0bc4f2b3db4d69/src/build.ts#L102 

Also `dirs` is still not effective in generated types.

**Comment by pi0** [comment]
Upgraded to v3 (https://github.com/unjs/nitro/pull/982). We also have an issue when adding new utility, full server reload is needed. need your help @antfu 🙏🏼

**Comment by antfu** [comment]
Theoretically v3 does not change the behaviour, but anyway I will have a look after lunch

**Comment by pi0** [comment]
Issue is from v2 :D
