### ISSUE TITLE
[Bug] Error using `getAsyncData` function in Nuxt 3 & `cloudflare` preset

### ISSUE THREAD

**Issue by kuohuanhuan** [unjs/nitro#901]
### Environment

Node.js v19.5.0 (also tested on 18.9.0)
Nuxt 3.1.1 with Nitro 2.1.1
Yarn Berry v3.1.1
wrangler 2.9.0

### Reproduction

```vue
<template>
  <div>
    ...codes...
    <div
      id="content"
      class="my-6 prose prose-neutral dark:prose-invert"
      v-html="mdParser.render(data.content)"
    ></div>
    ...codes...
  </div>
</template>

<script lang="ts" setup>
import MarkdownIt from 'markdown-it'
const { data } = await useAsyncData(
  `post/${useRoute().params.slug}`,
  () => $fetch(`/api/post/${useRoute().params.slug}`)
)

const mdParser = new MarkdownIt()
</script>
```

### Describe the bug

Error happens if reload the page.

### Additional context

I've tested, the error only happens if using the `cloudflare` preset of Nitro. (`$env:NITRO_PRESET="cloudflare"; yarn build` then `wranger dev`)

It works correctly with the development server of Nuxt (`yarn dev`), and also the `node-server` preset of nitro (`yarn build` then `node .output/server/index.mjs`).

Also, some workarounds like adding `{ server: false }` or the `<ClientOnly>` tag also works, but their user experience are really bad.

### Logs

```sh
[nuxt] [request error] [unhandled] [500] Cannot convert object to primitive value
  at Qd.format (worker.js:12531:164)
  at MarkdownIt$1.normalizeLink (worker.js:13892:27)
  at Array.Hp (worker.js:13613:27)
  at ParserInline$1.tokenize (worker.js:13726:48)
  at ParserInline$1.parse (worker.js:13737:17)
  at Array.Vu (worker.js:12949:57)
  at Core.process (worker.js:12995:15)
  at MarkdownIt$1.parse (worker.js:13948:24)
  at MarkdownIt$1.render (worker.js:13950:55)
  at worker.js:16911:1109
```

**Comment by manniL** [comment]
The problem looks more like it originates from importing and using `markdown-it`, which is likely not ready for usage out of the node environment.

**Comment by kuohuanhuan** [comment]
> The problem looks more like it originates from importing and using `markdown-it`, which is likely not ready for usage out of the node environment.

Yes, it's an issue caused by `markdown-it`. It doesn't work with Nuxt 3 server side rendering, either.

Closing and sorry for disturbing.
