### ISSUE TITLE
SWR does not work in per route setup. Node preset

### ISSUE THREAD

**Issue by oneart-dev** [unjs/nitro#905]
### Environment

Tested on:
 - Node.js version: 16.14.2 && v18.13.0
 - Nuxt ^3.1.2

### Reproduction

Minimal Reproduction:
https://stackblitz.com/edit/github-fuonyg?file=pages/index.vue

```bash
npm run build && npm run preview
```

### Describe the bug

SWR setting of 1800 seconds do not work as every page refresh we still getting freeze while promise resolved.
**Not working**
```js
routeRules: {
   '/': { swr: 1800 },
},
```

**Working**
Instant refresh as expected
```js
routeRules: {
   '/**': { swr: 1800 },
},
```

**Comment by manniL** [comment]
This does work as expected with a basic nitro example

https://stackblitz.com/edit/unjsnitroissues905?file=nitro.config.ts,routes%2Findex.ts,package.json

**Comment by oneart-dev** [comment]
@manniL ok, it does but it doesn't work with nuxt and very similar setup. What should I do? Create an issue in nuxt repository?

**Comment by manniL** [comment]
> @manniL ok, it does but it doesn't work with nuxt and very similar setup. What should I do? Create an issue in nuxt repository?

Actually yes, that'd be the best as it seems to be an integration issue on the "nuxt side" 😋

**Comment by oneart-dev** [comment]
Ok, issue created. I will leave this issue open for a bit in case ping pong between repositories send me back to nitro =)

**Comment by manniL** [comment]
I'd prefer closing it as the example above shows that it must be a nuxt-related topic 😄 
Worst case, we will reopen 😋
