### ISSUE TITLE
Inconsistent readRawBody behavior in some nitro presets

### ISSUE THREAD

**Issue by Twitch0125** [unjs/nitro#912]
### Environment

nitropack: 2.1.1
node: 18.12.1
deno: 1.30.2

### Reproduction

https://github.com/Twitch0125/nitro-inconsistent
(stackblitz works for node-server and cloudflare workers https://stackblitz.com/edit/nitro-inconsistent?file=readme.md)

1. `pnpm install`
2. `pnpm run:node-server` or `pnpm run:deno` or `pnpm run:cloudflare` 
### Describe the bug

It seems that some of the utils behave differently if they're in different environments. I'm not sure if this is actually an issue in Nitro, Unenv, or H3. Creating it for Nitro because it has the most stars so this might be seen by more people here.

When I try to get the raw body with `getRawBody` I'm seeing different return values if its running in Deno or Cloudflare Worker presets.

Given a handler that looks like this
```ts
export default eventHandler(async (event) => {
  const body = await readRawBody(event);
  return { body, type: typeof body };
});
```

I can send it this json payload 
```json
{ "test": "testing json" }
```

and I'll get 3 different responses

node:
```json
{"body":"{\"test\":\"testing json\"}","type":"string"}
```
deno:
```json
{"body":"blob:null/a9f116d7-5f24-4f78-a50f-aa6432394633","type":"string"}
```
cloudflare:
```json
{"body":{"type":"Buffer","data":[123,34,116,101,115,116,34,58,34,116,101,115,116,105,110,103,32,106,115,111,110,34,125]},"type":"object"}
```

### Additional context

Looking into the code a bit, it looks like readRawBody() is checking a `event.node.req.body` property and then returns whatever that is. I'd guess the issue is in whatever codebase is setting that `body` property.

**Comment by Atinux** [comment]
Could you confirm with latest version of Nitro @Twitch0125 ? 🙏

**Comment by Twitch0125** [comment]
> Could you confirm with latest version of Nitro @Twitch0125 ? 🙏
Updated to nitro 2.3.1 and I am still seeing this issue. The reproduction repo  and stackblitz link were also updated

**Comment by Atinux** [comment]
Seem related directly to h3: unjs/h3#363

**Comment by pi0** [comment]
https://github.com/unjs/h3/issues/363 will support Buffer for `readBody` but it might be safer option to choose. 

The core of different types backs to the fact that _raw_ input of providers is different (even for node for direct calls vs user fetch). While we might support to Buffer normalization more it adds more overhead.

**Comment by martinsotirov** [comment]
@pi0 Any ETA on this getting merged?

**Comment by pi0** [comment]
This should be fixed via https://github.com/unjs/h3/pull/366 and https://github.com/unjs/h3/commit/19d133d6a33ffb742713f4d83f00f555aeb83224

Please upgrade lockfile and ping me to reopen if either `readBody` or `readRawBody` (with second param `encoding` set to `false`) are not returning a Buffer type.

Thanks for reporting the issue ❤️
