### ISSUE TITLE
Server Assets default path confuse

### ISSUE THREAD

**Issue by serkodev** [unjs/nitro#914]
### Environment

nitropack v2.1.1
node v16.14.2

#### assets/data.json
```json
"File: assets/data.json"
```

#### assets/server/data.json
```json
"File: assets/server/data.json"
```

#### server/assets/data.json
```json
"File: server/assets/data.json"
```

#### routes/index.js
```js
export default defineEventHandler(async () => {
  const data = await useStorage().getItem(`assets/server/data.json`)
  return data
})
```

##  Run
```
pnpx nitropack dev
```
Visit `http://localhost:3000/`

### Describe the bug

In the nitro [document](https://nitro.unjs.io/guide/introduction/assets):
> All assets in `server/assets/` directory will be added automatically to the server bundle.

---

After reproduction above, you'll see it response `File: assets/data.json`.

That means the below code is getting assets from `assets/` from storage layer `assets/server/`.
```js
useStorage().getItem('assets/server/data.json')
```

So I think the document is wrong (should be `assets/` instead of `server/assets/`) ?

**Comment by pi0** [comment]
Hi dear @serkodev. Do you mind to open a PR to fix the docs? the `server/assets` is specific to Nuxt usrs. Normally using Nitro, everything is scoped in server.

**Comment by serkodev** [comment]
Hi @pi0. I've made a PR (#917) to fix it.
Thank you for the prompt reply.

**Comment by danielroe** [comment]
closed in https://github.com/unjs/nitro/pull/917

**Comment by pi0** [comment]
Since we are moving to use `server/` (https://github.com/unjs/nitro/issues/2195) as same convention in Nitro, this confusion would be fixed.
