### ISSUE TITLE
useStorage().clear() delete the project files in dev mode

### ISSUE THREAD

**Issue by emaia** [unjs/nitro#918]
Hi! I was playing around with Nuxt 3 and I saw a strange behavior with unstorage.
 
Nitro docs says: `By default storage is in-memory with mounted cache: prefix only for development.` 
https://nitro.unjs.io/guide/introduction/storage 

Unstorage docs says: `Options: driver: Default driver (using memory if not provided)`
https://github.com/unjs/unstorage#usage

So, I created a simple API endpoint to generate a random number and cache the response for 1 hour using `cachedEventHandler`.
http://localhost:3000/api/random

Cache was created in filesystem when running in dev. They should not be created in memory?

![image](https://user-images.githubusercontent.com/131877/202869977-d9153a3c-6978-479a-b96b-2714a438db98.png)

Then I created another API endpoint to log the cache keys and playing with remove them from the cache...
http://localhost:3000/api/cache

Using `await useStorage().clear('cache')` the cached files was removed as expected in dev. But in production it was not removed. 

![image](https://user-images.githubusercontent.com/131877/202869952-29f290f7-c900-4f51-9734-384e493638ec.png)

But, using `await useStorage().clear()` almost ALL files was removed... including .git, pages, middleaware and other files and folders in the project. This in prod build works as expected.

![image](https://user-images.githubusercontent.com/131877/202870425-c132fafe-4a9d-4f9d-a009-b11e106eea6b.png)

At this point I needed to clone my repo again.

I think this is not expected... I'm missing something?

Sample repo: https://github.com/emaia/nuxt-cache-reproduction

**Comment by pi0** [comment]
Sorry for incontinence 🙏🏼  This should have never happened. Latest version of nitro will be guarded to make mounts readonly by default. https://github.com/unjs/nitro/pull/920

**Comment by emaia** [comment]
Thks @pi0 !
