### ISSUE TITLE
Firebase preset defaults to Node 14

### ISSUE THREAD

**Issue by luc122c** [unjs/nitro#924]
### Environment

`node -v: v18.14.0`
`yarn -v: 1.22.19`
`firebase --version: 11.22.0`
<details>
<summary>nitropack@2.1.1</summary>
yarn why nitropack         
...
=> Found "nitropack@2.1.1"
info Reasons this module exists
   - "nuxt" depends on it
   - Hoisted from "nuxt#nitropack"
</details>

### Reproduction

Using the[ built in preset](https://nitro.unjs.io/deploy/providers/firebase).

### Describe the bug

Nitro's [current behaviour for Firebase](https://github.com/unjs/nitro/blob/6541373545ee2716566bce46c7568ad2c3164cdf/src/presets/firebase.ts#L68) is to default to Node 14, and upgrade to Node 16 if it is found in `package.json`. I believe the default should be Node 18, and to downgrade to an earlier version if `engines` is specified, for the reasons below. 

- [It's the recommended node runtime for cloud functions](https://cloud.google.com/functions/docs/concepts/nodejs-runtime)
- It's [supported by firebase tools](https://github.com/firebase/firebase-tools/pull/5319) (used for deployment)
- As the current LTS, [it's a prerequisite for Nuxt](https://nuxt.com/docs/getting-started/installation), and[ some modules](https://v1.image.nuxtjs.org/get-started#troubleshooting).

**Comment by danielroe** [comment]
I agree with this. PR would be welcome ❤️

**Comment by luc122c** [comment]
> I agree with this. PR would be welcome ❤️

I've started PR #925. It's my first time contributing here so any advice/feedback is welcome.
