### ISSUE TITLE
cannot build project in pnpm monorepo with externals disabled (cloudflare)

### ISSUE THREAD

**Issue by manniL** [unjs/nitro#947]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `pnpm@7.27.0`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Clone [the repo](https://github.com/manniL/nitro-pnpm-monorepo-cf-preset)
1. `pnpm i`
1. `pnpm --filter app build`
1. See error in the console

### Describe the bug

The build process throws an error saying:

>  Error: Cannot resolve "source-map-support/register.js" from "\u0000virtual:#internal/nitro/virtual/polyfill" and externals are not allowed!

**Comment by manniL** [comment]
Good catch, indeed!

**Comment by eladcandroid** [comment]
Any news?
My build for NITRO_PRESET=vercel-edge isn't working and I see the same error about externals...
