### ISSUE TITLE
proxy is broken with direct fetch and streaming

### ISSUE THREAD

**Issue by motea927** [unjs/nitro#950]
### Environment

Nuxt 3.2,
Node 18

### Reproduction
[online reproduction](https://stackblitz.com/edit/nuxt-starter-u19zth?file=app.vue)

### Describe the bug
When using `proxyRequest` with large data, response is broken,
I find an online fake json api from [jsonplaceholder](https://jsonplaceholder.typicode.com/),
And use [photos](https://jsonplaceholder.typicode.com/photos) API, 
We will find that, `directFetchData`(blue border in the UI) is good, 
But `proxyData` is broken (black border in the UI).

**Comment by pi0** [comment]
Hi dear @motea927 thanks for reporting issue with reproduction.

Investigating it, if you open `/api/photos` you can see the response is valid. Also if you use `useFetch(URL, { server : false }`. H3 proxy utility works as expected. However there is a catch here! 

When you use `useFetch` or `$fetch` in a Nuxt SSR application and using relative URLs such as `/api/photos`, nitro uses a technique called direct fetch. It emulates network request to remove latency time using [unenv](https://github.com/unjs/unenv). 

H3 proxy uses streaming by default (sending response in multiple chunks to speed up) and unenv is not compatible with stream yet. 

As a workaround you can use `sendStream: false` in your API route (or route rule for proxy) to make it working:

```js
return proxyRequest(event, target.toString(), { sendStream: false });
```

**Comment by motea927** [comment]
Incredible effectiveness, thank you very much.
