### ISSUE TITLE
Output dir creates wrong folders

### ISSUE THREAD

**Issue by notflip** [unjs/nitro#960]
### Environment

```
    nitro: {
        output: {
            dir: './build',
        }
    },
```

Will generate
`./server/build/server/` and `./server/build/public` 
instead of `./build/server` and `./build/public`

### Reproduction

Run `yarn build` with this configuration

```
    nitro: {
        output: {
            dir: './build',
        }
    },
```

### Describe the bug

A folder called `server` is prepended to the required result

**Comment by danielroe** [comment]
If you are using Nuxt, then this is actually the right behaviour, even if unexpected, as these folders are resolved relative to the _nitro_ source folder, which is `~/server`. You can instead use `~/build`.

(It might be worth improving the DX on this one within Nuxt - but it's not a nitro issue.)

**Comment by Hebilicious** [comment]
@notflip resolved with daniel suggestion
