### ISSUE TITLE
lagon preset

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#966]
Upstream issue https://github.com/lagonapp/lagon/issues/258

Progress:

- [ ] Gather some more information about platform status to be mentioned in **public docs**
- [x] Add `lagon` preset by @danielroe  (https://github.com/unjs/nitro/pull/964)
- [x] Support lagon config (https://github.com/unjs/nitro/pull/996)
- [ ] Extend documentation instructions (self hosting and GitHub actions)

(currently all deployments give 404)

**Comment by danielroe** [comment]
> (currently all deployments give 404)

Do you have any more information @pi0? Was this temporary? Here's a deployment that seems to be working: https://nuxt.lagon.dev/

**Comment by pi0** [comment]
Server errors happen randomly. Also https://nitro-app.lagon.dev/

**Comment by QuiiBz** [comment]
I'm debugging an issue with uploading empty files that cause deployments not to be deployed (`robots.txt` for nitro-app is empty). I'll keep you updated!

**Comment by fago** [comment]
when testing this, I ran into the 100 assets limit. I guess it would be great if nuxt/nitro could be aware of the limit and warn/handle it.
