### ISSUE TITLE
Nitro ErrorHandler

### ISSUE THREAD

**Issue by cosbgn** [unjs/nitro#983]
### Environment

Nuxt 3.2

### Reproduction

https://stackblitz.com/edit/nuxt-starter-htdfyf?file=server%2Fapi%2F500.js,server%2Fapi%2F200.js,app.vue,server%2Fplugins%2Ferrors.js,package.json

### Describe the bug

I want to be able to catch server error using nuxt 3. I've made a nitro plugin

```
// server/plugins/errors.js
export default defineNitroPlugin((nitroApp) => {  
    nitroApp.hooks.hook('render:response', (response, { event }) => {
		console.log(`Status is: ${response.statusCode} - ${Object.keys(response).join(", ")}`)
    })
})
```

My issue is that it gets called only on non errors. Any way to be able to run this also on errors? What's the best way to set an error handler?

**Comment by mao-shonen** [comment]
There is currently no corresponding callHook.
use nitro option?
reference:
https://nitro.unjs.io/config#handlers
https://github.com/unjs/nitro/blob/main/examples/custom-error-handler/nitro.config.ts

**Comment by JakobHock** [comment]
In my use case, I would like to hook into the requests being sent, capturing the method and path, to identify what and where the most errors occur. While the error hook can catch all server errors, it does not provide information on whether these errors stem from a side effect or an API call.

I am able to hook into the request and create a 'two-part log message,' but the error hook is invoked before the request hook. Is there another way to achieve this?
