### ISSUE TITLE
Import error when building cloudflare_pages pack

### ISSUE THREAD

**Issue by richtera** [unjs/nitro#986]
### Environment

WLS2 or CI
node v16.19

### Reproduction

I am not sure exactly what the error is since I do not import or require events directly.

The error just says
```sh
 ERROR  Could not load /home/andy/Development/project/node_modules/unenv/runtime/node/events/index/.cjs: ENOENT: no such file or directory, open '/home/andy/Development/project/node_modules/unenv/runtime/node/events/index/.cjs'
```
So for some reason in this particular case it interprets the alias as a file even though it's a directory. Tracing through the rollup config the alias is unenv/runtime/node/events without a slash at the end.

To reproduce all I have to do is run a build with a nodeless server. In this case:
```sh
NITRO_PRESET=cloudflare_pages yarn build
```

### Describe the bug

Somehow the import is misinterpreted as a file after having a slash added at the end of the id.

### Additional context

This started happening after adding some new external dependencies and features, but I am unable to get the location of the problem. ripgrepping through all sources and node_modules doesn't show any strange usage of require('events') or import from 'events' or import from 'node:events' or anything like that.

### Logs

```sh
The error is the log.
```

**Comment by danielroe** [comment]
What versions of `unenv`/`nitropack` do you have installed? We fixed a very similar issue some time ago.

**Comment by richtera** [comment]
unenv is 1.2.1
nitropack is 2.2.3
I don't have any custom resolutions so according to nuxt it's latest.

**Comment by pi0** [comment]
Hi. Is it possible to provide a reproduction? 🙏🏼

**Comment by richtera** [comment]
I can try to extract a reproducible section of the code. In the mean time I turned off SSR
